### ISSUE TITLE
Stopped working after update

### ISSUE THREAD

**Issue by Gamer-one** [termux/termux-app#1013]
------------------------error message-----------------------
CANNOT LINK EXECUTABLE "-bash": library "libandroid-support.so" not found
[Process completed (signal 6) - press Enter]

----------------------------------------------------------------------
-Galaxy s7 edge
-Custom Android Oreo (rooted)

**Comment by Grimler91** [comment]
A broken libandroid-package was unfortunately pushed to the repo a week ago or so, and everyone who did an `pkg upgrade` on android < 8 devices during a timespan of a couple of hours experienced this. To fix this you have to run some commands from a fail-safe shell. The steps are described in this comment: https://github.com/termux/termux-packages/issues/3283#issuecomment-457910719

**Comment by Grimler91** [comment]
It isn't on the repo. It's also possible to trigger the issue by doing a partial upgrade, i.e. only updating some packages, maybe that is what happened here

**Comment by cipher015** [comment]
@Grimler91 can you help to fix this,when i run 'sudo su' on my termux?
CANNOT LINK EXECUTABLE: could not load library "libiconv.so" needed by "mkdir"; caused by library "libiconv.so" not found
CANNOT LINK EXECUTABLE: could not load library "libiconv.so" needed by "chmod"; caused by library "libiconv.so" not found
tmp-mksh: can't create /data/data/com.termux/files/home/.suroot/.bashrc: No such file or directory
CANNOT LINK EXECUTABLE: could not load library "libiconv.so" needed by "chmod"; caused by library "libiconv.so" not found

**Comment by cipher015** [comment]
And when i'm installing tools like crips i've got like this problem
fatal: could not create leading directories of '/usr/share/doc/Crips': Read-only file system
CANNOT LINK EXECUTABLE: could not load library "libiconv.so" needed by "mkdir"; caused by library "libiconv.so" not found
CANNOT LINK EXECUTABLE: could not load library "libiconv.so" needed by "chmod"; caused by library "libiconv.so" not found
tmp-mksh: can't create /data/data/com.termux/files/home/.suroot/.bashrc: No such file or directory
CANNOT LINK EXECUTABLE: could not load library "libiconv.so" needed by "chmod"; caused by library "libiconv.so" not found
/data/data/com.termux/files/usr/bin/cp: cannot create regular file '/usr/bin/': No such file or directory
[✘] Installation faid![✘]

**Comment by Grimler91** [comment]
@cipher015 looks like your packages are not updated (since you get libiconv errors). Run `pkg upgrade`.

In the second screenshot you are trying to install something to `/usr`, which doesn't work in termux, you need to configure with `--prefix=$PREFIX` (or perhaps edit a Makefile if your project doesn't use a configure script)

**Comment by cipher015** [comment]
Thank you very much  for your fast responds.

Pada tanggal Sab, 15 Jun 2019 03.08, Henrik Grimler <
notifications@github.com> menulis:
