### ISSUE TITLE
restore previous shortcut layout

### ISSUE THREAD

**Issue by daufinsyd** [termux/termux-app#1034]
Hi, first of all thank you for this app, it's really amazing ! :)
Since the last update, the icon shortcuts changed. There is no more the left and right arrows which is really annoying since I can't move forward and backward :( (yes with Ctrl+b/w but that's incredibly tedious and inconvenient)

Could you add the left and right arrows ?
Thanks

**Comment by Grimler91** [comment]
I think you are talking about the extra-keys row.
You can specify which keys you want to have by putting it in `~/.termux/termux.properties`. See https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row for an example and some more information.

**Comment by daufinsyd** [comment]
Yes, Thank you !

**Comment by gulhe** [comment]
The `extra-keys` array of arrays in `~/.termux/termux.properties` is a very nice thing which I gladly adopt :)
However, since I did, all the keys I requested dispatched in 3 rows appear but the "textual keys" like `CTRL`, `PGUP` and such appear weirdly, only the two first letters of each appear atop each other.
All the buttons are crammed to the left of the screen except the last on of the last row which is in the middle ...
![Weird](https://user-images.githubusercontent.com/985787/54110105-cb0ef080-43e0-11e9-99db-9a352b7036db.jpeg)
My config is :
extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN'],['~', '|','`','(',')','[',']','{','}','<','>']]
in ~/.termux/termux.properties

**Comment by daufinsyd** [comment]
@gulhe you should open a new issue
1 issue = 1 specific problem :)

**Comment by gulhe** [comment]
thought it was close enough but I guess you are right
