### ISSUE TITLE
Termux blocks android with side effekts on launch after upgrade

### ISSUE THREAD

**Issue by justf0rfun** [termux/termux-app#1035]
When starting Termux the screen fades repeatingly between dark and some turky color. The only thing I found yet on what the system reacts is pressung the power button down. Then I get the dialog to shutdown or restart the system. I can't get to the home screen or to the list of running apps.

After restart the background image is gone! It looks similar to the color I described abhove which is fading in loop. MAYBE it is a default background. 

I'm not sure what happens. Termux does not run correctly and does not really crash. MAYBE Termux is in something like a restart loop.

Termux was running fine before so probably it has something to do with recent Germicidal upgrades. 

Termux 0.66 (installed from F-Droid)
Android 6.0
Phone Meizu MX6 with Flime 5.2.4.0G
Hacker's Keyboard

**Comment by justf0rfun** [comment]
Just switched back to Version 0.65 and its working fine on first try. So the issue seems indeed to came with changes between versions 0.65 to 0.66. 

Maybe I can support you with additional debug information if I learn how to do that.

**Comment by xeffyr** [comment]
If Termux crashing the component of your OS, then nothing can be done there (behaviour similar to https://github.com/termux/termux-app/issues/991).

**Comment by xeffyr** [comment]
Can you try the Termux APK from post https://github.com/termux/termux-app/issues/991#issuecomment-466027732 ?

**Comment by SBanya** [comment]
Hey xeffyr, I'm commenting since there's no public forum for this GitHub repo. I'm wanting to help contribute to this project by looking at bug fixes, and would like to use this is as a cool way to learn Java.

Can you please mark any of the open issues as "Beginner" so that someone like myself can help out, and help test / do some related bug fixes?

Thanks, my email is SBanya@outlook.com if you have any more details regarding contributing to the Termux project.

I know there's a contribution guide, but I would also prefer if someone that is a lead on this team kind of steer me in the right direction with helping contribute, since I really think this project is great (been using it on my phone for a couple months now).

**Comment by Grimler91** [comment]
Hi @SBanya, nice to hear that you want to contribute! Please join the gitter channels (or mirrored IRC channels): https://wiki.termux.com/wiki/Community. We also have a `termux/termux-dev` gitter room dedicated to development related discussions, where we also have weekly scheduled discussions: https://wiki.termux.com/wiki/Dev:Development_Sessions. 

We can probably come up with some good suggestions for a first project if you drop by the termux-dev channel!
