### ISSUE TITLE
Unable to get rid of this error since 6 hours 

### ISSUE THREAD

**Issue by Ashishm0nk** [termux/termux-app#1062]
$ apt update
Ign:1 https://termux.net stable InRelease
Err:2 https://termux.net stable Release
  The HTTP server sent an invalid reply header
Reading package lists... Done
E: The repository 'https://termux.net stable Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
$

**Comment by xeffyr** [comment]
* Check if you have a **stable connection**. Run `ping -c 10 termux.net`, command should finish successfully without lost packets and high-ping spikes.

* Check if there no censorship campaigns in your country. Since `termux.net` is behind [CloudFlare](https://www.cloudflare.com/) which is a large CDN, it may be a victim of access blocking.

As last thing, I may only suggest to disable HTTPS in your sources.list. Edit file `$PREFIX/etc/apt/sources.list` and carefully replace occurrencies of `https` with `http`.

For further notes, there no problems with `termux.net`, so everything is either in **your network** or **device**.
