### ISSUE TITLE
Feature Request: open Termux in a certain directory. **WITH Cooperating File Manager**

### ISSUE THREAD

**Issue by evan0greenup** [termux/termux-app#1070]
I have post this request before, but forget to attach the link to the file manager's homepage. Sorry about that.

# Feature description
Open Termux in a certain working directory specified by other Apps (File Manager).

In other words, provide a intent to other Apps.

# Reference implementation
Terminal App: I have only used Termux before.

The file manager waiting for the intent:
[android-file-manager](https://gitlab.com/axet/android-file-manager)
[On F-Droid](https://f-droid.org/en/packages/com.github.axet.filemanager)

**Comment by evan0greenup** [comment]
@xeffyr , How is the implementation of this feature going? Have the core team of termux communicate with the developer of android-file-manager?

**Comment by stevenleeS0ht** [comment]
This request is interesting, I would like to have a try.

**Comment by linsui** [comment]
Material File can't make `Open in terminal` work with Termux without this feature, see zhanghai/MaterialFiles#183 . Thanks!

**Comment by MuntashirAkon** [comment]
A sort of hacky method that I can think of is using something like below:
```java
        Intent intent = new Intent();
        intent.setClassName("com.termux", "com.termux.app.RunCommandService");
        intent.setAction("com.termux.RUN_COMMAND");
        intent.putExtra("com.termux.RUN_COMMAND_PATH", "/data/data/com.termux/files/usr/bin/bash");
        intent.putExtra("com.termux.RUN_COMMAND_WORKDIR", "/directory/to/open");
        intent.putExtra("com.termux.RUN_COMMAND_BACKGROUND", false);
        try {
            startService(intent);
        } catch (Exception e) {
            e.printStackTrace();
        }
```
This obviously requires the user to add `allow-external-apps=true` in `~/.termux/termux.properties` and the app has to request `com.termux.permission.RUN_COMMAND`. It might be necessary to open Termux app itself if it's not currently running though.

**Comment by xeffyr** [comment]
@MuntashirAkon Right, this can be used as solution. It's not "hacky" actually. Other method would be just a shortcut for same service launch intent.

> intent.putExtra("com.termux.RUN_COMMAND_PATH", "/data/data/com.termux/files/usr/bin/bash");

Use `/data/data/com.termux/files/usr/bin/login` instead.

> It might be necessary to open Termux app itself if it's not currently running though.

It will be opened automatically if not running.

**Comment by MuntashirAkon** [comment]
> Use `/data/data/com.termux/files/usr/bin/login` instead.

Thanks for the info.

**Comment by MuntashirAkon** [comment]
> It will be opened automatically if not running.

In that case, the service must be started in the foreground.

**Comment by zhanghai** [comment]
Hi, author of [zhanghai/MaterialFiles](https://github.com/zhanghai/MaterialFiles) here. I read https://github.com/termux/termux-app/issues/1070#issuecomment-668278572 and agree that it may work, but still hope that we can solve this with a different approach:

1. Activity v.s. Service: Ideally since we are intending to launch a new UI screen for user to issue shell commands, the sementically correct thing to do is to start an `Activity` instead of a `Service`. This also results in requiring the user to either manually click on a notification, or grant unnecessary permissions to Termux, which could have been fine with the semantically correct approach of starting an `Activity`.

    > To automatically bring to foreground and start termux commands that were started with
    > background mode "false" in android >= 10 without user having to click the notification manually,
    > requires termux to be granted draw over apps permission due to new restrictions
    > of starting activities from the background, this also applies to Termux:Tasker plugin.

2. Permission: The ability to run any command is too powerful for the use case of simply starting a terminal with a certain working directory, which is harmless, so having to request and be granted a runtime permission seems both tedious and unnecessary just for starting a terminal with a certain working directory.

3. Hardcoding: The approach above requires hardcoding `"/data/data/com.termux/files/usr/bin/login"`, which should ideally be an unrelated detail to the intention of simply starting a terminal with a certain working directory.

So I'm proposing to add an intent extra for working directory on the main activity instead. This approach doesn't have any of the problems above, and is the apporach chosen by some other well known applications:

1. The good old [jackpal/Android-Terminal-Emulator](https://github.com/jackpal/Android-Terminal-Emulator) supports `ACTION_SEND` on a `TermHere` activity for passing in an intial working directory ([source](https://github.com/jackpal/Android-Terminal-Emulator/blob/35188f8a8b57989a4a4ec9485e11187b46be26d9/term/src/main/AndroidManifest.xml#L61)). Notably, it also supports running custom scripts and protects that ability behind a runtime permission in the meantime, so the two are not in conflict and can instead be different features for different purposes, with different protection.

2. On desktop, `gnome-terminal` supports the command line argument `--working-directory=DIRNAME` ([source](https://manpages.debian.org/unstable/gnome-terminal/gnome-terminal.1.en.html)), which is also used by Nautilus for implementing the "Open terminal here" in its right-click context menu.

3. `kconsole` supports `--workdir dir` for the initial working directory as well ([source](https://docs.kde.org/stable5/en/applications/konsole/command-line-options.html)).

**Comment by evan0greenup** [comment]
@xeffyr , Do you plan to add the intent suggested by @zhanghai  ?

**Comment by agnostic-apollo** [comment]
@zhanghai

1. You should be able to send a `RUN_COMMAND` intent to the `RunCommandService` and then launch the `TermuxActivity` from your own app and it should be brought to foreground if Termux itself can't be granted Draw over apps permission for some reason.
2. Something like that could be considered in future with a dialog shown first.
3. You can use `$PREFIX/bin/login` instead, it has been fully functional since Termux app [`v0.109`](https://github.com/termux/termux-app/releases/tag/v0.109). Forks should/can support that too.
