### ISSUE TITLE
Exiting tsu shell causes the normal shell to mess up

### ISSUE THREAD

**Issue by DaBoss5** [termux/termux-app#1119]
Problems are:

1) Characters that are typed will not be displayed (although the command will run)

2) Pressing enter will cause the prompt character to print on the same line instead of a different one.

3) Command output is displayed with bad formatting

Any help would be appreciated.

**Comment by Grimler91** [comment]
Running reset or starting a new shell will restore to the normal behaviour. 

This can happen when some applications crash/are exited forcefully, it probably isn't related to tsu.

**Comment by DaBoss5** [comment]
Reset works temporarily, as it fixes the shell when I run it after exiting tsu. However, this phenomenon still continues to occur everytime tsu is used.

**Comment by Grimler91** [comment]
I can't reproduce it. Make sure your packages are up to date. If it still doesn't work then please post output of `termux-info`

**Comment by DaBoss5** [comment]
Here is the output of `termux-info`:

```Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.18.61-SuperStock_SM-G930F_V2.7.1 #1 SMP PREEMPT Wed Jul 19 10:55:32 CEST 2017 aarch64 Android
Termux-packages arch:
aarch64
Android version:
7.0
Device manufacturer:
samsung
Device model:
SM-G930F

**Comment by Moufunliux** [comment]
I have the same problem as my **termux-info** below:

Packages CPU architecture:
aarch64                                                    
Subscribed repositories:
\# sources.list
deb https://termux.org/packages/ stable main
\# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
\# root-repo (sources.list.d/root.list)                     
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
Updatable packages:
Running as root. Cannot check package updates.
Android version:
7.1.2
Kernel build information:
Linux localhost 3.18.31-perf-g0c1247c3554 #1 SMP PREEMPT Mon Apr 9 08:38:20 CST 2018 armv8l Android
Device manufacturer:
smartisan
Device model:
OC105

I can sure this problem comes from **tsu**, as without **tsu**, the command '**su**' works correctly. With  **zsh** the problem "**Characters that are typed will not be displayed (although the command will run)**" get fixed. this shows maybe the real problem is which the **tsu** returns that  **bash** could not work with correctly.

![Screenshot_2019-11-30-18-02-37-871_Termux](https://user-images.githubusercontent.com/43723233/69899036-db666180-139b-11ea-8985-5021a3d5a010.png)
