### ISSUE TITLE
cp -i does not prompt before overwrite (cp from busybox)

### ISSUE THREAD

**Issue by Emil-7** [termux/termux-app#114]
termux behaviour:
`$ touch 1 2`
`$ cp -i 1 2`
`$`

expected behaviour:
`$ touch 1 2`
`$ cp -i 1 2`
`cp: overwrite '2'?`

`mv -i` works as expected, but not `cp -i`

**Comment by danalgen** [comment]
FWIW, this works for me. Maybe OP has another version?

$ touch 1 2
$ cp -i 1 2
cp: overwrite '2'? y
$ cp --version
cp (GNU coreutils) 8.25
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbjorn Granlund, David MacKenzie, and Jim Meyering.
$

**Comment by Neo-Oli** [comment]
@danalgen You're running the coreutils version of cp because you installed it sometimes with `apt install coreutils`. OP is probably running the busybox version of cp, which is a lightweight version, that comes pre-installed with termux (which according to the help should still support -i). 

@Emil-7 Thanks for reporting this issue. If you just need it fixed fast, you an install coreutils with `apt install coreutils`, which has a more complete version of cp.

**Comment by fornwall** [comment]
This does indeed looks like a bug in busybox - I have now reported it upstream at https://bugs.busybox.net/show_bug.cgi?id=9106.

**Comment by Emil-7** [comment]
@Neo-Oli, @fornwall: Thanks for pinpointing the cause of this bug and reporting it to busybox!

**Comment by danalgen** [comment]
It does seem to be a bug in busybox (see the link provided by fornwall above). However it also seems to be possible to get the desired behaviour by setting the config option 'Non-POSIX, but safer, copying to special nodes' (under Busybox Settings, Busybox Library Tuning).

Busybox default config seems to set the 'Non-POSIX, but safer [...]' option but presumably there is a reason Termux has un-set it?

**Comment by fornwall** [comment]
@danalgen Nice find!

I guess `CONFIG_FEATURE_NON_POSIX_CP=y` is a reasonable thing to set?

There is no good reason for it not being set - it's just that [the busybox config file used in Termux](https://github.com/termux/termux-packages/blob/master/packages/busybox/busybox.config) was created by copying `configs/android_defconfig` as a starting point, and that one has `# CONFIG_FEATURE_NON_POSIX_CP is not set`.

**Comment by danalgen** [comment]
@fornwall The difference is that cp open the destination file with O_EXCL instead of O_TRUNC, and therefore fails if the file already exists. If open faiils, the destination is unlink:ed and then open:ed again. This means there is a difference in behaviour if the destination is a symlink! Busybox dev's made a long argument about the security risks with the O_EXCL and the symlink. (See the file libbb/copy_file.c and the FEATURE_NON_POSIX_CP in Busybox if you want to check the code yourself).

**I must confess I only did a code review and testing on x86/Linux, not actually on Android. So maybe there is a caveat there, but I think it is worth trying.**

Btw, from the comments in Busybox it seems that coreutils cp follow the Posix definition (using O_EXCL) but have a longoption --remove-destination to unlink the destination before copying.

**Obviously the bug should be fixed in Busybox to stat (or similar) and ask BEFORE trying open, so a change in the config should be considered a workaround**
