### ISSUE TITLE
Quick launch in application drawer

### ISSUE THREAD

**Issue by twaik** [termux/termux-app#1203]
Is it possible to add Quick launch shortcuts to navigation drawer? 
Shortcuts can be opened in new terminal instead of bash and close terminal after the command was finished. And may be it is possible to add options: icon, colour, is new terminal session start needed or not.

**Comment by xeffyr** [comment]
> Shortcuts can be opened in new terminal instead of bash and close terminal after the command was finished.

Exactly what Termux:Widget does.

> is new terminal session start needed or not.

Termux:Widget can do this too.

**Comment by twaik** [comment]
Termux:Widget is not integrated to navigation drawer.

**Comment by RalfWerner** [comment]
> Termux:Widget is not integrated to navigation drawer.

That is not completely right. The navigator is used by Widget to manage the open tasks.
I consider the widget solution to launch Termux applications for the smartest on a smart phone, in addition to the context/extension-conditional launch, via a File Manager like mc or pcmanfm.

My experience with _Widget_ is from Feb/Mar and can now be continued with the three plugins from @xeffyr. The start always takes place from the start screen of the mobile phone and is described in `~/shortcuts` _($s)_. Any start that does not finish creates another entry in the task list of the navigator. No_scripts like _.bashrc_ or _.profile_ sourced will be used (reduced set of **env**) but NEW SESSION. After finishing the task, if there are no more left in the tasklist or by "O"-tipping, you will be returned to the start screen. New is: The _limitation_ to 8 tasks does _not_ exist anymore and with _**exit 1** a confirm enter_ is requested.
This is fine as long as the task (eg. **feh**) _not_ is done in PID2+3. Here a PID1 / 2 change is necessary and can be described in _shortcut_.
_One-touch-termux_ creates the [PID1-4](https://gitter.im/termux/dev?at=5d4955bc45da450fecb56fca). These are by my _**vtpu**_ two Xserver and two **WM**, which can be used alternatively and takes place in _.bashrc_. If PID2 does not yet exist (for the first time) it will be started (`am start -n $y`) and you will be **in PID2+3**. This corresponds to a Linux boot with _startx/xinit_.

So that the change between running processes in PID1 _and_ PID2+3 is solved and can be used. The current is only possible with _my PID1_ on the Android Tasklist with 4 to 5 tabs (I also use to cancel at _**ssm**_). This is also the case with API. Apps (am) stay in the Tasklist regardless of the end. Different in the Navigator, where closed processes disappear

At Xorg we had SPARKLE in the navigator of PID1 and LEAVE in PID2+3, although this did not work. To build a navigator into PID2+3 I think _not a good idea_ and with several _Xservern_ (Xvnc, XSDL, Xorg/PC) at the same time also the change between these is to be described. My suggestion is to use _Icons_ on the PID2+3 screens. would be possible with _xlunch_.

I suspect in a typical cell phone session, launches will be done in two PIDs. As an example I suggest first: mc, htop and ls / ps (PID1) and xlunch, pcmanfm (PID2+3 for Xorg and VNC) plus dialogues with API. The widget shortcuts look like this (I've added to _vtpu_):
![grafik](https://user-images.githubusercontent.com/45426380/62703763-312c8d80-b9ea-11e9-89af-4f04285b2a17.png)
Shot1: **arch* start screen, shot2(upper): ls, env and ps, shot2(lower): midnight commander, shot3: pcmanfm+two xterm (one from _"one-touch-start"_), shot4: same in VNC-Viewer, Shot5: Tasklist in Navigator of all widget-tabs until here, Shot6: **arm** start screen

If the PID1 bug is fixed, I will describe the dialog API and _xlunch_ app control solutions here. My personal favorite (**WM**=none and **finger** only) is not here yet.

**Comment by nathaneltitane** [comment]
Not everyone enjoys cluttering their phone's display with widget and launcher shortcuts.... +1 on OP

**Comment by twaik** [comment]
Stale issue.
