### ISSUE TITLE
Unabl to open files with names starting with . "hidden files"  using Android Access Framework (TurboEdit)

### ISSUE THREAD

**Issue by cyberb** [termux/termux-app#1220]
Unable to open files starting with "." using Android Access Framework for example TurboEdit. I am not sure if it is an issue with TurboEdit or Termux.

**Comment by kevin-canadian** [comment]
User https://github.com/johnmellor commented on this in issue 79 (https://github.com/termux/termux-app/issues/79#issuecomment-213575265), and he even added some commits to a fork (although he doesn't seem to have created a pull request) which suggests that this behaviour is hard-coded into Termux.

I agree that this behaviour is unfortunate.  The apps using a storage should be the ones to determine whether or not they want to ignore hidden files, not the provider of the storage.  File explorers normally have an option for this (FX Explorer does, for example).  The storage should provide a full view of the files it contains.  Indeed, I can even create new hidden files in the Termux storage using an external application, which could result in clobbering of existing files by accident, since existing hidden files are currently not visible.

To ignore hidden files by default assumes too much about the intent of the user.  In my case, one of the main reasons I want to grant access to my Termux directory is to make it easier to manage my "home" directory, and most of the files of interest to me are hidden files.

Is there any reason not to update this behaviour?

**Comment by kevin-canadian** [comment]
FYI, I've created pull request #1856, which is identical to to the commit created by @johnmellor.

**Comment by xeffyr** [comment]
Will be fixed in v0.104 release.

**Comment by kevin-canadian** [comment]
Thanks for the quick fix @xeffyr!

**Comment by cyberb** [comment]
Do you plan to release to Google Play?
Current version is 101.
Thanks for the fix!

**Comment by xeffyr** [comment]
Google Play releases are end-of-life now. See more information: https://wiki.termux.com/wiki/Termux_Google_Play

Termux needs drastic changes in order to get released on Google Play again.
