### ISSUE TITLE
switch to another app and back ,pls don't reset scroll position

### ISSUE THREAD

**Issue by qidizi** [termux/termux-app#1248]
**Feature description**
example :
`curl --help` 
it will print out lines very more then one page  
when i scroll to y ,and want to open google for find out what is `smtp` ,  
when go back to termux ,it will focus last line and wait for input.  

now i must try to find where is `smtp`  again.

**Comment by AbdullahM0hamed** [comment]
A temporary solution to your problem would be:

curl --help | less



scrolling in less retains its position, even after switching between apps

**Comment by ticalc-travis** [comment]
One caveat is that if you use the -F option in less (as I have by default on some systems I SSH to), this still can cause a problem if the output is less than 2 screens: less will scroll to the bottom and terminate too when switching from an app back to Termux! I've also had a similar problem with the scrollback in tmux not holding its scroll position.

I'm guessing that what's happening is that switching from an app back to Termux causes it to change the terminal size (because the on-screen keyboard is not yet loaded for a very brief instant) and then change it again when the keyboard appears. Unfortunately, this behavior causes problems like this, and I've also had trouble with certain curses applications somehow getting confused and intermittently repainting incorrectly. It would be nice if Termux would be able to avoid unnecessary rapid terminal size changes on app switch simply due to the keyboard starting out hidden and then immediately being redisplayed again (which often merely results in the terminal going back to the same size it was in the first place when Termux was last in the foreground).

**Comment by amaramth** [comment]
The scroll is also reset when navigating between termux sessions. We cannot use `less` to keep the position in a repl; there needs to be a setting for whether to save the scroll position when switching.

**Comment by agnostic-apollo** [comment]
Closed by 5fc2b4cd4ae59a7cbfccea60c76019e96efb847c

**Comment by amaramth** [comment]
Thank you :) How is the next release coming along, btw? ;)

**Comment by agnostic-apollo** [comment]
You are welcome. :) Yeah, it's being worked on.
