### ISSUE TITLE
Dear author, may I add functions based on your code?

### ISSUE THREAD

**Issue by hanxinhao000** [termux/termux-app#1302]
I have made a version, what should I comment in the app?
To thank the original author

**Comment by xeffyr** [comment]
You may use Termux code as soon as your device is compliant with licenses.
https://github.com/termux/termux-app/blob/master/LICENSE.md

Services, i.e. package repositories, aren't allowed to be used by third-party projects (in general, you even won't be able as all packages are bound to Termux app package name).

**Comment by hanxinhao000** [comment]
hello

**Comment by hanxinhao000** [comment]
This is my apk, which is also based on your project. I am from China, so the apk language is only Chinese. Sorry, could you please check if it is ok?

**Comment by hanxinhao000** [comment]
https://drive.google.com/file/d/1rYyqmtGz2d57XUmShDRK38N5_hkjGIKX/view?usp=sharing

**Comment by xeffyr** [comment]
It is not ok:

* Application name (Termux) and package name (com.termux) should be different if you going to distribute your application.

* Usage of the official Termux apt repositories by third-party applications **is not allowed**. By the way, growing traffic from third-party things most likely will end in certain actions in order to disable wasting of our monthly bandwidth.

* Login motd should be changed too. Forks aren't supported in our community pages and bug tracker.

* If you are going to distribute the application, a source code must be freely available in order to be GPLv3 compliant.

**Comment by hanxinhao000** [comment]
Hello, I don't go back to the application release it, because China for making the speed limit is too severe, basic only 50-200 KB, installation of the most basic systems to half an hour, I actually like termux this application also thank the authors make you're giving us such a powerful applications, but if I want to join to this exciting project, what should I do

**Comment by hanxinhao000** [comment]
Translated by youdao

**Comment by hanxinhao000** [comment]
My English is poor

**Comment by hanxinhao000** [comment]
...

**Comment by hanxinhao000** [comment]
Don't release

**Comment by hanxinhao000** [comment]
Whatever the outcome, I respect your choice
