### ISSUE TITLE
package create fail & deb file lost & deb File format not recognized ?

### ISSUE THREAD

**Issue by CMingTseng** [termux/termux-app#1330]
Dear Sir

for some use so i need modify 

I modify PREFIX 

and re-build deb files

today i clone again & run-docker & build-all

I get

1.  

Building cryptopp...
ERROR: See /home/builder/.termux-build/_buildall-aarch64/cryptopp.err
builder@25c9da3ca231:~/termux-packages$ cat /home/builder/.termux-build/_buildall-aarch64/cryptopp.err

I check the error and fixed it  --- because  

Download of https://www.cryptopp.com/cryptopp820.zip failed (attempt 5/6)

Yes !!  the file  { https://www.cryptopp.com/cryptopp820.zip} lost !!!
[https://i.imgur.com/p3ejE31.png](url)
i replace it  by 

https://mirrors.aliyun.com/macports/distfiles/libcryptopp/cryptopp${TERMUX_PKG_VERSION//./}.zip

Building mime-support... ERROR: See /home/builder/.termux-build/_buildall-aarch64/ca-certificates.err
builder@25c9da3ca231:~/termux-packages$ cat /home/builder/.termux-build/_buildall-aarch64/ca-certificates.err

I check the error and fixed it  --- because   ca-certificates sha change !!

i replace new sha 

Building mime-support... ERROR: See /home/builder/.termux-build/_buildall-aarch64/mime-support.err
builder@25c9da3ca231:~/termux-packages$ cat /home/builder/.termux-build/_buildall-aarch64/mime-support.err

I check the error and fixed it  --- because  

Download of mime-support_3.63.tar.gz failed (attempt 5/6)

Yes !!  the file  { http://http.debian.net/debian/pool/main/m/mime-support/mime-support_3.63.tar.gz} lost !!!
[https://i.imgur.com/eDTbAkY.png](url)
[https://i.imgur.com/XDAcSYy.png](url)
i replace it  by 
http://sourcearchive.raspbian.org/main/m/mime-support/mime-support_$TERMUX_PKG_VERSION.tar.gz

2.  The Packages folder  include 652 sub-folder 
[https://i.imgur.com/oQZ8IkH.png](url)
but   when finish build deb files . i only get 540 deb files !!??

as termux-packaging  the  { generate-bootstraps.sh } show -- # Core utilities. bzip2 !!
[https://i.imgur.com/juYZTlt.png](url)
https://github.com/termux/termux-packaging/blob/master/scripts/generate-bootstraps.sh#L305

but can not find it !!?

3. as generate-bootstraps.sh show need { package.deb }

https://github.com/termux/termux-packaging/blob/master/scripts/generate-bootstraps.sh#L107

i can not found any package folder  &  i get File format not recognized 

https://github.com/termux/termux-app/issues/1329#issuecomment-547725475

THX

**Comment by xeffyr** [comment]
In all your messages you didn't mention that you are creating & uploading packages to APT repository. So I'm really sure that you just trying to bypass that step and this is a **source of all your failures with generating bootstrap archives**. If so, nothing will help you - create your own scripts which are suitable for you.

Suggesting to learn bash scripting a bit. Just to understand how script works and where it stores files.

> Yes !! the file { https://www.cryptopp.com/cryptopp820.zip} lost !!!

That's expected, Internet is not persistent - its continuously changing. We do not own sources for various packages and their authors have right to *change, move, delete* source files from their servers. We do not monitor such things and changing URLs if found necessary.

>     i only get 540 deb files !!??

`build-all.sh` is not best thing to use. It most likely will fail. Some packages will conflict with each other and it is not possible to rebuild all combinations of packages in order to find that.

Just don't use `build-all.sh`.

> but can not find it !!?
***

Btw, the `build-all.sh` script is not used in package building process. Also, posting instructions about generating bootstraps again (can't read wiki ?), last time:

1. Build necessary packages with `./build-package.sh`.
2. Create APT repository. *APT repository is a special file & directory structure expected by `apt` package manager. Typical utilities for creating APT repository are https://github.com/termux/termux-apt-repo and `aptly` (https://www.aptly.info/).* If you don't want to create APT repository & upload it to some hosting, stop at this step - you won't be able to proceed.
3. Clone `https://github.com/termux/termux-packaging` and cd to `termux-packaging/scripts`.
4. Execute script `./generate-bootstraps.sh --repository <your repository url> --prefix <prefix>`. Repository URL is an HTTP URL to repository web root, e.g. `https://termux.net`. If your packages are only for one architecture, pass additional argument like `--architectures aarch64`.

**Comment by xeffyr** [comment]
That info should be enough for you to start investigating your errors and revise the correctness of your way of building bootstrap archives.

Closing.
