### ISSUE TITLE
Termux session can't start after update

### ISSUE THREAD

**Issue by donmor** [termux/termux-app#1341]
**Problem description**
I upgraded Termux via Play Store and then when I open the app, it traces some messages, then the session closed on clicking ENTER. Each new session produces this problem.

P.S: Before this, I once changed my phone and found "adb backup"not working to the internal data of this app, so I packed the whole "/data/data/com.termux/files" in a tarball and expanded it to my new phone. It got to work at that time and nothing seemed weird. My old phone's CPU is Snapdragon 625 with Android M and the new one is 845 with O.

**Steps to reproduce**
1.(May related to this problem or not) Install an old version of Termux (before 0.73 because it was not deployed as a bundle and I made a backup apk of it) on a Snapdragon 625 Android M device and get write permission to "/sdcard" and type "tar cvpf /sdcard/termux.tar -C /data/data/com.termux/files .". Copy the tarball to a Snapdragon 845 Android O device, install Termux (same version) and run "tar -xvpf /sdcard/termux.tar -C /data/data/com.termux/files"(might be incorrect, but I managed to extract the "home" and "usr" directory to the internal dir and it worked fine at that time and I ran "pkg update" several times before having this problem)
2.Upgrade Termux to the latest version.

**Expected behavior**
A way for me to make this app work again or, at least, to backup the data in the app. 

**Additional information**
Here is the traced messages:
> NOT LINK EXECUTABLE "cat": library "libandroid-support.so" not found
Aborted
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash": library "libandroid-support.so" not found

I think it is possible that the busybox Termux packed in the new version no longer needs that library, and the library was eventually removed from the app. Maybe I have to "re-install" the "system" inside the app, but there's no chance for me to backup my data: I even cannot enter the shell! I know the home directory is accessible via SAF, but I also have some data stored in usr directory.

**Comment by donmor** [comment]
One more thing: I changed apt source to a Chinese server by Tuna

**Comment by xeffyr** [comment]
> One more thing: I changed apt source to a Chinese server on mirrors.tuna.tsinghua.edu.cn

That's the reason. Switch back to `termux.net`.
Application uses the URL in sources.list to determine whether to export LD_LIBRARY_PATH or not (it is needed only for legacy repositories used for Android 5 & 6).

Or start failsafe shell: instead of tapping "enter" on shell exit, open drawer (swipe right), then long tap on "new session" -> "failsafe". In failsafe shell put `export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib` to file `/data/data/com.termux/files/home/.bashrc`.

***

Few more notes:

* Do not copy rootfs between Termux installations on legacy Android (5 & 6) and Android 7 or higher. The `LD_LIBRARY_PATH` is used only on legacy Android versions.

* We are going to completely drop legacy Android support after 01.01.2020.
