### ISSUE TITLE
F-Droid version is showing incompatible

### ISSUE THREAD

**Issue by TGWGitHub** [termux/termux-app#1349]
**Problem description**
The version available on F-Droid is showing as incompatible on an Android v6.0 device, requiring Android v7.0+ while the version on Google Play Store is still compatible with Android v6.0, please see the screenshot below:

![Screenshot_2019-11-16-13-47-46-1](https://user-images.githubusercontent.com/37277112/68992903-4d0dbe00-087a-11ea-8442-250eb04f655e.png)

https://imgur.com/IFMTtun

**Comment by xeffyr** [comment]
Yes, F-Droid now shows only APKs for Android 7+ for some reason (seems picking versions only from branch "master").

Though, due to https://github.com/termux/termux-packages/issues/4467 (dropping legacy Android support completely) this issue doesn't make sense. F-Droid will not keep all outdated version on application's page forever.

Closing.
