### ISSUE TITLE
Incompatible versions

### ISSUE THREAD

**Issue by 2011** [termux/termux-app#1353]
Hi,

Have had this installed for quite some time (including several updates) via F-droid. The last three updates though (0.76, 0.77, and 0.82), show as incompatible with both of my devices (so still on 0.75). The both run a LineageOS version equivalent to Android 6.0.1. I couldn't find any documentation or requirements that would explain this? Does anyone know the reason why recent versions appear as incompatible?

Thank you in advance.

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-app/issues/1349. Versions with odd numbers should work on android 5 & 6 but for some reason that doesn't work in F-droid. 

Closing as support for android 5 and 6 will be dropped on the first of January 2020 anyways

**Comment by sudomain** [comment]
I ran into this issue after factory resetting an Android 5 device. The solution is to open Settings in F-Droid, open Repositories, and enable the "F-Droid Archive" repo. Apparently F-Droid keeps the three most recent builds in the "F-Droid" repo, all of which are now incompatible with Android 5/6 (since Termux 0.75)
