### ISSUE TITLE
Termux-share error

### ISSUE THREAD

**Issue by Gio1422** [termux/termux-app#1387]
Termux-share -a edit file doesn't work with QuickEdit. Editing the opened file results in the following error
![IMG_20191218_002548](https://user-images.githubusercontent.com/47062775/71031660-3d112480-212d-11ea-995f-27d289ff2e2b.jpg)

**Comment by xeffyr** [comment]
termux-share won't allow you to save a file.

**Comment by xeffyr** [comment]
There can be a confustion about `-a edit` action, but it is really just for viewing files in text editor.

**Comment by AbdullahM0hamed** [comment]
@Gio1422 As an alternative, you could add your own method to do this in your .bashrc.

This is what I managed to get working (requires inotify-tools which can be installed with pkg): 

```
share() 
{ 
    mkdir /sdcard/.termuxShare 2> /dev/null
    touch /sdcard/.termuxShare/"$(basename $@)"
    cat "$@" > /sdcard/.termuxShare/"$(basename $@)"
    am start -a android.intent.action.VIEW -d file:///sdcard/.termuxShare/"$(basename $@)" -t '*/*'
    inotifywait -e MODIFY /sdcard/.termuxShare/"$(basename $@)"
    cat /sdcard/.termuxShare/"$(basename $@)" > "$@"
    rm /sdcard/.termuxShare/"$(basename $@)" 
}

**Comment by xeffyr** [comment]
@Gio1422 QuickEdit supports SAF, so it can access Termux home dir directly. Though it requires user interaction because SAF-based access is interactive-only.

![Screenshot_20191218-013000_QuickEdit Pro](https://user-images.githubusercontent.com/25881154/71043090-3e931a80-2136-11ea-82f4-12e3778082eb.jpg)

![Screenshot_20191218-012952_Files](https://user-images.githubusercontent.com/25881154/71043097-43f06500-2136-11ea-97ed-16aae940e02b.jpg)

**Comment by Gio1422** [comment]
wow, thank you guys
