### ISSUE TITLE
arp: permission denied

### ISSUE THREAD

**Issue by kfiz** [termux/termux-app#1401]
**Problem description**
Calling`arp -a` results in `/proc/net/arp: Permission denied`

**Steps to reproduce**
Call `arp -a` from within termux

**Expected behavior**
In the previous repo this was possible. Since upgrading, I get this error.
I would expect to get the output of the command.

**Additional information**
```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.179-perf+ #1 SMP PREEMPT Sat Dec 14 20:49:05 CST 2019 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6013
```

**Comment by Grimler91** [comment]
Have you upgraded your android version? Permission denied comes from the OS, there's nothing we can change in termux to "fix" it. If you are rooted then you could try running the command as root

**Comment by xeffyr** [comment]
Android 10 deprecates the whole `/proc/net` interface and nothing can be done with that. Check this changelog entry: https://developer.android.com/about/versions/10/privacy/changes#proc-net-filesystem

Generally, that change is expected because kernel interfaces are not the official part of SDK and are not meant to be used by regular applications.
