### ISSUE TITLE
Question: Disable telnet?

### ISSUE THREAD

**Issue by joshcangit** [termux/termux-app#1431]
Termux has `telnet` enabled.
Should it be disabled? Why?
If so, then how to do it?
So then, what would replace it if it is disabled by default in the future?

**Comment by xeffyr** [comment]
> Should it be disabled? Why?

That's question for you - why `telnet` should be disabled ?
Insecure because unencrypted and therefore should be disabled ? Why not to disable everything unencrypted by such logic, e.g. all FTP & HTTP clients and servers (or at least unencrypted proto support) ?

**This will not happen.** If you don't want to use these utilities, just do not use them.

**Comment by tomty89** [comment]
Am I missing something here? Since when Termux has telnet "enabled"? I don't suppose "enabled" means "inetutils which consists of telnetd *can be* installed and run"?

**Comment by xeffyr** [comment]
Enabled here means available as part of installed package. If someone don't need it (and whole `inetutils` package), then just
```
pkg remove inetutils
```

**Comment by Neo-Oli** [comment]
The busybox package contains a telnetd service
https://github.com/termux/termux-packages/blob/master/packages/busybox/build.sh#L12
```
"telnetd" 'exec busybox telnetd -F'
"ftpd" 'exec busybox tcpsvd -vE 0.0.0.0 8021 ftpd $HOME'
```
Both the telnetd and the ftpd service are configured very insecurely by default. telnetd allows full access via telnet and ftpd allows full filesystem access. Both these services are (like all services) disabled by default, but can very easily be enabled with termux-services `sv up telnetd`. A case could be made to not ship these services at all, because for a user to use them seriously they would need to change the service file anyway.

telnetd could be used to run programs other than a shell, I've seen it used to control art installations at places like the CCC.
`exec busybox telnetd -F -l bastet` would allow other people to play tetris from your device.
Maybe telnetd can be configure to do something innocent by default, like displaying the date. 
"telnetd" 'exec busybox telnetd -F -l date'

I'm not sure how this version of ftpd can be used without giving full filesystem access. You can't restrict it to a single directory, which could be useful. I can't think of a scenario where it would be useful and safe. 

I'm not making the case about the lack of encryption (you may not care about that in some scenarios), but about the level of access these services have by default.

**Comment by tomty89** [comment]
Hmm sounds like the question if busybox should be kept minimal/local...
