### ISSUE TITLE
Ctrl+Shift+(+/-) already mapped on ChromeOS

### ISSUE THREAD

**Issue by qntmpkts** [termux/termux-app#145]
Background: ChromeOS now allows the installation of Android Apps as a beta feature released to certain chromebooks. Cf. https://www.chromium.org/chromium-os/chrome-os-systems-supporting-android-apps

Ctrl+Shift+(+/-) is already mapped to resolution adjustment on ChromeOS. In order to allow text resizing in Termux, this modifier should be changed to something that will not be interpreted by the host. According to the keymap (brought up with Ctrl+Alt+/ on any chromebook), the best solution would be to use Ctrl+Alt instead.

**Comment by filodej** [comment]
Hello,
I second this request. In my case the problem is with emacs undo command (Ctrl + underscore), which requires pressing Ctrl + Shift + minus simultaneously on my hardware keyboard, which leads to "zoom out" terminal command instead of "undo".
A possibility to customize the Ctrl+Shift to something different would be great.
Thanks.

**Comment by fornwall** [comment]
@filodej Would Ctrl+Alt work as a prefix for shortcuts (https://termux.com/hardware-keyboard.html) for you as well?

**Comment by filodej** [comment]
Absolutely. Ctrl+Alt woul work perfectly for me.
Thanks.

**Comment by fornwall** [comment]
The prefix for shortcuts has now been changed to `Ctrl+Alt`  in version `0.42` of the Termux app, which should be available as an update in a couple of hours

**Comment by filodej** [comment]
Hi,
the new shortcut works great for me.
Thank you very much for the swift update.
BR.
