### ISSUE TITLE
Sharing Files with script ! [Feature Request] 

### ISSUE THREAD

**Issue by gwpl** [termux/termux-app#150]
I'd love to be able to select file(s) in some android app (e.g. pictures in gallery, or recordings) , then select "share with" and select "termux" and one of scripts from the list configured to receive files via "sharing". I'd love to be able to make such script to receive "shared with it files" via arguments.

(I am not sure if it's feature request appropriate for temrux-app or termux-widget or maybe request for even new app. I just would like to be able to process files with my scripts easily via sharing UI flow, instead of writing files into directory and then running script. It would be wonderful if I could share multiple files at once!

**Comment by gwpl** [comment]
Mayve sth like $HOME/bin/termux-url-opener , but for files? (Now I am getting "save in directory" dialog for files)

**Comment by Ryan-B-W** [comment]
What you're looking for is basically a way of handling Android Intent events using scripts inside of Termux.  As of now there is no way of doing so that I'm aware of.  However, there is permissions limited access to the 'am' and 'pm' Android shell tools that can be used for sending new Intents but not for receiving Intents AFAIK.  If you want to be able to handle incoming Intents then you would need to update the app manifest file (AndroidManifest.xml) for Termux to add the right intent filters, as well as have some way for Termux to pass those Intents on to your script.

I don't see a way of doing what you're asking for as of now but such a feature _might_ be possible to implement.

**Comment by Neo-Oli** [comment]
There is `termux-file-editor`, which was added at the same time as `termux-url-opener`
From changelog:

> Termux can now receive files shared from other apps. Files are saved into ~/downloads/ and it’s possible to open this folder or editing a file directly when receiving it. Editing is done through a ~/bin/termux-file-editor program which will be called with the newly received file as only argument.

Is this what you're looking for?

**Comment by gwpl** [comment]
Yes and No.

Yes, for one file awesome -> Wow! `termux-file-editor` sounds awesome!
I got misleaded by "save file" dialog. (Maybe adding "?" in "save file" dialog , mentioning  after click that "termux-file-editor" can be called would be an option? Or I was just before "RTFM" :) )

No, it does not handle multiple files -> It serves only part of my needs. I would love to be able to send multiple files and let them be opened either via multiple arguments to program (those could be temporary streams), either via file with list of file locations, or any other way.

Thanks a lot for feedback Neo-Oli ! :D

**Comment by gwpl** [comment]
I confirm:
* solutions work for one file or url
* still lack of solution for sharing multiple files

my ux idea for multiple files:
* just replicate approach for one file - when dialog asks for filename before saving in ~/downloads , instead of asking for filename, ask for subdirectory name! And also offer "edit" button which will open all with `~/bin/termux-files-editor` (or other `bin/something` of choice)

**Comment by sanchomuzax** [comment]
I have a Python2 script, and I would like to send an URL to it with the Share function over Termux.

What is the prefered syntax of the `$HOME/bin/termux-url-opener` file?

I tried two methods, but haven't luck.

1st method: create a `termux-url-opener` script with the following line:
`python2 ~/myscript/myscript.py %1`
The script started, but didn't get the `%1` parameter.

2nd method: create a symlink to my script. It can't running, because the `python2` parameter is missing from it.

How is it possible to pass a URL parameter for a Python script with the Termux Share function?

**Comment by brunelli** [comment]
> The script started, but didn't get the `%1` parameter.

You expand variables with `$`, not `%`.

Or, the more elegant way:

> create a symlink to my script

You'll need a shebang on your script to specify an interpreter to run the program (in this case, `python2`. Add this to the beginning of your script so you can call it directly:

`#!/data/data/com.termux/files/usr/bin/python2`

(Or wherever location python2 is installed)

**Comment by sanchomuzax** [comment]
Thank you, solved. 👍

**Comment by mentalisttraceur** [comment]
To me, the ideal feature design looks like this:

Instead of an unconditional prompt, let the user fully control how sharing is handled. So, either:

1. Before creating the "save file in ~/downloads/" prompt, check if a specific executable exists, and if so, just call that *instead* of showing the prompt. We'll need a new name to keep backwards compatibility - perhaps "termux-share-receive-override`. Or:

2. Provide a checkbox inside Termux settings to disable/skip the prompt, and just go directly to `termux-files-editor`.

To handle things like shared clipboard copies, which don't have a file name, when bypassing the name prompt, I would either robustly create a file with a unique name with `mktemp ~/downloads/.termux-share-received-XXXXXX` (could even say it's the script's job to clean it up), or I would pipe the shared input to the receiving scrip's stdin.

**Comment by gwpl** [comment]
It was so long tome ago, that I can't remember, I am sorry 🙈

**Comment by hbendi** [comment]
@mentalisttraceur 

I am very interested in this.

## Intent

Get list of filenames shared from gallery app.


## Why

### Technical

Keep local database of summary for files linked to files of my choosing custom topics.

By minimum, the selection should be include visual files (photos, screenshots, camera recordings, screen recordings), anywhere on device, similarly to [ Files ] app.

This is similar to adding files to albums on Google Photos for images and videos, excluding the cloud and online part.


### Human

_I want to go tripping. I intend to record and write a lot. Uploading 10+ GB of data per day via mobile network is out of question.

I won't want to postpone writing notes about my observations, emotions or ideas – I tend to forget the details that make those 'wow'. Thus, I want them 'now' (complete noting for ongoing day before bedtime by latest)._


## Tested

### Termux app

-  [ termux-file-editor ] cmd works only for text files. I want to include images and videos by minimum, preferably text and audio files as well.

- [ termux-storage-get ] cmd expects me to supply filename, but I need reverse: to get filename.

- [ termux-cliboard-set ] cmd expects me to supply text to copy. If possible, I would share multiple files with Termux and get it copied to clipboard, similarly to [ Copy as Path ] option in Window 10 (pressing shift + right click on selection in file manager).


### ZArchiver Pro app

- Can quickly move files to temp folder and get list there, but moving files back to original folders would be a mess. Possible, but too much manual handling.

- Would work even on low storage.


### Files app

- Can move files to temp folder and get list there, but moving files back to original folders would be a mess. Possible, but too much manual handling.

- Fails with low storage. Files NOT moved, files NOT copied.


### Obsidian app

- Bootup is faulty. Loading cache takes forever. Takes forever to load (I have over 10k [ .md ] files). Waiting for 1+ minute for every sharing is NOT acceptable.


### OnePlus Gallery app

- Share single file with Termux #works

- Share multiple files with Termux #fails (Termux NOT appearing on list)


## Conclusion 

No other/external app can handle my needs atm. Termux is limited in GUI to select files user files intuitively.

**Comment by twaik** [comment]
Seems like it can be closed since original issue was solved.

**Comment by hbendi** [comment]
@twaik , could you point at solution (comment, post, command, script)? 

Problem statement clearly define fileS as plural:

1. Select files with other app (e.g. Gallery, file manager)
2. Share those files with Termux
3. Run Termux script on said files (or at least get a list of filenames with their absolute paths)
