### ISSUE TITLE
Termux and the relationship with users

### ISSUE THREAD

**Issue by robinpaulson** [termux/termux-app#1516]
I've been using Termux now for some years, it's a great addition to the Android environment.

I was disappointed to see no more updates for Termux some weeks ago, apparently only later versions of Android are now supported. So, I came to the Github issues page, to see what other users were saying, and what the devs had said to them. It appears there are several other users who are in the same situation as me.

I dug further, looking at the responses from the devs, and was unhappy to see all the issues on the topic had been closed immediately, without any discussion, some permanently locked. One of them even had the comment "Time to upgrade your devices or learn how to backport git changes.", which is deeply patronising, dismissive and shows a lack of care towards the people who use the software. Is this the image you wish to portray?

This isn't a request to make Termux compatible with Android/Replicant 6 (although that would be great), but for you to engage in meaningful conversations with your users. Taking a hostile, "we don't care what you think" approach isn't great. The issues page is here to discuss issues, and whether you like it or not, this is an issue, no matter how many times you tag ts as "invalid". It's not hard to have a conversation and to listen to other people.

Perhaps @x2k13, @millerebonds and @nathaneltitane might like to comment too on what they think of being dismissed out-of-hand?

Or will you close and lock this conversation immediately out of fear they might do just that?

Thanks for reading.

**Comment by Grimler91** [comment]
Hi, 

First things first, the discussion of dropping android 5 and 6 support started in February last year [1](https://wiki.termux.com/wiki/Dev:Development_Session_4), [2](https://groups.io/g/termux-dev/topic/termux_development_session/29681645), and was then more publicly announced in https://github.com/termux/termux-packages/issues/4467 and https://www.reddit.com/r/termux/comments/dnzdbs/end_of_android56_support_on_20200101/. Quite a lot of discussion followed, but goal with those posts was mostly to inform rather than to discuss though. 

> One of them even had the comment "Time to upgrade your devices or learn how to backport git changes.", which is deeply patronising, dismissive and shows a lack of care towards the people who use the software. Is this the image you wish to portray?

I am sorry to hear that you find this comment patronizing and dismissive. The point is that the current people maintaining termux does not have android 5 or 6 devices so we are not interested in maintaining packages for those versions. Termux is an open-source project solely maintained and developed by individuals volunteering for free so if no one volunteers to maintain those older android versions it is unlikely to happen. If you or someone else wants to host and maintain an android 5 repo then we could help switching the repositories over to the new url.

> The issues page is here to discuss issues, and whether you like it or not, this is an issue, no matter how many times you tag ts as "invalid". It's not hard to have a conversation and to listen to other people.

Well sure, but having the same conversation over and over again tends to drain my energy. I would rather spend that energy developing something. I think that is why some of the later issues have been closed and locked rather fast.

**Comment by xeffyr** [comment]
> I was disappointed to see no more updates for Termux some weeks ago, apparently only later versions of Android are now supported. 

> I dug further, looking at the responses from the devs, and was unhappy to see all the issues on the topic had been closed immediately, without any discussion, some permanently locked.

There was 2 (!) discussions about dropping support for Android 5.x - 6.x:

* https://github.com/termux/termux-packages/issues/2874 (soft deprecation)
* https://github.com/termux/termux-packages/issues/4467 (final)

And no one decided to take care of the legacy Android branch during that time.  As result, we officially dropped support for this OSes and no longer accepting related issues.

In last updates in android-5 branch, I have [intentionally added the message](https://github.com/termux/termux-packages/commit/97b5924662d8631d0cec39315a6b8f9606ae07e2) stating that packages are no longer maintained on legacy environment.  There were some issues about that which were closed and probably locked.

<details>
<summary>android-5 last 3000 commits stats (click to expand)</summary>
<pre>
1490	fredrik@fornwall.net
889	leonid.plyushch@gmail.com
248	henrik@grimler.se
93	tom.ty89@gmail.com
59	bored@goat.si
34	winsto003@hotmail.com
30	Henrik@Grimler.se
16	stephengroat@users.noreply.github.com
13	oli@glow.li
12	kevin@kevincotugno.com
11	bednarski.michal2@gmail.com
7	git@joakim.fea.st
6	alex@digriz.org.uk
6	henka20@hotmail.com
4	info@bitcoinprivacy.net
4	raghavsphadke@gmail.com
3	brandon.philips@coreos.com
3	cswl1337@gmail.com
3	j@ovvvo.co
3	kieran@coldron.com
3	repo@butta.fastem.com
3	sudosurootdev81@gmail.com
3	tom.ty89@outlook.com
2	17478432+TheBrokenRail@users.noreply.github.com
2	edward@edward-p.xyz
2	gdrbyko1@protonmail.com
2	github.snth@xoxy.net
2	hgrimler@kth.se
2	infectedx27@gmail.com
2	koro@kzxiv.net
2	laurent@spkdev.net
2	rafael@rafaelmartins.eng.br
2	stefan@sblbs.de
2	stephengroat@Stephens-MacBook-Pro.local
1	11911577+kenneth-Q@users.noreply.github.com
1	51031215+CarsonThompson@users.noreply.github.com
1	andy@onthewings.net
1	araczkowski@gmail.com
1	bigras.bruno@gmail.com
1	boundary.effect@gmail.com
1	connor24nolan@live.com
1	daniel.dob.obrien@gmail.com
1	davide@depau.eu
1	dextor@civ.zcu.cz
1	erlanger@please_use_issues
1	gary@garykim.dev
1	guillerobles1995@gmail.com
1	ImgBotHelp@gmail.com
1	infernix@gmail.com
1	its-pointless@users.noreply.github.com
1	Jason@zx2c4.com
1	jiri.tyr@gmail.com
1	karol@baraniecki.eu
1	karol@karcom.pl
1	kinke@users.noreply.github.com
1	landfillbaby@users.noreply.github.com
1	lkpandey950@gmail.com
1	lotheac@iki.fi
1	me@duncm.com
1	me@serl.it
1	mklein994@gmail.com
1	nonedisponibile@gmail.com
1	qbasic010@aim.com
1	ross@bluelightos.ddns.net
1	spaceboyross@yandex.com
1	surya@keyba.se
1	vbauer@yandex-team.ru
1	ysaxenax@gmail.com
1	zaomir@outlook.com
</pre>
</details>

So, there is a question: **Is there are people who want to maintain packages for old Android versions ?** Currently I see only requests like https://github.com/termux/termux-app/issues/1407 or discussions like this one.

> One of them even had the comment "Time to upgrade your devices or learn how to backport git changes."

It is possible to continue to have necessary software support for old devices on your own.  Why not to try it, especially if maintainers no longer want to deal with old Android versions ?

**Comment by xeffyr** [comment]
## For those who decides to maintain Android 5/6:

Ask yourself these questions:

* Are you ready to deal with incoming issues on your own ?
* Are you familiar with bash/python scripting and probably a bit of C/C++ ?
* Are you ready to keep versions up-to-date, fix bugs and maybe add new packages for old Termux installations ?
* Are you ready to maintain package hosting and be responsible for its safety & consistence ?

If you answer positive for all questions, then we may discuss more details on restoring support for legacy Android.  If not, further discussions on this topic will be pointless unfortunately.

**Comment by xeffyr** [comment]
> this is an issue, no matter how many times you tag ts as "invalid"

> I think that is why some of the later issues have been closed and locked rather fast.

About "invalid" tag: I use it under these conditions:

* Issue is not subject for further discussion.  (case for all Android 5/6 issues as their support is dropped and issue isn't going to be fixed)
* Issue about user errors such as invalid script syntax or command name typos. (we are not stackoverflow.com)
* Issues coming from outdated package dependencies. (all packages should be at current available version)
* Issues in third party scripts/programs. (we provide support for our packages only)
* Unreproducible issues or ones which happen due to unusual setup. (messing up with $PREFIX is not covered by our support; same goes for messed up ROMs)
* Requests for features which definitely won't be implemented. (quality vs features tradeoff,  conflict with existing features or just implementation impossibility)
* Issues about "slow package downloads". (we don't know what is happening on user devices/network + hosting won't be changed unless more serious issues will happen)

**Comment by nathaneltitane** [comment]
> Hi,
> 
> First things first, the discussion of dropping android 5 and 6 support started in February last year [1](https://wiki.termux.com/wiki/Dev:Development_Session_4), [2](https://groups.io/g/termux-dev/topic/termux_development_session/29681645), and was then more publicly announced in [termux/termux-packages#4467](https://github.com/termux/termux-packages/issues/4467) and https://www.reddit.com/r/termux/comments/dnzdbs/end_of_android56_support_on_20200101/. Quite a lot of discussion followed, but goal with those posts was mostly to inform rather than to discuss though.
> 
> > One of them even had the comment "Time to upgrade your devices or learn how to backport git changes.", which is deeply patronising, dismissive and shows a lack of care towards the people who use the software. Is this the image you wish to portray?
> 
> I am sorry to hear that you find this comment patronizing and dismissive. The point is that the current people maintaining termux does not have android 5 or 6 devices so we are not interested in maintaining packages for those versions. Termux is an open-source project solely maintained and developed by individuals volunteering for free so if no one volunteers to maintain those older android versions it is unlikely to happen. If you or someone else wants to host and maintain an android 5 repo then we could help switching the repositories over to the new url.
> 
> > The issues page is here to discuss issues, and whether you like it or not, this is an issue, no matter how many times you tag ts as "invalid". It's not hard to have a conversation and to listen to other people.
> 
> Well sure, but having the same conversation over and over again tends to drain my energy. I would rather spend that energy developing something. I think that is why some of the later issues have been closed and locked rather fast.

I must say that having been on my own endeavor with using Termux as the backend to my little project, I haven't had to come across using the issues too much.

I will say that the amount of discussions are plenty and the difficulty in finding information in them is often due to how lenghty they can be, which is by no means negative!

I understand both @Grimler91 and @xeffyr where maintaining code that is on its way out for good can be some sort of losing battle, especially when the project's heartbeat depends on the goodwill, time and conscious effort of the people who are fond of it and sadly not compensated (enough or at all) to do it.

I see no harm in asking a question and being pointed to the right direction. If that isn't clear, i'll just ask again in hopes to get a clearer answer or some help along the way.

Hope this helps @robinpaulson

**Comment by robinpaulson** [comment]
The entire point I was making was this:
You were dismissive and patronising to your users.

Everything else is irrelevant. I don't doubt that maintaining for Android 5 and 6 is difficult. In fact, I even made this statement, so you'd understand:

"This isn't a request to make Termux compatible with Android/Replicant 6, but for you to engage in meaningful conversations with your users."

I guessed you might straight away jump to technical answers and ignore the point I made, which was why I put it there and why I chose the title. It appears you didn't read it anyway, which only reinforces the point I made: a lack of care towards users.

**Comment by xeffyr** [comment]
@robinpaulson So what should be done in your opinion, do you have any suggestions ? Do you think we should keep open issues for things we no longer support ?

Or we should encourage people to submit generally offtopic or *irrelevant* issues like these:

* https://github.com/termux/termux-packages/issues/4384
* https://github.com/termux/termux-packages/issues/4409
* https://github.com/termux/termux-packages/issues/4439
* https://github.com/termux/termux-packages/issues/4507
* https://github.com/termux/termux-packages/issues/4755
* https://github.com/termux/termux-packages/issues/4943
* https://github.com/termux/termux-packages/issues/5024

There actually more such examples. Ultimately-weird issues were deleted shortly after their creation.

Please understand that we use Github issues mostly as bug tracker for things we support currently. Additionally we may handle requests for new features and packages.  Everything else is offtopic and  subject for close or even deletion.

**Comment by robinpaulson** [comment]
You're still missing the point and changing the topic of conversation. Please read what I wrote, carefully.

> So what should be done in your opinion, do you have any suggestions?

Be polite. Show care. Treat others as human beings.
Don't be dismissive, patronising, angry, passive-aggressive. Don't change the topic.
If a conversation has been had already, or a decision made, post a link to that discussion.

**Comment by RalfWerner** [comment]
@robinpaulson So far I have seen Leonid and his colleagues as friendly, helpful and very effective.
I can also understand if they try to _**end** "offtopic issues"_ in order to _remain effective!_

**Comment by debugrr** [comment]
robinpaulson

You are doing the list of things you are telling others to do.

Have you ever worked on a project like this before?

git issue pages are coding issues.

It is very frustrating when people use these issues to complain, and or
seek how-to advice.

I see the point you are trying to make.

There was discussion, it is over, and no longer valid with no volunteers,
is an invalid topic?

Did some make frustrated retorts? perhaps.

Have you never? (this is rhetorical, every human has, every human loses
patience)

If you want to help, then you direct others go the previous conversations.
And you be sweet and kind to every poster.

It takes a great deal of time and energy. I'm sure that while it was an
open discussion, there was much more back and forth. And calmer responses.

Issues are CODING Issues.
If you want discussion, that is what Reddit et al are for.

Every bit project has a "will not fix" section and old hardware/software is
always on that section.

**Comment by robinpaulson** [comment]
> You are doing the list of things you are telling others to do.

Good.

> Have you ever worked on a project like this before?

I know how to be kind to people, that's the only important thing.

> git issue pages are coding issues.

Why? That's an excuse to deflect any attention from bad behaviour.

> It is very frustrating when people use these issues to complain, and or seek how-to advice.

Yes, it is. That's no excuse to not be kind though.

> I see the point you are trying to make.

Good

> There was discussion, it is over, and no longer valid with no volunteers, is an invalid topic?

Yes, so tell them in a non-dismissive way, As I've said before. 

> Did some make frustrated retorts? perhaps. Have you never? (this is rhetorical, every human has, every human loses patience)

I get to speak on things, regardless of my past. Your point is an attempted deflection and a change of subject again.

> If you want to help, then you direct others go the previous conversations.

Why is this relevant? We're talking about whether or not the devs were polite in a particular situation. You're changing the subject again.

> And you be sweet and kind to every poster. It takes a great deal of time and energy. I'm sure that while it was an open discussion, there was much more back and forth. And calmer responses. 

Good, I'm glad to hear it.

> Issues are CODING Issues.

Is that information shown anywhere? The patronising behaviour was here, on Github, not Reddit. Why would I talk about it there? Also: are you not interested to hear of dismissive behaviour, regardless the channel?

> If you want discussion, that is what Reddit et al are for.

There is a "Discussion" tag on the Github issues page, which has been applied to this discussion. Also, I think you're making some of these points up ad-hoc.

> Every bit project has a "will not fix" section and old hardware/software is always on that section.

Yes it does, but that has nothing to do with being polite to your users. Again, you're changing the subject.

**Comment by Grimler91** [comment]
> Be polite. Show care. Treat others as human beings.
> Don't be dismissive, patronising, angry, passive-aggressive

Text messages on github or the internet in general is not a good way to communicate emotions, I am sorry if you feel that our messages and actions are dismissive, patronising, angry or passive-aggressive. 

I do not think the intent behind our comments and actions is to be those things, I think you might be interpreting our, sometimes short, comments as dismissive, patronising, angry or passive-aggressive when it's rather due to us trying to be time efficient.

**Comment by xeffyr** [comment]
>> Issues are CODING Issues.

>Is that information shown anywhere? 

Yes, it is.  We provide 2 issue templates to show which kind of issues we expect generally:

* https://raw.githubusercontent.com/termux/termux-packages/master/.github/ISSUE_TEMPLATE/bug_report.md
* https://raw.githubusercontent.com/termux/termux-packages/master/.github/ISSUE_TEMPLATE/package_request.md

Among with structure elements, they have suggestions about filling them and what *is not being accepted*, for example:
```
<!--
IMPORTANT: we are not accepting issues about Termux
installations running on Android 5.x-6.x.
-->
```
`not accepted` is `closed` and maybe `deleted`, with or without proper answer or reviewing.

**Comment by robinpaulson** [comment]
It's taken 11 comments to get to the point I raised in the first comment I wrote. Why? When you do get there, you still don't get it. Qualified apologies ("I'm sorry if ...") and a lack of desire to change how you communicate. Given you realise text is bad, try harder, don't make excuses.

"Time to upgrade your devices or learn how to backport git changes.", isn't great, neither is a terse message and an "invalid" tag. Paste the link to the discussion, paste the link to the decision, with why.

So much of the responses to what I've written are in bad faith, either changing the topic multiple times, or completely ignoring what I said. I get it, you don't see the problem. I give up.

**Comment by robinpaulson** [comment]
@xeffyr Great, but it doesn't say "And don't talk about these things, they are not permitted".

Ah, what am I doing, I already said "I give up".

**Comment by RalfWerner** [comment]
nice - then close this issue - @robinpaulson is author or answer with [yes](https://github.com/termux/termux-app/issues/1516#issuecomment-615185803) for new experiences :)

**Comment by snogglethorpe** [comment]
Even if they are often terse and to the point, the devs have been generally quite polite and kind in their interactions with others in these bug reports.
Don't mistake terseness for incivility.

**Comment by x2k13** [comment]
>Perhaps @x2k13, @millerebonds and @nathaneltitane might like to comment too on what they think of being dismissed out-of-hand?
>
Well, I understand that Android 5 and 6 devices are legacy/EOL devices and keeping the code updated/bugfixed takes additional manpower which can be better used on development of current and upcoming OS versions.

Furthermore I guess I missed the announcements beforehand, so being informed about that felt like no big deal.

The fact that this has been asked/discussed over and over again might have led the Dev to being a bit impatient to that topic.

I'm not much of a coder and don't have the knowledge nor the time to keep the old branches alive, so  I just moved on.

On the other hand, the Dev can get indignant pretty fast claiming bugs aren't bugs but the fault of [insert other app here], even when that's not the case. But my time is to precious to me to start a fight over that.

**Comment by millerebonds** [comment]
Hello.

I read a little bit, and I find there is some unrespectful behavior here.

My point of view is quite simple: I make advocacy for replicant, you do?
I work with replicant in their forum, try to help their developers.

Termux is very practical to replicant, but not compatible anymore. Since replicant is the only one fully free android distribution, you don't see any problem?

**Comment by millerebonds** [comment]
To complete what I'm saying:

for me free software is a community where many people work on many topics and specialities.

When I spoke about termux compatibility and problems with replicant, and didn't get an answer for this, I felt frustrated and angry, because of I mean working for replicant is a good thing, it's important to help people who develop it.

And after that, I can believe that people who work for termux don't want to help people who work for replicant.

Maybe it's false. But I can believe that, and feel it's unfair.

You work on nice code about termux, I try to help replicant… it is not a nice thing to view things more globally?
View things globally doesn't mean do what I want because I see things globally. It means discuss together about a strategy about free software, and try to find solutions.

To close topics even without give us the time to answer (I'm not instantly everytime behind my computer) is imho unrespectful.

**Comment by xeffyr** [comment]
> is some unrespectful behavior here

The only unrespectful behaviour here is only from those who request support for things we already deprecated.

Do you want to support Android 5/6 packages ? Perhaps not. And not only you. I did't received any answer regarding https://github.com/termux/termux-app/issues/1516#issuecomment-615185803 from anyone.  No one decided to take its ownership in https://github.com/termux/termux-packages/issues/2874 and https://github.com/termux/termux-packages/issues/4467. That makes me realise that there either no interest or people just expect that all work will be done by us.

Please understand that I (and probably other maintainers) won't make Termux their full-time job. We work on it as far as possible in our free time. As no one else *interested* to contribute, we will decide on our own what we will support or not.

> Since replicant is the only one fully free android distribution, you don't see any problem?

No, I don't see any problem here. Whether OS is free or non-free, that actually won't affect Termux support for reason specified above.

> To close topics even without give us the time to answer (I'm not instantly everytime behind my computer) is imho unrespectful.

We won't close them as soon as someone will write us that is ready to support Android 5/6 on his own.

For now, all discussions about Android 5/6 considered as offtopic as we **completely dropped their support** and not dealing with related issues.

**Comment by millerebonds** [comment]
> The only unrespectful behaviour here is only from those who request support for things we already deprecated.

Be unrespectful is for you like command you?  I don't want to command you.

> Do you want to support Android 5/6 packages ? Perhaps not. And not only you. I did't received any answer regarding [#1516 (comment)](https://github.com/termux/termux-app/issues/1516#issuecomment-615185803) from anyone. No one decided to take its ownership in [termux/termux-packages#2874](https://github.com/termux/termux-packages/issues/2874) and [termux/termux-packages#4467](https://github.com/termux/termux-packages/issues/4467). That makes me realise that there either no interest or people just expect that all work will be done by us.

You know how it sounds to me? It's like I ask you if you have shoemaking skills. I have shoemaking skills, why you don't have these skills?
I can't reply to these questions because of I'm not engineer. But I work to help free software as I can, making advocacy, sharing nice techniques I discovered, helping in forums, telling people to take part in forums instead of being consumers, giving money to nice projects, etc…
You understand what I mean, I feel it's unfair to say I'm not involved and don't want to help. I already help, but not right here for termux. I can give you some money for termux if you want, but if you want me to take part like you say you must consider computing is not my job and a day has 24h.

> No, I don't see any problem here. Whether OS is free or non-free, that actually won't affect Termux support for reason specified above.

ok. The problem with replicant, is that there is very few people in their team. They don't have time to contact you and help you.
And for me replicant is here ( https://www.gnu.org/distros/free-non-gnu-distros.html ), thus I see it like very important to support. For several ethical or political reasons.




> We won't close them as soon as someone will write us that is ready to support Android 5/6 on his own.
> 
> For now, all discussions about Android 5/6 considered as offtopic as we **completely dropped their support** and not dealing with related issues.

Ok, I understand.
(I don't like the yellow thumb to give some rating to comment - ok it's github's problem ,o)

**Comment by Grimler91** [comment]
> You know how it sounds to me? It's like I ask you if you have shoemaking skills. I have shoemaking skills, why you don't have these skills?

It is not really skills that are needed to contribute here on github, it is more a will to invest time, study the scripts and learn about building packages.

> I can't reply to these questions because of I'm not engineer. But I work to help free software as I can, making advocacy, sharing nice techniques I discovered, helping in forums, telling people to take part in forums instead of being consumers, giving money to nice projects, etc…

Those kind of contributions are also very much needed in the FOSS world, thanks for that!

> You understand what I mean, I feel it's unfair to say I'm not involved and don't want to help. I already help, but not right here for termux. I can give you some money for termux if you want, but if you want me to take part like you say you must consider computing is not my job and a day has 24h.

Yes, a day only has 24 h and all of us have other jobs. That, and the fact that none of us use android 5 or 6 anymore, is why we do not want to maintain the older android 5&6 app and packages as well as the master branches. (For the record, I am a chemical engineer so computing is only tangentially related to what I do for a living.)

> ok. The problem with replicant, is that there is very few people in their team. They don't have time to contact you and help you.

Sounds like the replicant team are in the same boat as us then. But I guess termux is not really a crucial part of replicant, it is just an app among many others, so there is not really any reason for them to contact or help us. 

> And for me replicant is here ( https://www.gnu.org/distros/free-non-gnu-distros.html ), thus I see it like very important to support. For several ethical or political reasons.

We very much welcome help from more people to maintain the android 5 app and packages, but since no one of us uses replicant or android 5/6 I do not think anyone is very motivated to spend time on it

**Comment by xeffyr** [comment]
> You understand what I mean, I feel it's unfair to say I'm not involved and don't want to help.

We do not forcing anyone to contribute. We understand that some people may not have opportunity/skills to do so.

But if no one decided to take care on `android-5` branch from the time when https://github.com/termux/termux-packages/issues/2874 was announced (>1 year ago), then perhaps people just not interested in that ? Why we should support it on our own then ?

**Comment by trygveaa** [comment]
> You know how it sounds to me? It's like I ask you if you have shoemaking skills. I have shoemaking skills, why you don't have these skills?

But no one is making shoes on their spare time which they are giving away for free to strangers (I would be surprised at least). However, this is the case with most open source projects. Since this is a project with few contributors, and the contributors are using their spare time, they don't have the time to do everything. That is why they are asking for others to work on this issue.

As far as I have understood, supporting Android 5&6 takes a large effort in addition to supporting the current releases of Android. Additionally, supporting new releases of Android also requires a large effort, and I don't think the maintainers have time for much more than that at the moment.

**Comment by millerebonds** [comment]
> > I can't reply to these questions because of I'm not engineer. But I work to help free software as I can, making advocacy, sharing nice techniques I discovered, helping in forums, telling people to take part in forums instead of being consumers, giving money to nice projects, etc…
> 
> Those kind of contributions are also very much needed in the FOSS world, thanks for that!

You can understand that such comments lead to anger and then unconstructive messages?
It's not irrelevant what I said. I said that I feel like in a injust situation because of I already help free software, but not exactly you.

To do some caricature, I can say: "you want me to stop to help archlinux, replicant, peertube, free software advocacy, help to people who have GNU/Linux system settings and software problems, and instead help you?"
That's why I spoke about a more global view and strategy about free software.




> It is not really skills that are needed to contribute here on github, it is more a will to invest time, study the scripts and learn about building packages.

And then I don't have the will to really help you?



> But I guess termux is not really a crucial part of replicant,

Ok, you guess.
Termux is the only terminal application I found which permits to install w3m cli browser. And then w3m is very useful for poor people with cheap sim cards to get data on the web with very low data consumption. It's one of my uses of termux, but there are others.

> I've been using Termux now for some years, it's a great addition to the Android environment.
> 
> I was disappointed to see no more updates for Termux some weeks ago, apparently only later versions of Android are now supported. So, I came to the Github issues page, to see what other users were saying, and what the devs had said to them. It appears there are several other users who are in the same situation as me.
> 
> I dug further, looking at the responses from the devs, and was unhappy to see all the issues on the topic had been closed immediately, without any discussion, some permanently locked. One of them even had the comment "Time to upgrade your devices or learn how to backport git changes.", which is deeply patronising, dismissive and shows a lack of care towards the people who use the software. Is this the image you wish to portray?

There is a choice to stop support for android 5/6, and it can't be disappointing for you to see nobody reacting when you ask if somebody wants to help to support android 5/6.
And maybe some people here think that termux is not an essential part of replicant.
That's what I understand now.

But what is said at the beginning of this topic is that there was very few discussions or explanations, and then my original topic was closed… a little brutally… we speak about this.





> But no one is making shoes on their spare time which they are giving away for free to strangers (I would be surprised at least).

I took time to make shoes I gave away for free to stangers. It's the truth. These one exactly ( https://millerebonds.piwigo.com/picture?/513/category/3-bricolages ).
And I take time to document diy shoe making with free licensing ( https://www.millerebonds.lautre.net/?file=bricolages/chaussures/baskets-en-cuir )

The other part of your answer is correct, what was said in the beginning of this topic is some problem with way of answering to people, relationship with users.

**Comment by RalfWerner** [comment]
@millerebonds This issue was _**closed**_ 2 days ago and with every additional contribution I will receive an email! I would be nice, if you would look for another forum for _the **relationship** topic._

**Comment by Grimler91** [comment]
@RalfWerner you can unsubscribe in the menu on the right hand side if you do not want to receive notifications

**Comment by debugrr** [comment]
And people can stop commenting on Closed issues.

Which I thought was protocol for such things, just like git issues are code
issues.

Not complaints, helpdesk, open ended discussions on resolved issues.

The beauty of open source is, if you don't like what is happening... Fork
it.

If you need changes someone isn't doing... do it.

All the devs on this project are doing this out of a want for the project,
and do so for themselves. They are nice enough to Share their work with
others.

This is my Favorite, and most useful app I've ever seen, and I would love
to keep using it on every device I own, but I also recognize the work that
goes into that, and I would not force that on anyone. People have lives,
and should live them.

**Comment by ChiefMikeK** [comment]
ʕ •́؈•̀ ₎  Maybe need to pin this issue?  
---
[Pinning an issue to your repository - GitHub Help](https://help.github.com/en/enterprise/2.20/user/github/managing-your-work-on-github/pinning-an-issue-to-your-repository)
