### ISSUE TITLE
atool package

### ISSUE THREAD

**Issue by angelog0** [termux/termux-app#1523]
I have _built_ Atool package and send its _binaries_ maybe you can transform it in a true Termux package

[termux-atool-0.39.0.tar.gz](https://github.com/termux/termux-app/files/4504371/termux-atool-0.39.0.tar.gz)

The tarball can be installed with `tar -xf termux-atool-0.39.0.tar.gz -C $PREFIX`

**Comment by Grimler91** [comment]
We generally do not add perl/python/ruby/similar packages (atool was requested before in https://github.com/termux/termux-packages/issues/198), and all packages must be created with a `build.sh` script that compiles & packages them from source. Due to this we can not add the script(s) in your tar archive
