### ISSUE TITLE
Termux builds on F-Droid - only Android 7+

### ISSUE THREAD

**Issue by ameer1234567890** [termux/termux-app#1577]
I noticed that Termux builds on F-Droid are only for Android 7+, whereas Play Store has Termux for lower versions of Android. I ask because I need to install Termux on a device with Android 5.

PS: This is also the case for termux-api

**Comment by Grimler91** [comment]
Older versions are still compatible with android 5, so if v0.79, v0.81 or v0.83 are still provided by fdroid you can install those. 

If that is not possible then you can also download the apps from https://archive.org/details/termux-repositories-legacy, but remember that all apps have to be signed with the same key so you can't mix installation sources.

It might be possible to configure the fdroid build bot to build a separate app from the android-5 branch, but since we dropped support for android 5 and 6 at the beginning of this year no one of us is looking into it. PRs are welcome.

**Comment by xeffyr** [comment]
> are still provided by fdroid you can install those.

F-Droid archive repo should be enabled for this.

**Comment by ameer1234567890** [comment]
I specifically need a recent build of termux-api (those including persistence in job-scheduler). Any hope?

**Comment by xeffyr** [comment]
Not officially. We are not building newer app versions for Android OS lower than 7.0. Newer Termux API will also require update for package `termux-api`.

Support for Android versions lower than 7.0 has been finished at 01.01.2020, meaning no updates anymore. Including new features, bug fixes, etc for both application and packages.

**Comment by ameer1234567890** [comment]
If I build it myself (termux and termux-api) with my own signatures, would it work?

**Comment by xeffyr** [comment]
Yes, it will work once `minSdkVersion` is set to `21` and both applications have same signature. And you will need an updated `termux-api` scripts from https://github.com/termux/termux-api-package.
