### ISSUE TITLE
Unable to immediately see downloaded files when phone is connected to another computer.

### ISSUE THREAD

**Issue by cusco-travel-services** [termux/termux-app#1613]
Hi Folks,

I installed Termux from the F-Droid shop a few days ago on my UMIDIGI Z2 Special Edition phone which I imported from China. It has Android 8.1.0 as the OS.

I installed wget which was required for the execution of script files to download files. I downloaded the files to a directory under the "com.termux" directory tree. I have performed this action twice now.

Within Termux, the files are located below the following directory structure.

home/storage/shared/Android/data/com.termux/files/Computers/.../TargetDirectory

The ".../TargetDirectory" is for brevity because there are more branches between the Computers directory and the Target directory.

Within Termux and the Android File Manager, I can see that the downloaded files have both Read and Write access permissions.

When I connect the phone to my Laptop (Devuan Linux) I can not immediately see the downloaded files in the Linux File Manager. I can see the Script file that I transferred to the phone in the Target directory.

With the Android File Manager, if I copy the immediate Parent Directory of the downloaded files to the "Internal shared storage/Download" directory, the downloaded files in the original Target directory become visible in the Linux File Manager.

What needs to be done so that files, downloaded to a Target directory under the "com.termux" directory tree, are immediately available in the Linux File Manager when the phone is connected to the Laptop?

Thanks!!, Michael.

**Comment by Grimler91** [comment]
Hi,

> When I connect the phone to my Laptop

Connect over usb I suppose?

> in the Linux File Manager

Which file manager are you using?

> I can see the Script file that I transferred to the phone in the Target directory.

So in termux and android's file manager you have many files in `home/storage/shared/Android/data/com.termux/files/Computers/.../TargetDirectory`, but when browsing the folder on linux you just have a single script?

How long is the `home/storage/shared/Android/data/com.termux/files/Computers/.../TargetDirectory` path?

You could try running `termux-media-scan` on the folder, but I do not think it will make a difference since you can already see the files in android's file manager

**Comment by xeffyr** [comment]
MTP implementation for Linux is buggy and it often stuck. Generally this happens when MTP's cached file system state doesn't match with the state of file system on your device. Termux can nothing to do with that.

If you want more reliable file transfer, consider `sshfs` or `adb`.

> What needs to be done so that files, downloaded to a Target directory under the "com.termux" directory tree, are immediately available in the Linux File Manager when the phone is connected to the Laptop?

Here are things which may help:
* Reconnect your device to laptop.
* Try to change USB mode to "only charging" and then back to "MTP".
* Reboot your phone.
* Laptop side: kill all `gvfs`-related processes, logout and login again.

> You could try running termux-media-scan on the folder

This may not help.
