### ISSUE TITLE
COLUMNS not being honoured

### ISSUE THREAD

**Issue by memeplex** [termux/termux-app#162]
It seems like SIGWINCH is correctly handled since COLUMNS has the right number of columns (61 in my case). Nevertheless every cmd seems to be assuming 80 (git help, man man, etc). I often run 'COLUMNS=60 man' in my desktop but it doesn't work using termux. Any idea?

**Comment by memeplex** [comment]
At least for man I was able to do this

`$ alias m="man -T ascii -O width=$COLUMNS"`

**Comment by fornwall** [comment]
@memeplex Thanks for reporting!

The issue was that the man implementation in Termux comes from [mandoc](http://mdocml.bsd.lv/), which does not adjust output width to that of the terminal.

As this is rather nice to have in Termux where smaller screens are common, I've added this by patching the package. If you run

    apt update && apt upgrade

you will receive the updated version `1.13.4-3` of the `man` package which should adjust to the terminal width - let me know otherwise!
