### ISSUE TITLE
Will termux support .net core ???

### ISSUE THREAD

**Issue by lephamduythong** [termux/termux-app#1625]
**Feature description**
I followed this instruction : https://gist.github.com/richlander/467813274cea8abc624553ee72b28213
I downloaded dotnet SDK using "curl -SL -o dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-linux-arm64.tar.gz"
I "mkdir dotnet" to create dotnet folder
I extracted tar.gz file to ~/dotnet/ folder using "tar -zxf dotnet.tar.gz -C ~/dotnet"
I run "./dotnet" but it showed:
    "bash: ./dotnet: No such file or directory"
Will dotnet SDK support this ??

**Comment by Grimler91** [comment]
It won't work unless dotnet is compiled specifically for android. 
`bash: ./dotnet: No such file or directory` happens because dotnet has been compiled against a libc that is incompatible with android's libc (bionic).

dotnet was requested in https://github.com/termux/termux-packages/issues/516. It will be available when someone manages to (cross-)compile it for termux
