### ISSUE TITLE
Immersive mode doesn't work with external Keyboard

### ISSUE THREAD

**Issue by sodoku** [termux/termux-app#165]
When I set termux to fullscreen, notification bar and navigations go away as soon as the software keyboard is hidden. When I connect an external keyboard though, I always see notification and navigation bar. Only thing that is changing in full screen mode is that both bars have the color of the termux background.

Phone: 
Nexus6, Nougat Beta

Keyboard:
Microsoft Wedge

**Comment by cgevans** [comment]
This is a significant issue for me on on a Pixel C with its hardware keyboard. Interestingly, however, removing the keyboard, ensuring the terminal is fullscreen without notification bar and navigation bar, and then reattaching the keyboard causes it to remain in that state so long as it is not disturbed.

It appears the problem is that, with the external keyboard attached, the terminal never enters a fullscreen state. If it is already in that state, the keyboard does not pull it out of the state.

**Comment by duckdodger** [comment]
Hello,
I just bought a bluetooth keyboard and I'm still experiencing this issue. Has there been any progress towards fixing it? I would really like to have that extra space from hiding the status bar and navigation bar on my small phone screen.

**Comment by xeffyr** [comment]
We no longer have immersive mode.

**Comment by msongz** [comment]
still have the same problem on pixel 4 xl under immersive mode
