### ISSUE TITLE
Can't switch dark mode in time

### ISSUE THREAD

**Issue by purofle** [termux/termux-app#1694]
When I enable dark mode, termux can’t even switch

**Comment by trygveaa** [comment]
You have to restart Termux for it to take effect. The reason is that `configChanges` in the manifest includes `uiMode`. I tried asking @jeansch if that was necessary in https://github.com/termux/termux-app/pull/1446#discussion_r386008165, but never got any response.

Afaik it is possible to support switching to dark mode while the app is running without removing `uiMode`, but it requires more code.
