### ISSUE TITLE
Termux not running not newest version

### ISSUE THREAD

**Issue by QkiZMR** [termux/termux-app#1697]
I'm trying to run newest version and getting error
![Screenshot_20200809-074949~2](https://user-images.githubusercontent.com/7574087/89726002-28fc9900-da16-11ea-92eb-e5a2b70f08d3.png)

`/data/data/com.termux/files/usr/bin/login:` has 700 mode and belongs to app_10191 which is Termux user. Failsafe session is working.

**Comment by Grimler91** [comment]
What version? How did you install it?

Clearly something is very wrong, so try reinstalling the app (after using a [fail-safe shell](https://wiki.termux.com/wiki/Recover_a_broken_environment) to save valuable files (if you have any)

**Comment by QkiZMR** [comment]
I have a problem with 0.98. Now I'm reverting to 0.95 from Titanium Backup. I have a lot of files so it takes some time. Unfortunately Android 9 doesn't allow downgrade. I needed to remove app with it's data and restore from backup.

**Comment by kevin-stuart** [comment]
I have the same problem after upgrading a few minutes ago. I do not have root and therefore cannot revert. I'm using the Google Play version on Android 10.

**Comment by xeffyr** [comment]
Can't reproduce the issue, Android 10 AArch64.

**Comment by xeffyr** [comment]
This is a variation of https://github.com/termux/termux-app/issues/1072, which already affects some users even though Termux is not compiled against target SDK 29.

**Comment by kevin-stuart** [comment]
The old version worked flawlessly. Is there a way to fix this or am I out of luck after the update?

**Comment by xeffyr** [comment]
Installation on Android 7, ARM also working. As here only 2 users reported, it seems not mass problem.

Could @QkiZMR or @kevin-stuart obtain output of `logcat` (from **failsafe shell**) and post it here? Note that it should be obtained after you opened one or more normal sessions.

**Comment by kevin-stuart** [comment]
I tried getting the output: [logcat.txt](https://github.com/termux/termux-app/files/5047041/logcat.txt)

As I said, it seems that Samsung devices are problematic, both on Android 9 and 10 this seems to be enforced already, but not on a Pixel device.

**Comment by xeffyr** [comment]
On your device `logcat` doesn't add the SELinux info (entries like `avc granted` or `avc denied`), ok.

Last few things to try:
1. Does file `/data/data/com.termux/files/usr/lib/libandroid-support.so` exist ? (you can check with ls in failsafe)
2. If exists, could you try to execute this in failsafe shell ?
   ```
   export PREFIX=/data/data/com.termux/files/usr
   export LD_LIBRARY_PATH=$PREFIX/lib
   export PATH=$PREFIX/bin
   bash
   ```

I can think only about 2 cases why this issue may happen: something have messed up SELinux contexts for Termux directories (which very unlikely if stock non-rooted ROM) and incorrectly extracted bootstrap archives...

**Comment by kevin-stuart** [comment]
The .so exists and the commands work, it is possible to run bash and other installed executable again. 

I cannot think of why the SELinux contexts should be messed up, I just upgraded Termux, and I just use a few applications inside without any wild changes to permissions. The bootstrap archives should have been extracted a long time ago and I cannot recall any problems or anomalies. Since this also happens on another Samsung device with an older OS, I don't know what to make of it.

So if the commands run fine, why does Termux not work when launching regularly? What is different?

**Comment by xeffyr** [comment]
> So if the commands run fine, why does Termux not work when launching regularly? What is different?

I have intentionally put 
```
export LD_LIBRARY_PATH=$PREFIX/lib
```
at https://github.com/termux/termux-app/issues/1697#issuecomment-671033047 because that's only the case why libandroid-support.so cannot be found if SELinux contexts are ok and file exists at expected location.

You are using *Termux Legacy Environment*, with packages compiled for Android 5. Or even worse - a mix of Android 5 and Android 7+ packages. We have completely dropped support of Android 5 stuff at 01.01.2020.

Termux v0.96 and higher removes the Android 5 specific things that needed only for legacy environment packages, I did that at https://github.com/termux/termux-app/commit/fc04a93990eae1ac8b78d216b853f753b93a7bcf. That's why it is no longer working and why this issue is not a mass problem. That's just your setup.

To fix this issue, copy all important files to `/sdcard` and completely erase application data, if you want to use up-to-date packages and application. Otherwise, stick with v0.95 and do not update anymore.

**Comment by kevin-stuart** [comment]
OK, cool, so I can fix this with a bit of work.

I'm a bit puzzled how I ended up with this on multiple devices, although they have now been used for years. Was there no way to update the Android 5 packages? I.e. was there a migration path from _Termux Legacy Environment_ to the new packages? I found this post https://github.com/termux/termux-app/issues/1393 and now looked into running termux-upgrade-repo but it does not exist and `pkg update` also does not seem to work. I guess I missed to update earlier and now am stuck doing a wipe?

**Comment by xeffyr** [comment]
> I.e. was there a migration path from Termux Legacy Environment to the new packages? I found this post #1393 and now looked into running termux-upgrade-repo but it does not exist and pkg update also does not seem to work. 

`termux-upgrade-repo` is the proper way of migration from Android 5 environment to Android 7+. If it does not exist and packages still require LD_LIBRARY_PATH to be set, you probably somehow have a mixed installation. There no other way then to clear application data.

You can look into file
```
/data/data/com.termux/files/usr/etc/apt/sources.list
```
If it uses https://termux.net/, then this is fully legacy installation. If there is something else, then this is a mix.

New packages use DT_RUNPATH section which hardcodes library search path into binary, so you should not need LD_LIBRARY_PATH. But it works only if executed binary and all its dependencies have DT_RUNPATH, so mixing package will lead to issues.

**Comment by xeffyr** [comment]
>  It seems that tools like ls and cp are missing in bash or in failsafe, it says to install busybox. This makes copying to /sdcard/ kind of hard...

In failsafe, `export PATH=/system/bin` (default). Do not use utilities from Termux.

**Comment by QkiZMR** [comment]
[termux.log](https://github.com/termux/termux-app/files/5047483/termux.log)
My logcat. I wonder if it because I set Fish as my default shell.

**Comment by QkiZMR** [comment]
`termux-upgrade-repo` helps me reinstall whole system. Problem gone.
