### ISSUE TITLE
Support non-primary user account

### ISSUE THREAD

**Issue by jekkel** [termux/termux-app#171]
The app would be very helpful in enterprise scenarios but on shared private/business devices users may be required to separate data by means of different user accounts (or even container solutions like Samsung Knox). Currently it is not possible to support those scenarios. 

The source code looks like this limitation stems from assumptions about absolute paths and such but on the other hand this is being handled in other places by environment variables used as prefix. So maybe this approach can be extended so secondary user accounts are usable, too.

**Comment by thespacious** [comment]
+1

**Comment by xeffyr** [comment]
> on the other hand this is being handled in other places by environment variables used as prefix

https://github.com/termux/termux-packages/issues/2902
But any kind of using implementation of "dynamic prefixing" will require huge amount of work, not saying about maintaining these patchsets.

Irrelevant for now.

**Comment by arno01** [comment]
Since https://github.com/termux/termux-packages/issues/2902 got closed, to those looking for a workaround, I found ``proot`` tool is the best. The good point is that ``proot`` does not require root access.

```
pkg install proot
mkdir $HOME/workhome
```

Add this alias to your ``$HOME/.bashrc`` file:

```
alias work="proot -b $HOME/workhome:$HOME bash -l"
```

And then add to your ``$HOME/workhome/.bashrc`` file the following content:

```
export PS1='work \$ '

# So that bash does not hang on exit from proot when gpg-agent forks (ppid=1)
trap 'gpgconf --kill gpg-agent' EXIT
```

Now, all I need to do is to type ``work`` whenever I want to switch to a different user.
