### ISSUE TITLE
Is it possible to make two copies of termux application?

### ISSUE THREAD

**Issue by gowwe** [termux/termux-app#1761]
Is it possible to make two copies of termux application?

**Feature description**

**Reference implementation**

Does another app/terminal emulator have this feature?
Provide links to more background information.

**Comment by kcubeterm** [comment]
Do you mean cloning, like u do things with whatsapp and Facebook. If so, then cloning is't possible in case of termux app.

Termux don't  support multiple user because of android. Android doesn't allow multiple user per app.

**Comment by xeffyr** [comment]
This is not possible. All binaries are bound to specific installation path:
```
/data/data/com.termux/files/usr
```
If you change APK package name, Termux will not launch except the failsafe shell.

**Comment by RadicalEd360** [comment]
Thank you

**Comment by gowwe** [comment]
I meant to change the name of the com.termux package to any name

في الاثنين، ٧ ديسمبر ٢٠٢٠ ٨:٢٠ م Radical Edward <notifications@github.com>
كتب:

**Comment by xeffyr** [comment]
>  meant to change the name of the com.termux package to any name

Not possible without recompiling all new packages with different prefix.

**Comment by gowwe** [comment]
When I change the package name, this problem appears

في الخميس، ٢٤ ديسمبر ٢٠٢٠ ٣:٠٣ م Leonid Pliushch <notifications@github.com>
كتب:

**Comment by xeffyr** [comment]
@gowwe First of all, I don't see any issue in your message. Perhaps it was truncated. For second, changing the package name is a complex task.

Here is a brief list of steps what would be needed to make Termux clone:
1. You need a custom repository. Get a clone of [termux-packages](https://github.com/termux/termux-packages), modify `TERMUX_APP_PACKAGE` in [scripts/properties.sh](https://github.com/termux/termux-packages/blob/89384aed06f60ec3fb258caaeba24bdf0d73abeb/scripts/properties.sh) and recompile packages. You may need to fix the initial sources list of `apt` to use your domain instead of provided by Termux.
2. You will need a some hosting where to publish repository, in LAN or somewhere else (like Bintray). This is also a prerequisite for building bootstrap archives.
3. Once repository is up, edit `REPO_BASE_URL` in [scripts/generate-bootstraps.sh](https://github.com/termux/termux-packages/blob/89384aed06f60ec3fb258caaeba24bdf0d73abeb/scripts/generate-bootstraps.sh) script and run it.
4. Publish generated zip files somewhere on hosting. You can use same as in step (2).
5. Get a clone of [termux-app](https://github.com/termux/termux-app), modify bootstrap archive URL and SHA-256 in [app/build.gradle](https://github.com/termux/termux-app/blob/cb13a5a5314f1093a6f828a930aecc448453657c/app/build.gradle).
6. Replace all occurrences of `com.termux` with your `package.name` and `com_termux` with `package_name`.
7. Build Termux app.

I know, accomplishing all can be difficult or even not possible for some people. But Termux is not app which can be cloned easily. That's all due to its design, many things are bound to specific file paths which will become invalid once app package name is changed. And considering the problem with repository traffic, we do not want to make Termux easily cloneable to ensure that only legit installations may retrieve and use packages from our repositories.

So, in order to clone Termux app you will need to maintain a full fork.

I'm locking that issue since I have provided enough information on Termux cloning topic.
