### ISSUE TITLE
Help Needed: Using termux on a parallel space

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-app#1775]
**Problem description**

Using termux in a parallel space causes following error:
exec("/data/data/com.termux/files/usr/bin/login"): Permissio  Denied
**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by xeffyr** [comment]
> Using termux on a parallel space

That's not possible. As I know, only VMOS meets requirements to run Termux but even there are issues.

From your error, I can assume that Parallel Space disabled executable permissions on files, however they are part of essentials for running CLIs.

Also note that Termux requires prefix, i.e.
```
/data/data/com.termux/files/usr
```
to be present and accessible. Since https://github.com/termux/termux-packages/commit/7ec3f401fb0ec9f10ea15de7e52229c1684eb235, you may not run `coreutils` or `apt` if prefix is no longer accessible.

***

Making Termux cloneable or installable on secondary user is a won'tfix.

**Comment by tathastu871** [comment]
> > Using termux on a parallel space
> 
> That's not possible. As I know, only VMOS meets requirements to run Termux but even there are issues.
> 
> From your error, I can assume that Parallel Space disabled executable permissions on files, however they are part of essentials for running CLIs.
> 
> Also note that Termux requires prefix, i.e.
> 
> ```
> /data/data/com.termux/files/usr
> ```
> 
> to be present and accessible. Since [termux/termux-packages@7ec3f40](https://github.com/termux/termux-packages/commit/7ec3f401fb0ec9f10ea15de7e52229c1684eb235), you may not run `coreutils` or `apt` if prefix is no longer accessible.
> 
> Making Termux cloneable or installable on secondary user is a won'tfix.
Apt not work in vmos

**Comment by tathastu871** [comment]
is there a way to downloaad offline packages so that they can  be importes into vmos

**Comment by xeffyr** [comment]
> is there a way to downloaad offline packages so that they can be importes into vmos

Bootstraps are offline, what else you need? Do you have problems with `apt`?

**Comment by tathastu871** [comment]
> > is there a way to downloaad offline packages so that they can be importes into vmos
> 
> Bootstraps are offline, what else you need? Do you have problems with `apt`?

apt shows repo under maintainence while apt update worked on termux directly but  not on v vmos

**Comment by xeffyr** [comment]
Then browse repo manually. http://dl.bintray.com/termux/termux-packages-24/

**Comment by tathastu871** [comment]
```
GPG error: https://dl.bintray.com/grimler/game-packages-24 games Release: Unknown error executing apt-key
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
W: GPG error: https://dl.bintray.com/grimler/science-packages-24 science Release: Unknown error executing apt-key
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
W: GPG error: https://dl.bintray.com/termux/termux-packages-24 stable Release: Unknown error executing apt-key
E: The repository 'https://termux.org/packages stable Release' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
```

**Comment by tathastu871** [comment]
When installing from offline package
```dpkg-deb: error: tar subprocess was killed by signal (Segmentation fault)```

**Comment by tathastu871** [comment]
While installing from offline deb
```
dpkg-deb: error: tar subprocess was killed by signal (Segmentation fault)
```

**Comment by xeffyr** [comment]
> dpkg-deb: error: tar subprocess was killed by signal (Segmentation fault)

Known issue of VMOS. It was fixed in unofficial VMOS repacks (pirated?), not sure about latest official versions.

But anyway, VMOS is offtopic here. We'll not make/provide solution for this.

***

And as I wrote
> Making Termux cloneable or installable on secondary user is a won'tfix.

We will not make Termux independent from prefix path. Why:
* Lots of work as need to review source code of all packages and properly hook path string variables where needed according to their lifetime. Would be problematic for Go & Rust packages with sideloaded build-time dependencies.
* We do not want to let third-parties download our packages by their Termux-unrelated apps and waste our bandwidth.
