### ISSUE TITLE
[Question] Why is SDK 24 needed?

### ISSUE THREAD

**Issue by MPeti1** [termux/termux-app#1785]
I just noticed that the development of Termux hasn't stopped, just the minsdkversion has been changed in build.gradle.

What is the reason of this change? The message of the [commit](https://github.com/termux/termux-app/commit/c76cec186af4df7b1020cd1471ea50dfcb25afba) in which it was changed does not explain it, and it isn't mentioned in the changes of the next version tag either

Sorry for not using a template, but I though using the bug report template would be rude, and the feature request is an inappropriate one

**Comment by AbdullahM0hamed** [comment]
Well, since we no longer support android 5/6, there is no point having a lower minSdkVersion

**Comment by odie0102** [comment]
Adakah termux yang SDK di bawah 24 ?

**Comment by xeffyr** [comment]
>  just noticed that the development of Termux hasn't stopped


Development of Termux app compatible with Android 5/6 has been stopped since 01.01.2020 - https://github.com/termux/termux-app/tree/android-5, https://github.com/termux/termux-packages/commits/android-5.

> What is the reason of this change? The message of the commit in which it was changed does not explain it,

This was switch to offline bootstrap packages. They do not work with Android 5 because Google Play for unknown reason tampers libtermux-bootstrap.so and it no longer works on such devices (results in crash).

At this point Termux was splitted into 2 branches, one Android 7+ compatible and Android 5/6.

Also we had to move to higher SDK version since Android 7 provides some benefits:
* Dynamic linker supporting DT_RUNPATH.
* Dynamic linker no longer restricts path length for shared library location. (was an issue with Python on Android 5)
* Less amount of patches due to more mature & functional Bionic libc.
* No need to seek for workarounds of ROM bugs.

> and it isn't mentioned in the changes of the next version tag either

As in https://github.com/termux/termux-app/releases/tag/v0.76:
```
* Include bootstrap zip as shared library
```

***

Please note that Termux will not support Android 5.x - 6.x officially anymore. We gave about 1 year between [announcing](https://github.com/termux/termux-packages/issues/2874) and [finally dropping](https://github.com/termux/termux-packages/issues/4467) legacy Android version. No one was interested to join @termux and take ownership on **android-5** branch of Termux app and packages.

Termux team is small and supporting 1000+ packages for both SDK levels (21 for Android 5 and 24 for 7+) wouldn't be easy task. Especially when none of maintainers use Android 6 devices and none has been granted package submission access to http://termux.net/.
