### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by timkofu** [termux/termux-app#1787]
I don’t know how possible this is, as most the code would need to be ported. But I’m putting it out there because many of us agree this would be fantastic to have on iOS.

**Comment by xeffyr** [comment]
Not possible, Termux utilizes Linux kernel features. IOS is not Linux-based.

**Comment by WMCB-Tech** [comment]
Also. iOS is Based on BSD. so no linux software will work on BSD

**Comment by timkofu** [comment]
> IOS is not Linux-based.
Ya, it’s [based on Darwin, which is based on BSD 4.4](https://en.m.wikipedia.org/wiki/IOS)

> you may use iSH
Actually [iSH](https://github.com/ish-app/ish) is what made me reckon it could be done.

**Comment by xeffyr** [comment]
> that would take huge amount of time recompiling packages to BSD and change the PREFIX also.

Compilation doesn't take huge time. There are different problems like:
* **Porting problems.** We know nothing about IOS design, its restrictions, etc.
  * What we should be aware of?
  * Does IOS allow execution of command line tools natively? Will that require jailbreak?
  * Does IOS libc provides an API compatible with GNU libc or at least Bionic libc like on Android?
  * Or we'll have to write own x86 or other CPU arch emulator like iSH does?
* **Distribution problems.**
  * How we should distribute packages? Cydia - against AppStore policy and requires jailbreak. Inside application bundle - we don't know anything about format properties, its restrictions and in general could we run CLIs from it or not.
  * Hosting (Internet traffic issues) if using Cydia. For now Termux relies on *free of charge* services. Total traffic usage is around 45 - 60 terabytes which is very close to limit (60 TB, with mirrors - about 80). Increasing of usage by 30% may put us into trouble with total denial-of-service.
* **Finally - who will maintain the IOS-related stuff?**

Adding support for the new platform is something that unlikely to happen. Maybe at certain point some people, who have good knowledge about IOS, will join @termux and take the responsibility on porting application and packages.

***

> Actually iSH is what made me reckon it could be done.

iSH is x86 CPU emulator. It is completely different from Termux which is a [terminal emulator](https://en.wikipedia.org/wiki/Terminal_emulator). Do not compare these 2 things, they are a lot different from design & purpose.

**Comment by timkofu** [comment]
> iSH is x86 CPU emulator. It is completely different from Termux which is a terminal emulator. Do not compare these 2 things, they are a lot different from design & purpose.

The end result is a Linux terminal on an iOS(iSH) or Android(Termux) device, where one can install and run Linux command line software. Termux is Debian based and uses `apt`, while iSH is Alpine based and uses `apk` (here is an [iSH install and use demo video](https://www.youtube.com/watch?v=53ddhk6ki2E)). So for my use, the _purpose_ is the same, with Termux having a much larger package inventory, what with being apt based.

> Maybe at certain point some people, who have good knowledge about IOS, will join @termux and take the responsibility on porting application and packages

Yes.

**Comment by xeffyr** [comment]
> Termux is Debian based and uses apt

Termux is not Debian-based. That's a common misunderstanding due to presence of `apt` package manager. Termux environment is completely standalone distribution of packages ported to Android OS. It is too far from Debian by design.

More info regarding Termux vs Linux distributions: https://wiki.termux.com/wiki/Differences_from_Linux

> So for my use, the purpose is the same

Termux primary use-case is to be a terminal emulator for Android OS. Just like PowerShell for Windows or Xterm on Linux distributions, but since Android lacks many tools, Termux provides their own.

iSH is an utility to run a Linux distribution. I don't think it has similar capabilities of interacting with operating system like Termux, maybe on jailbroken devices it has more. But since it is emulator, use of certain things (e.g. PulseAudio) may not be possible.

> with Termux having a much larger package inventory, what with being apt based.

Alpine Linux provides more than 10000 packages. Termux has a bit more than just 1000 (10 times less!), so I don't know where you found much larger package inventory...

You can't install and use the original Debian packages in Termux. Why? - answer in https://wiki.termux.com/wiki/Differences_from_Linux (libc ABI).

Package manager is just a convenient way of installing/updating/removing sets of software packages and by definition its different implementation can't provide more or less packages. Also we may switch from `apt` to own packaging method to solve [Android 10+ issues](https://github.com/termux/termux-packages/wiki/Termux-and-Android-10), so do not rely on package manager implementation.

**Comment by timkofu** [comment]
> iSH is an utility to run a Linux distribution. I don't think it has similar capabilities of interacting with operating system like Termux.

No it doesn’t (see response to “certain things may not be possible below”).

> maybe on jailbroken devices it has more

Which is not an option at all. SSH-ing into a real Linux machine and working from there would be more prudent.

> But since it is emulator, use of certain things (e.g. PulseAudio) may not be possible.

Yes, but basic things work, like Python and some networking utilities(it’s all I’ve tried so far), so not too bad. But it’s still young and [actively developed](https://github.com/ish-app/ish/graphs/code-frequency), so we’ll see.

> You can't install and use the original Debian packages in Termux.

Yes. Each OS has a different Application Binary Interface. I figured y’all recompile the Debian system and packages for Android (like the way there’s a Debian for ppc and x86*).

> Alpine Linux provides more than 10000 packages. Termux has a bit more than just 1000

“Working” packages(but we addressed that above). And now using [this list](https://github.com/ish-app/ish/issues/718) linked by the iSH devs, there’s quite a bit more “available” packages yes.

Alright iSH it is.
