### ISSUE TITLE
Can't remote login via ssh connect to my CentOS server (installed on vm ) from termux

### ISSUE THREAD

**Issue by Parthaaaaa** [termux/termux-app#1800]
**Problem description**
Hello Everyone,I am a new user.I can't remote login via ssh to my CentOS server which is installed on vmware.

**Error messages showing the following information:**

Connection to partha@myServeripAdderress exited: Connection failed: Connection time out

**Steps to reproduce**
I have used the port 2244.So,my command on Termux was:

ssh -p 2244 partha@myServeripAdderress 

**Expected behavior**
I can access that server from other pc.But can't access from Termux.

Thanks in advance

**Additional information**

* Termux application version:0.101
* Android OS version:Android 9
* Device model:Xiaomi Redmi Note 5
* CentOs version: 8

**Comment by Grimler91** [comment]
Hi, your command looks correct so most reasonable problem is that there is a problem with your internet connection (or that you specified wrong ip address..). Maybe you have a firewall blocking your connection from the phone.

**Comment by Parthaaaaa** [comment]
@Grimler91 Thanks.But I have double checked that ip address.How to check if any "firewall blocking" my connection from phone ?

**Comment by Grimler91** [comment]
@Parthaaaaa Try from a wifi, or with mobile internet, or with a vpn

**Comment by xeffyr** [comment]
I can't confirm connection issues with `ssh`.
![Screenshot_20201023-220001_Termux](https://user-images.githubusercontent.com/25881154/97043508-448a3100-157b-11eb-814e-6b92e1faff72.png)

Things to check:
* On server: fail2ban setup & firewall, to ensure that connection is allowed from IP of your Android device. Connection timeout usually points on dropped packets.
* On device: check your network connection, e.g. try Wi-Fi instead of mobile network. Ensure that you don't use proxies or VPNs. Also check the correctness of entered IP address in Termux.

You may try `netcat` to connect to SSH port. If you can reach the server, SSH version should be shown:
![Screenshot_20201023-221321_Termux](https://user-images.githubusercontent.com/25881154/97044680-1ad20980-157d-11eb-97d8-de79672dcf45.png)
