### ISSUE TITLE
[Question] What does it mean F-Droid only

### ISSUE THREAD

**Issue by angelog0** [termux/termux-app#1832]
I see you added **F-Droid only** to the 0.102 and 0.103 releases on GitHub page.

What does it mean? Who does not uses F-Droid, will see Termux upgraded?

**Comment by AbdullahM0hamed** [comment]
It means that the updates can only be acquired from F-Droid. The play store will not receive updates for the foreseeable future, due to play store now requiring app updates to target API 29 (Android 10) as per:
> New apps and app updates (except Wear OS) must target Android 10 (API level 29) or higher. 

Source: https://developer.android.com/distribute/best-practices/develop/target-sdk

which termux does not function on due to the new restrictions, which you can read about here: https://github.com/termux/termux-app/issues/1072

**Comment by angelog0** [comment]
I installed Termux package from **apkpure** which, I think, uses G.Play package. Does this mean I cannot upgrade Termux any more? Can I migrate/upgrade in some manner? Which?

Shouldn't you remove the suggestion to install Termux from G.Play? I think I saw that on Termux wiki..

**Comment by WMCB-Tech** [comment]
> Can I migrate/upgrade in some manner?

Yes, by creating an Termux Archive to transfer installations between Google play to f-droid
https://wiki.termux.com/wiki/Backing_up_Termux

> Shouldn't you remove the suggestion to install Termux from G.Play? I think I saw that on Termux wiki..

See: [#1072](https://github.com/termux/termux-app/issues/1072)

**Comment by xloem** [comment]
Just a note that, depending on the time schedule for implementation, it would be helpful to organise a way for curious visitors to move #1072 (which is hundreds of technical comments long) to a wiki page that summarises the options that were considered and which one was eventually chosen.
