### ISSUE TITLE
make help page offline available

### ISSUE THREAD

**Issue by treakiandroid** [termux/termux-app#184]
hi,

i tryed to read the help because i can't remember all key combination's as i was on the go out of network coverage and found out that it didnt work. 

So could you please include the help pages into the app instead of invisibly linking to pages in the www.

thanks

**Comment by xeffyr** [comment]
Since `termux-tools v0.95` man page `termux` is provided. Run `pkg upgrade` to ensure that latest version of `termux-tools` is installed.

Offline help will be supplied only as standard man page. Embedding help pages in HTML format inside the application will not happen. [Termux Wiki](https://wiki.termux.com/wiki/Main_Page) remains to be the main source of up-to-date information about Termux.
