### ISSUE TITLE
Can I install termux twice on the same phone

### ISSUE THREAD

**Issue by gowwe** [termux/termux-app#1876]
Can I install termux twice on the same phone

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by kcubeterm** [comment]
Asking same question again. https://github.com/termux/termux-app/issues/1761

**Comment by gowwe** [comment]
Sorry😔

في الثلاثاء، ٥ يناير ٢٠٢١ ٨:١٠ م Krishna Kanhaiya <notifications@github.com>
كتب:

**Comment by gowwe** [comment]
I want another termux version that contains the proot package, and through
Proot I can run any distribution on it

في الثلاثاء، ٥ يناير ٢٠٢١ ٨:١٠ م Krishna Kanhaiya <notifications@github.com>
كتب:

**Comment by gowwe** [comment]
I want another termux version that contains the proot package, and through
Proot I can run any distribution on it

في الثلاثاء، ٥ يناير ٢٠٢١ ٨:١٣ م black Tiger <bt644318@gmail.com> كتب:

**Comment by gowwe** [comment]
??

في الثلاثاء، ٥ يناير ٢٠٢١ ٩:٣٤ م black Tiger <bt644318@gmail.com> كتب:

**Comment by xeffyr** [comment]
@gowwe You're not reading answer given in https://github.com/termux/termux-app/issues/1761#issuecomment-752077124 and keep asking same question again and again. Suggesting to read my post in #1761 in order to understand how to clone Termux app. *We will not make a special copy of application for you*.
