### ISSUE TITLE
add arm64 to dpkg arch

### ISSUE THREAD

**Issue by johnss** [termux/termux-app#1890]
**Problem description**

as dpkg --add-architecture is not working, i recommend add arm64 to ../usr/var/lib/dpkg/arch currently i edit the file mannually using vim to allow installing arm64 .deb packages, i succesfully installed some debian and ubuntu packages using termux-chroot (just proot without installing proot-distro)
**Steps to reproduce**

dpkg --add-architecture arm64
is not working

dpkg -i path/to/deb/packages.deb
return package architecture (aarch64) does not match system (arm64)
**Expected behavior**

should be installed succesfully if dependency are met
**Additional information**
debian and ubuntu usually using arm64 instead of aarch64 while major linux distro that use aarch64 instead arm AFAIK is alpine linux and arch linux,
this will allow many packages installed without installing debootstrap, proot-distro, or any similar packages as debian or ubuntu has larger community than alpine or arch linux
* Termux application version: 
* Android OS version:
* Device model:

**Comment by xeffyr** [comment]
**arm64 == aarch64**

If you are trying to install a package from foreign source (say from Debian or Ubuntu), it will not work. Termux can run only own packages.

**Comment by xeffyr** [comment]
https://wiki.termux.com/wiki/Differences_from_Linux for more information on what Termux actually is.

**Comment by johnss** [comment]
i know arm64 and aarch64 is the same, but why use aarch64 instead of arm64, debian and ubuntu use arm64 arm64 should be win in popularity

**Comment by xeffyr** [comment]
> but why use aarch64 instead of arm64

Because Android specifies ARM 64 as AArch64.

> debian and ubuntu use arm64

Termux is neither Debian nor any other Debian-based distribution. A fact that Termux uses apt as package manager means literally nothing. It would be definitely changed some day.

> arm64 is more popular and termux should use

Termux should not. It has own roadmap and again, it isn't Debian.

We'll not fulfill your request. Debian packages aren't supported by design: https://wiki.termux.com/wiki/Differences_from_Linux. Also changing architecture name from "aarch64" to "arm64" would cause a lot more headache than you can think.
