### ISSUE TITLE
Crashes on Xiaomi Redmi 9 devices

### ISSUE THREAD

**Issue by LaroTayoGaming** [termux/termux-app#1908]
**Problem description**
The new update for Termux literally crashes the entire app. Can you fix this?

**Steps to reproduce**
1. Install and open the app. Then crashes

**Expected behavior**
Literally I want to open it but it didn't.

**Additional information**

* Termux application version: 0.105 [F-Droid]
* Android OS version: 10
* Device model: Xiaomi Redmi 9 (MIUI 12.0.2)

**Comment by kcubeterm** [comment]
#1896

**Comment by vkuehn** [comment]
you closed both of them !?

**Comment by MFAHAC** [comment]
I have the same problem for termux 114 it's not installed on my device Redmi 9 android 10
Please someone help me

**Comment by agnostic-apollo** [comment]
@MFAHAC Open a new issue and post the crash report that normally should have generated when termux crashed and you started it again. If it did not, then use [`logcat`](https://developer.android.com/studio/command-line/logcat) to find the exception. This issue wouldn't be related to yours since it was already fixed long ago.

>it's not installed on my device Redmi 9 android 10

Assuming that's a typo.
