### ISSUE TITLE
BUG? Cannot read /storage: permission denied - Android 11

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-app#1926]
**Problem description**

Previously, using 'termux-setup-storage' to enable storage permissions and accessing /storage for reading or listing was permitted.
I use that method to provide access to my external microSD card and link it to whaterver Termux/CHROOT location i desire.
 Now that I have upgraded my device to Android 11,  after enabling storage permissions (by script or manually, an error results after attempting to read /storage:

example error output:

ˋˋˋ$ ls /storage
ls: cannot open directory '/storage': Permission denied
$ˋˋˋ

**Steps to reproduce**

open up a fresh/clean instance of termux
run ˋtermux-setup-storageˋ manually or programatically
allow permissions
attempt reading /storage directory contents manually or programatically (i.e.: ˋls storageˋ
error

**Expected behavior**

If storage permissions are allowed for tha app to access and manipulate storage, no error hould be triggered when attempting to access previously unauthorized or restricted storage directories (as was the behavior prior to Android 11 in my case)

**Additional information**

* Termux application version: latest
* Android OS version: Android 11
* Device model: Samsung Galaxy Tab S7+ SM-T970

![Screenshot_20210209-165725_Settings](https://user-images.githubusercontent.com/5674757/107433846-ebc5b080-6af7-11eb-940c-e5941aabcd7a.png)

**Comment by xeffyr** [comment]
This is not a bug. System directories are being locked down as really shouldn't be viewable by regular apps. *Least privilege principle, which is being enforced on modern Android.*

**Comment by xeffyr** [comment]
Use `ls /sdcard` or `ls /storage/emulated/0`, i.e. direct path to readable directory.

If /sdcard somehow became unreadable (permission denial), then revoke and grant again storage permission.

**Comment by nathaneltitane** [comment]
how does one detect uids of multiple sdcard-like devices or other forms of external storage then?

**Comment by xeffyr** [comment]
External sdcard mount path can be detected as path component of `~/storage/external-1` symlink target. However there no ways for USB storage. Either downgrade to older Android or use root.

Future Termux versions, with updated SDK level to 30+, support of external storage will be dropped as it literally useless even with write access to application private directory (files placed in it cannot be moved elsewhere or even accessed with file manager).

**Comment by nathaneltitane** [comment]
thanks for clarification

**Comment by RalfWerner** [comment]
> Termux versions, with updated SDK level to 30+, _**support of external storage will be dropped**_

@xeffyr Have you completed your `MANAGE_EXTERNAL_STOREAGE` test?
I can currently _only_ check Android 11 (_**30+**_) on emulators and I can _confirm_ the missing termux access from _**29+**_ - also _with_ your last commit, but _**not**_ the missing _fileApp_ access (SAF), including the _most internal_ [termux](https://github.com/RalfWerner/integrated-process/issues/2#issuecomment-773480281) data!

In practice (_support will be dropped_) this means: all relevant project data must be copied with the fileApp to a location under path: **t** (`ln -s ~ /../../ t`) and since this data is disposed of with termux beforehand be saved with the _fileApp_ extern.

Everything (relevant) is then stored at least twice on the device. Most of my real devices are equipped with 16Gb (of which a maximum of 5Gb free) and _"sufficient"_ external storage in which media/downloads (project data ~20Gb) are already managed.

**Comment by xeffyr** [comment]
> Have you completed your MANAGE_EXTERNAL_STOREAGE test?

If you read my messages on Gitter about it, then you will know that yes and it works. You need to grant a special permission to get it working: Settings -> Applications -> Special access -> Access all files permission.

You can store files in Termux directories and in /storage/emulated/0. On external storage, you can continue to use app private directory as writable location but you will not be able to move files anywhere else (Android/data/com.termux can be accessed only by Termux or ADB).

**Comment by xeffyr** [comment]
@nathaneltitane Perhaps a way to get UUIDs is still present. Access to `/proc/mounts` is unrestricted, so you can list mountpoints under /storage and other directories.

**Comment by agnostic-apollo** [comment]
The files created in external storage by users for termux-only usage like `/storage/emulated/0/` directory would also be deleted if termux is uninstalled when targeting sdk 29(android 10) like even the termux tar backup. We need to add the [hasFragileUserData](https://developer.android.com/reference/android/R.attr#hasFragileUserData) flag to the `AndroidManifest.xml` to show the user a prompt of whether he wants to delete termux data on uninstall, I don't currently see it. A guide on how to add the flag is [here](https://medium.com/@cafonsomota/android-persist-your-app-data-after-uninstall-894f6ea22686). Note that the data will still be removed if its uninstalled from playstore instead of settings app regardless of the flag value, since playstore uninstalls in the background without any prompts, at least that what the link says, maybe play store app update has fixed that now.

**Comment by xeffyr** [comment]
@agnostic-apollo Is this same when MANAGE_EXTERNAL_STORAGE is in effect?

**Comment by xeffyr** [comment]
Can't reproduce behaviour (all app-specific files deleted when uninstalling app) with manifest flags as in https://github.com/termux/termux-app/issues/1926#issuecomment-778087353

**Comment by agnostic-apollo** [comment]
So I was a mistaken, that flag shouldn't affect any files under `/storage/emulated/0/` except app private directories in `/storage/emulated/0/Android/{data,media,obb}/`. The documentation for `hasFragileUserData` should mention this.  And it engages regardless of `MANAGE_EXTERNAL_STORAGE` or scoped storage or target sdk on android `>=10`, don't see any checks in [`PackageParser`](https://cs.android.com/android/platform/superproject/+/android-10.0.0_r30:frameworks/base/core/java/android/content/pm/PackageParser.java;l=3720), [`ApplicationInfo.hasFragileUserData()`](https://cs.android.com/android/platform/superproject/+/android-10.0.0_r30:frameworks/base/core/java/android/content/pm/ApplicationInfo.java;l=1845) or while creating the [`UninstallAlertDialogFragment`](https://cs.android.com/android/platform/superproject/+/android-10.0.0_r30:frameworks/base/packages/PackageInstaller/src/com/android/packageinstaller/handheld/UninstallAlertDialogFragment.java;l=167).

>As I know, scoped storage works only if application doesn't has permission for all files access.

True, although possibly other android 11 restrictions like not being able to access private directories of other apps `Android/data/` seems to engage on android 11 regardless of scoped storage status as mentioned [here](https://medium.com/androiddevelopers/android-11-storage-faq-78cefea52b7c) but can be [bypassed](https://www.androidpolice.com/2021/01/29/x-plore-is-one-of-the-first-file-managers-to-bypass-scoped-storages-drastic-limitations-on-android-11/?amp) on target sdk 10 for now. 

>Regardless of target SDK, Storage Access Framework on Android 11 cannot be used to gain access to Android/data and Android/obb directories.

We haven't [opted out of scoped storage](https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage) either, since `requestLegacyExternalStorage` is not set to `true` in the `AndroidManifest.xml` in the `android-10` branch, which would only last till ~nov this year, if we manage to target sdk 30 for playstore releases, and `adb` commands can "probably" be used to opt out for now without the flag anyways as mentioned [here](https://www.xda-developers.com/android-q-storage-access-framework-scoped-storage/).

```
adb shell cmd appops set com.termux android:legacy_storage allow && \
adb shell am force-stop com.termux
```

Anyways, with the `hasFragileUserData` flag set, if you ask the dialog to preserve the data, then the internal app private directory `/data/data/` and external app private directories `Android/{data,media,obb}/` would be retained. There is an xda article on this as well [here](https://www.xda-developers.com/android-10-manifest-flag-developers-retain-app-data-before-uninstalling/). This may or may not be something we want, but could be useful if users want to write to `Android/data`, sppecially when targeting sdk 30 and could be useful for switching from playstore to F-Droid or custom builds too, specially for devs, so I guess leave the flag enabled. Are you sure all private data is getting deleted as well for you?

The flag would have been added because since app devs are being pushed to write data to their own private app data directories on external storage instead of random directories, so android provided a way for data to be preserved on uninstall. 

##### Internal details

If you ask the dialog to preserve the data, then [`DELETE_KEEP_DATA`](https://cs.android.com/android/platform/superproject/+/android-11.0.0_r3:frameworks/base/core/java/android/content/pm/PackageManager.java;l=1597) is passed to [`PackageInstallerService.uninstall()`](https://cs.android.com/android/platform/superproject/+/android-11.0.0_r3:frameworks/base/packages/PackageInstaller/src/com/android/packageinstaller/UninstallUninstalling.java;l=101). Ultimately, this reaches [`removePackageDataLIF()`](https://cs.android.com/android/platform/superproject/+/android-11.0.0_r3:out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/xref/srcjars.xref/frameworks/base/services/core/java/com/android/server/pm/PackageManagerService.java;l=18817) which calls the native [`destroyAppData()`](https://cs.android.com/android/platform/superproject/+/master:frameworks/native/cmds/installd/InstalldNativeService.cpp;l=716) to do the actual deletion, which is only deleting app user specific paths.

Apologies for the misinformation.

**Comment by nathaneltitane** [comment]
everything you've all just mentioned is very nice but, does it change anything to what @xeffyr gave to me as the final answer?

also, one must also consider the use case where no adb console can be accessed, as the Android device is used as the main PC (I.e.: my use case)

**Comment by RalfWerner** [comment]
@nathaneltitane No as long as you use the Termux artifact with targetSDK=28 :)

**Comment by nathaneltitane** [comment]
> @nathaneltitane No as long as you use the Termux artifact with targetSDK=28 :)

I don't delve into versioning of termux - I simply use the version available on PlayStore like most people would.

Guess I'll rewrite the detection script to find the mounts under /storage using /proc/mounts like @xeffyr  suggested.

I just hope that it'll stay accessible throughout

Thanks

**Comment by RalfWerner** [comment]
last _play store_ version is _v101_ the current ones (since Nov.2020) are published in _F-Droid_ and are currently at _v107_ in "Notificatons" above, annoying messages can be suppressed.
> If you read my [messages](https://gitter.im/termux/dev?at=600c05602cb18a437c37ec86)

Yes read @xeffyr! you have _pushed_ i asked _checked_ if so where (emulator) and with which artifact (branch android-10)?

**Comment by nathaneltitane** [comment]
So here are the two storage units of intterest:

 ˋˋˋcat /proc/self/mountinfo | tail -n 2
4473 4469 0:113 / /storage/3211-BCAD rw,nosuid,nodev,noexec,noatime master:57 - fuse /dev/fuse rw,lazytime,user_id=0,group_id=0,allow_other
6587 4362 8:65 / /mnt/media_rw/27E0-7084 rw,nosuid,nodev,noexec,noatime master:60 - sdfat /dev/block/vold/public:8,65 rw,fs=exfat,gid=1077,fmask=0007,dmask=0007,allow_utime=0020,codepage=cp437,iocharset=iso8859-1,utf8,namecase=0,adj_req,symlink=0,bps=512,errors=remount-roˋˋˋ

As mentioned above, i was able to trace back the SDCard 3211-BCAD to /sdcard and or /mnt/sdcard
The external SSD (27E0-7084) seems to mount but the location access rights are restricted... there is no way to access the mount although external file managers are able to read and write to it?
How can it be that termux cannot handle such storage when other applications do?

**Comment by xeffyr** [comment]
@nathaneltitane Storage properties are clarified in https://wiki.termux.com/wiki/Internal_and_external_storage. You can have full access only to internal and shared storage.

Only applications using *Storage Access Framework* APIs are able to write to external storage. Termux command line tools, like bash or coreutils, are not using Android APIs and in general not part of Android OS runtime. They are executed by Linux kernel and are subject for restrictions implied by [DAC](https://en.wikipedia.org/wiki/Discretionary_access_control) (chmod/chown) and [MAC](https://en.wikipedia.org/wiki/Mandatory_access_control) (SELinux).
