### ISSUE TITLE
On Huawei P20 Pro, TCP long connection cannot last, whether it is php or telnet

### ISSUE THREAD

**Issue by Hanmo123** [termux/termux-app#1934]
**On Huawei P20 Pro, TCP long connection cannot last, whether it is php or telnet**

**Comment by Hanmo123** [comment]
The same to mate30,also HUAWEI

**Comment by Hanmo123** [comment]
and another model: HUAWEI 畅想9 PLUS 6+128

**Comment by xeffyr** [comment]
Your issue provides no information about the actual problem and description doesn't look consistent anyway.

I'll assume that issue is due to powersaving, Huawei is known about its "revolutionary innovations in app restrictions" to make their devices last longer.

Try to enable wakelock and disable any restrictions for background processes if possible. Maybe https://dontkillmyapp.com/huawei will help.
