### ISSUE TITLE
External sdcard permission denied 

### ISSUE THREAD

**Issue by AireagoirSteam** [termux/termux-app#1943]
**Problem description**
Termux reports permission denied with copying files from the external sdcard and termux setup storage does not a link to the external storage.

However before running termux setup storage for the first time the I could write to the external sdcard and storage permissions are enabled.

I've reinstalled termux a few times now without success still getting permsion denied.

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:0.106
* Android OS version: P (9)
* Device model: Samsung s8

**Comment by xeffyr** [comment]
You can't write to external sdcard. Only shared storage and app private directories.

https://wiki.termux.com/wiki/Internal_and_external_storage

**Comment by AireagoirSteam** [comment]
@xeffyr I used to be able to to write to external storage though. And now I can't.

**Comment by xeffyr** [comment]
@AireagoirSteam As this is **unsupported** case due to Android OS restrictions, writing to external sdcard or mounted usb disks, issue won't be re-opened.

Termux supports only writing to shared storage and limited access to external storage:
* Global read-only access.
* Read-write access is restricted to Termux private directory in `.../Android/data/com.termux`.

**Comment by annihat** [comment]
@AireagoirSteam, `cp` is one of many links to `coreutils` which is less than 1M in size, it simply isn't big enough to go through this rigmarole: [https://developer.android.com/training/permissions/requesting](https://developer.android.com/training/permissions/requesting)  

...which seems to be different for pretty much every version of Android: [https://stackoverflow.com/questions/40068984/universal-way-to-write-to-external-sd-card-on-android](https://stackoverflow.com/questions/40068984/universal-way-to-write-to-external-sd-card-on-android) 

I suspect, though I have no way of testing, that if `Termux` in the installation script in the `.apk` file joined the groups `media_rw` & `sdcard_rw` some of these problems would go away. 

One of the core mantras of Unix & all it's successors seems to be "KISS" (Keep It Simple, Stupid) & Android violates this every step of the way. Unix has, since the beginning in 1970, had a pretty bomb-proof system of access permissions, Google had absolutely zero need to reinvent it (nor did Oracle who wrote Java which is what has been reinvented to create Android)
