### ISSUE TITLE
access denied ~/storage/shared/Android/data after updated to android 11

### ISSUE THREAD

**Issue by KrullBorg** [termux/termux-app#1952]
after i updated my phone to android 11 i cannot access ~/storage/shared/Android/data anymore; other apps can do it (es "cx file explorer")

thanks in advance

**Comment by xeffyr** [comment]
Revoke permission and grant again.

**Comment by KrullBorg** [comment]
i already did it before opening the issue; because just after the update to android 11 i could not access to ~/storage at all

in settings->apps->termux->permissions->allowed->storage->all files

and i re-run termux-setup-storage

maybe i need to uninstall/reinstall termux?

**Comment by RalfWerner** [comment]
give more information about your _device_ and termux _version_

**Comment by KrullBorg** [comment]
my device is a samsung m31 (device model sm-m315f) android version 11; termux 0.101 from google play store

so i cannot access anymore ~/storage/shared/Android/data from termux?

**Comment by agnostic-apollo** [comment]
You should be able to access `~/storage/shared` but not `~/storage/shared/Android/data` (except `com.termux` directory). Check [here](https://www.reddit.com/r/termux/comments/ln75tr/how_to_transfer_files_between_android_filesystem/gnzndn5?utm_medium=android_app&utm_source=share&context=3).

**Comment by RalfWerner** [comment]
_Right! I can only check emulators. There access is only _**there**_ possible. Newer _termux_ (106+) available in F-Droid!

**Comment by KrullBorg** [comment]
> You should be able to access `~/storage/shared` but not `~/storage/shared/Android/data` (except `com.termux` directory). 

but other apps can do it; so is it a choice of termux? ("cx file explorer" on my device seems have the same permissions type)

**Comment by xeffyr** [comment]
> but other apps can do it

None of apps can access ../Android/data directory on my Android 11 device. Android documentation also states about the restrictions for accessing this directory.

Some apps may use workaround shown in https://www.androidpolice.com/2021/01/29/x-plore-is-one-of-the-first-file-managers-to-bypass-scoped-storages-drastic-limitations-on-android-11/, but Termux can't do that because is locked down to Android 9 SDK (api level 28) because Android 10 breaks the application (issue #1072).

**Comment by agnostic-apollo** [comment]
Other apps can do it if they request access to `Android/data` using a SAF prompt and only if they target sdk `29` and below. Some info [here](https://www.reddit.com/r/Android/comments/j3zgmm/managing_files_in_the_androiddata_folder_on/). Once other apps start targeting sdk 30 in ~nov 2021 to be able to release  update on playstore, it will break for them too, like it has for [MiXplorer](https://www.apkmirror.com/apk/pishrodevs/mixplorer-hootanparsa/mixplorer-hootanparsa-6-47-2-release/).

Access might still be there on some phones on android 11 if the manufacturer has allowed it, but AOSP does not allow it and likely neither do devices close to it like Pixel. Android emulator/avd does not allow it either, even with `ADB`. Running `ls /storage/emulated/0/Android/data` results in permission denied errors, even running `mkdir /storage/emulated/0/Android/data/com.termux` will fail as well. To create `Android/data/com.termux`, run `termux-setup-storage`, which will create it using [Android APIs](https://github.com/termux/termux-app/blob/v0.108/app/src/main/java/com/termux/app/TermuxInstaller.java#L231) instead of shell. After creating it, you should be able to access it even with shell.

**Comment by xeffyr** [comment]
> Android emulator/avd does not allow it either, even with ADB.

On Pixel 5 it can be accessed with ADB, except some special directories like a one with offline YouTube content.

**Comment by agnostic-apollo** [comment]
>On Pixel 5 Android/data can be browsed with ADB. 

Hail the fragmentation. Yeah, read some people were able to access it with ADB, surprising pixel allows it. If access is there with ADB, then [Termux-ADB](https://github.com/MasterDevX/Termux-ADB), Tasker `ADB Wifi` action or similar apps that have ADB Wireless functionality could be used to bypass restrictions.

> offline YouTube content

lolz

**Comment by RalfWerner** [comment]
> Termux can't do that because is locked down to Android 9 SDK (api level 28)

@KrullBorg Your only chance to solve it now is: _build_ your own [29+](https://gitter.im/termux/dev?at=60277759a7fc4b573bcffaca) version of [termux](https://github.com/termux/termux-app) - but you have ti solve other differences.

**Comment by KrullBorg** [comment]
ok now everything is clear to me, thanks to all

**Comment by agnostic-apollo** [comment]
welcome

**Comment by superbonaci** [comment]
X-plore is dope.

**Comment by SDRausty** [comment]
Android 11 (with storage permission denied):

Both commands work:
`mkdir /storage/emulated/0/Android/data/com.termux`
`mkdir /storage/emulated/0/Android/media/com.termux`

The `Android/data` directory is accessable with this shortcut app: https://play.google.com/store/apps/details?id=com.marc.files (What's the source?)

The `Android/media` directory is accessable.

**Comment by SDRausty** [comment]
[u/DutchOfBurdock](https://www.reddit.com/user/DutchOfBurdock/) just shared:
> Try issuing an intent; `pkg install termux-am` and something along the lines of

> `am start -a android.intent.action.OPEN_DOCUMENT -d /storage/emulated/0 -t '*/*'`
