### ISSUE TITLE
repository down

### ISSUE THREAD

**Issue by cyberb** [termux/termux-app#1980]
```
Reading package lists... Done
E: The repository 'https://main.termux-mirror.ml stable Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
```

**Comment by WMCB-Tech** [comment]
The `main.termux-mirror.ml` is down, change the repo with `termux-change-repo` utility

**Comment by sudo-do** [comment]
all of the choices in Main Repository is down

**Comment by sudo-do** [comment]
all of the choices are down @WMCB-Tech

**Comment by WMCB-Tech** [comment]
See https://github.com/termux/termux-packages/issues/6726

**Comment by sudo-do** [comment]
lol, took a while to understand. since this issue is top of search results i'll explain **for people who came here from google search**


After typing `termux-change-repo`, select all options with the space key
![IMG_20210529_133332](https://user-images.githubusercontent.com/63397699/120067159-d6629b00-c082-11eb-996d-313f45305319.jpg)
press enter

select grimler.se repo  with the space key
![IMG_20210529_133636](https://user-images.githubusercontent.com/63397699/120067181-ebd7c500-c082-11eb-9359-6f0f956f7c51.jpg)
press enter

Done!
