### ISSUE TITLE
USB-C Yubikey device disables on-screen keyboard

### ISSUE THREAD

**Issue by cmosetick** [termux/termux-app#1995]
Hello and thank you for this excellent project.

I am a part-time security researcher and tester.
I have recently been doing some research on Android and found Termux to be helpful.
However, I have been road blocked by a USB issue with my testing device.
Please note that the Android device is NOT heavily customized.
So I am looking for other people that can reproduce and confirm the issue I describe below.
If several people are not able to reproduce this issue, then I am happy to consider it invalid.

**Problem description**
Inserting a Yubikey USB device into USB-C port on Android handset disables on-screen keyboard within Termux Application.
Device Tested: [Yubikey 5Ci](https://www.yubico.com/ch/product/yubikey-5ci)

NOTE - I do not see this issue with other applications while a Yubikey USB device is plugged into the same handset.
(i.e. the on-screen keyboard works normal and as expected in all other applications I have tested.)

NOTE: Inserting a regular USB-C mass storage device does not make the keyboard disappear!
Device Tested: A regular SanDisk USB-C flash disk formatted with a couple partitions. 

**Steps to reproduce**
- Plug in a Yubikey device into USB-C port of Android Handset.
- You will immediately see the regular on-screen keyboard within Termux App disappear.
- Tapping on the screen does not make on-screen keyboard re-appear.
- I have not found a way to make on-screen keyboard re-appear.

**Expected behavior**
- Android on-screen keyboard does not disappear.
OR
- There is a way to make on-screen keyboard come back and be usable even with Yubikey plugged into device.

**Additional information**

* Termux application version: `0.108` installed via F-Droid. (same bug experienced with previous Play Store version)
* Android OS version: `10`
* Linux Kernel version: `4.14.141-20190226`
* Device model: Samsung Galaxy

Please note that the Yubikey USB device works perfectly fine with @Yubico `yubioath-android` App on the same device.
(installed via [Play Store](https://play.google.com/store/apps/details?id=com.yubico.yubioath))

CC:
- https://github.com/Yubico/yubioath-android
- https://github.com/Yubico/yubico-java-client

**Comment by Grimler91** [comment]
Thanks for the detailed report. 

The yubikey [identifies as a keyboard](https://support.yubico.com/hc/en-us/articles/360013790279-The-YubiKey-as-a-Keyboard) so that is why termux thinks you are using an external keyboard (and do not need the soft-keyboard). 

It used to be possible to show the keyboard by pressing keyboard in the left drawer, but this apparently does not work anymore now that I tried it

**Comment by cmosetick** [comment]
Hi @Grimler91, Thanks for the link regarding the Yubikey being identified as a keyboard. As I mentioned in my original report, Termux is the only application I have installed on the device that has this issue with disappearing + not able to return on-screen keyboard.

At least, I can not find any other applications.
Various note taking applications, web browsers, etc. etc., all have functioning keyboards with the device plugged in.

Additionally some applications IF open already when the Yubikey is plugged in, make the keyboard go away.
BUT, they let me tap on the screen of the Application, and then the on-screen keyboard comes back with no issues.

As you mentioned above, it seems like there should be a way to force the Termux on-screen keyboard to open by tapping something within Termux.

**Comment by agnostic-apollo** [comment]
It's weird that it's working for other apps, but when you connect the yubikey and open termux, there might be a notification shown to select input method, it may have a toggle to enable soft keyboard. Or check Language and Input in android settings.

Otherwise try following with `adb`. Some phones like Xiaomi have additional options in Developer Options to disallow granting secure settings permission, so if the command doesn't work, check those toggle as well, although don't think following commands would be prohibited.

```
# get the value
adb shell settings get secure show_ime_with_hard_keyboard

#set the value
adb shell settings put secure show_ime_with_hard_keyboard 1
```

**Comment by codebam** [comment]
This isn't a bug. You need to pull down your navbar and switch back to your default on-screen keyboard from the notification. The Yubikey identifies itself as a keyboard to Android.

**Comment by cmosetick** [comment]
@codebam What is navbar?

**Comment by agnostic-apollo** [comment]
He means the status bar at the top of android UI (navbar is the bottom one). While the keyboard is being used by an app, a notification is shown in the notifications list to `Select Input Method`, it might have a toggle to enable/disable soft keyboard. If the toggle isn't there, then it should be in `Language and Input` section of `Android Settings`. If its not in either places, try to use the `adb` method mentioned. The toggle will probably only show when a hardware keyboard is attached. For android avd, there is a [Keyboard Button](https://github.com/termux/termux-app/pull/1953#issuecomment-819314958) instead of a notification.

**Comment by TPS** [comment]
Related to https://github.com/termux/termux-app/issues/1634?

**Comment by agnostic-apollo** [comment]
Can you guys check if 4d1851e6 solves the issue. The debug build apk is available [here](https://github.com/termux/termux-app/actions/runs/821865196). Note that you won't be able to install the apk if you are using F-Droid or Play Store builds. Check https://github.com/termux/termux-app#installation. If you can't reinstall, then wait for new update to be pushed to F-Droid. Thanks.

**Comment by RalfWerner** [comment]
Thanks for the answer to:
>I've checked`*)` your [artifact](https://github.com/termux/termux-app/actions/runs/821865196) with [OS-KB-Toggle](https://github.com/termux/termux-app/commit/4d1851e6beb5afb9c8de952797364fb4ff14faf2) update, but no changes found. _**What should change in which configurations?**_
`*)` On Android 10 and 11 AVD emulators with PC-KB=External-KB and SM-P610 (Android 11) with BT-KB. This device can also be operated with PC-KB when the screen is mirrored (`scrcpy`) to PC. In both cases, PC-KB has _no influence_ on OS-KB Toggling. All checks described in [1953](https://github.com/termux/termux-app/pull/1953#issuecomment-817907932) [ff](https://github.com/termux/termux-app/pull/1953#issuecomment-808695881) [...](https://github.com/termux/termux-app/pull/1953#issuecomment-813446277) are unchanged. Toggling only with `KEYBOARD` (extra key) _**still does not work!**_

Hackers KB I've used for years on all my real devices, but _not on AVD_, since PC-KB can be used here. However, I prefer to use Floating KB, if possible (Swift, Gboard, Samsung). Differences I could _not_ determine between the various OS-KB, except floating at some.
I also tested now on my Huawei (Android 8) with your Artifact and USB-KB. The result is like SM-P610 with BT-KB, except the disabling only with 2 or 7 steps is possible. In both cases, on both devices with the `KEYBOARD` Extra Key OS-KB _**can not be switched on again.**_
> ... and android 11 avd and everything is working as mentioned above.

What did you use as a _**second KB in the emulation?**_ The PC-KB has _no interaction_ with the Termux settings for me!

**Comment by agnostic-apollo** [comment]
Well, I have pushed some [more commits](https://github.com/termux/termux-app/commits?author=agnostic-apollo&since=2021-05-08&until=2021-05-10) in order to attempt to fix soft keyboards not opening in some cases. Not sure if this will solve the **issue** for some specific devices where soft keyboard doesn't open if hardware keyboard is attached, since I can't reproduce that in LG G5 android 7 device and android 10 and 11 AVDs. You can grab the debug build APK from [here](https://github.com/termux/termux-app/actions/runs/826513065). If soft keyboard doesn't open automatically, try using the `KEYBOARD` toggle button in drawer or extra keys now and see if that works. If it still doesn't, then someone who has this issue with their device, who has knowledge of android `logcat`, can use `debug` builds and can communicate properly, should contact me, and we can try to fix the issue if possible.

I have also added support for `soft-keyboard-toggle-behaviour` `termux.properties` property which can be used to change the default behaviour of `KEYBOARD` toggle buttons from `show/hide` to `enable/disable`. You can add the line `soft-keyboard-toggle-behaviour=enable/disable` to `termux.properties` and then run `termux-reload-settings`. This will make the keyboard toggle buttons to disable (and hide) the keyboard and tapping on the terminal view will not open the keybaord automatically, until the keyboard toggle button is pressed again manually. This has been tested on android 7 device, android 10 and 11 AVDs, including split screen and floating keyboard and is working for all cases. (e4e638bd)

**Comment by agnostic-apollo** [comment]
>Toggling only with KEYBOARD (extra key) still does not work!

Are you trying to show/hide soft keyboard or enable/disable it? Working fine on my AVD, even on previous artifact, even though its behaviour was not changed from `v0.112` 39c69db8

>I use hide-soft-keyboard-on-startup=true in *.properties  - OS-KB should always not show! 

That got broken in previous artifact, should be fixed now.

>However, I prefer to use Floating KB, if possible (Swift, Gboard, Samsung)

If hardware keyboard is connected, and `Show on-screen keyboard while hardware keyboard is attached` toggle in Android `Language and Input` settings is **disabled**, these keyboards would **not show**. At least Gboard does not and there is no setting for it in Gboard settings. Only HackerKeyboard has `Show soft keyboard` (always) setting. Termux can't fix this. Only keyboard app can change this behaviour.

>disabling only with 2 or 7 steps is possible. 

Disabling has been implemented now, check above.

>What did you use as a second KB in the emulation?

Laptop keyboard as hardware, GBoard/HackerKeybaord as software.

>The PC-KB has no interaction with the Termux settings for me!

I have no idea what you mean. Termux has **no setting** for hardware keyboards.

**Comment by Grimler91** [comment]
@agnostic-apollo it works as intended with `Show soft keyboard` enabled, and `soft-keyboard-toggle-behaviour = show/hide` or `soft-keyboard-toggle-behaviour = enable/disable` does what it advertises, nice work. 

There's one bug when rotating the screen on my galaxy s8, LOS 17.1, when `Show soft keyboard` is off.
If I start without keyboard in landscape, attach the keyboard and rotate the screen and then try to toggle the keyboard, then termux only fills half the screen, see this [screen recording](https://grimler.se/files/keyboard.mp4).

A logcat from termux does not show anything related.

**Comment by agnostic-apollo** [comment]
Great. Welcome.

Hmmm, this could be tricky. I can't seem to reproduce it on my LG G5. Moreover, set log level to `Verbose`, then it will show termux internal keyboard related log entries. You can even run logcat command in termux `logcat | grep -iE "TermuxTerminalViewClient|keyboard"` for termux internal logging or `sudo logcat | grep -iE "TermuxTerminalViewClient|keyboard"` if you want to include android os logcat logs too if you have root. Although, internal ones are not likely to be helpful for this. Did this happen in `v0.112` as well or just in the artifacts? But this does seem like a ROM bug, it's likely related to [`SOFT_INPUT_ADJUST_RESIZE`](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#SOFT_INPUT_ADJUST_RESIZE) which pushes up the view when keyboard is opened instead of the keyboard opening on top of the view (hiding stuff). If the `Show soft keyboard` toggle was off, then this resizing shouldn't happen. It seems resizing does, but keyboard is never opened since its not supposed to. What happens if you change behaviour of keyboard toggle to `enable/disable`? Hopefully, that doesn't cause the issue.

**Comment by RalfWerner** [comment]
I tried all the settings by `*properties` and menus. The case _"OS-KB only with Extra Key"_ I could not achieve a hiring. Maybe it is only my device, that PiP can. So, for example, when changing from Github Picture to the Termux Picture always the OS-KB is displayed or at with `disable` never, no matter what I'm trying.

**Comment by agnostic-apollo** [comment]
By default when you open termux it **automatically takes focus of terminal view** and **opens soft keyboard**. When soft keybaord is closed, like with back button, you can tap on terminal view to open keyboard too.

If `hide-soft-keyboard-on-startup=true` is set, then when termux is opened or switched back from another app from recents menu, **focus is not automatically taken** and **soft keyboard is not opened**. This **does not** work with PIP, when you tap on termux app box, you are **not selecting the termux app** but **focusing/tapping on the terminal view** which opens keyboard. The only way to prevent this is to **disable** the keyboard, either from Termux Settings or keyboard button toggles with `soft-keyboard-toggle-behaviour=enable/disable` property set. With split screen if you tap termux in recents menu to switch to termux app (termux on bottom), keyboard will **not open**, but if you tap on termux app box (termux on top) keyboard **will open**.

>soft-keyboard-toggle-behaviour=disable

That is **invalid** value. There are **only two** valid values: `soft-keyboard-toggle-behaviour=show/hide` and `soft-keyboard-toggle-behaviour=enable/disable`

**Comment by RalfWerner** [comment]
> ... There Are Only Two Valid Values: `soft-keyboard-toggle-behavior=show/hide` and `*=enable/disable`

OK thanks! Only with `enable/disable`, I can reach my desired behavior but only _without **BT-KB**_. The Values ​​are _not_ interchangeable, as far as I've checked. Any incorrect spelling or swap as `hide/show` makes _**something else**_ (no error message). The Settings [Shot2](https://github.com/termux/termux-app/issues/1995#issuecomment-837401024) (step 5 of 7) are thus changed but also with every `KEYBOARD` application. This also relyed when the file `*.properties` is changed and with `termux-reload-settings` or `New Session` (`DRAWER` popup over `KEYBORAD` [above](https://github.com/termux/termux-app/issues/1995#issuecomment-837447023)) and applies to _all_ sessions. The _session toggle_ (`NEXT` popup over `ENTER` above) often leads to the state that _**no KB works anymore!**_ 
Long Tap on `KEYBOARD` in the Drawer dazzles Extra Keys and thus the KB Toggle.

What do you think of the [Solution](https://github.com/termux/termux-app/pull/1953#issuecomment-808247534): All devices with PiP (should belonging to Android 11 but is not in AVD) use _as default_ `*=enable/disable` and `hide*=true`, if Extra Keys are _displayed with_ `KEYBOARD` - _do **not need** the two properties (lines 3+4 above)?_

**Comment by agnostic-apollo** [comment]
Well the os logs don't show anything related, but thanks!

Yeah, likely is a LOS issue, maybe report that. As far as solving it from Termux side is concerned, I am not sure if its possible directly. You see, in Android, there is/was no **official** `isKeyboardOpen()` API, the best [you could do](https://stackoverflow.com/questions/4745988/how-do-i-detect-if-software-keyboard-is-visible-on-android-device-or-not) is check if the height of the specific view in your app does not match the screen height or its hardcoded height, since keyboard will take some of it, but that of course doesn't work in PIP/split screen/floating keyboard. API 30 has finally [introduced](https://twitter.com/chrisbanes/status/1296164894199382025) an API, which I [implemented](https://github.com/termux/termux-app/blob/4ecea144bb4d3dd511fa551410f9a481ddd43b92/termux-shared/src/main/java/com/termux/shared/view/KeyboardUtils.java#L85) but didn't use, since doesn't work in android 7 at least. An I'm not sure, but the API likely uses similar view related calculations to decide if keyboard is open.

Anyways, in your case, if we use the above ways, I don't think there is a reliable way to differentiate between **keyboard open and taking space** vs **keyboard not open but blank space being taken**. The best I could do considering you have confirmed that `enable/disable` is working, is to add another option in Termux Settings for `Disable soft keyboard only if hardware keyboard attached`. That should be helpful for other use cases as well. I have added that in 90c9a7b, which details its behaviour. Let me know how it goes and if it has any issues.

**Comment by RalfWerner** [comment]
Thanks for the adjustments @agnostic-apollo. I considered this initially _"formally"._ It increases the number of sources from 197 to 205. The [adjustment](https://github.com/termux/termux-app/commit/c24f0d758b82a5f65127dccd20de81c43e426255#commitcomment-50771884) from @Fornwall to 200 and both together should contain 208. _merge_ conflicts I've not discovered and the `v112` works identical (checked yesterday) so I recommend _**merge now**_ to avoid the problems of `Android 10` branch and it could solve the [$nl](https://gitter.im/termux/dev?at=6098e86575aeb43be739a5ee) problem. Your `gradlew.bat` update change nothing but `git` works differently on windows/linux (see [here](https://github.com/RalfWerner/integrated-process/issues/2#issuecomment-780625381))!

I did not get feedback yet to [what you've used for AVD as external KB for testing](https://github.com/termux/termux-app/issues/1995#issuecomment-837401024) and [common OS-KB features ... from the X11 plugin. Could you take a look at it](https://github.com/termux/termux-app/issues/1995#issuecomment-839656224) 

If I have complete the check your changes on my devices, I'll contact you again - thanks so far :)

**Comment by agnostic-apollo** [comment]
@RalfWerner

>The Values ​​are not interchangeable, as far as I've checked. Any incorrect spelling or swap as hide/show makes something else

Would you also like some German language combinations to be supported as well? 

> (no error message)

Errors are  currently not thrown. At verbose log level, the values that are loaded are logged. Some updates and design changes need to be made in future to support setting termux.properties from Termux Settings, so will fix in that.

 >All devices with PiP (should belonging to Android 11 but is not in AVD) use as default *=enable/disable and hide*=true

Very complicated logic and no special need for it anyway since user can easily configure in couple of minutes. They will also complain about different behaviour from normal.

>In your TermuxConstants I have not discovered anything from the X11 plugin. Could you take a look at it?

No specific usage of X11 plugin in termux and it was never released officially.

> Your gradlew.bat update change nothing but git works differently on windows/linux

It wouldn't change behaviour on windows since that's controlled by [gitattributes](https://git-scm.com/docs/gitattributes). It just fixes an issue of `gradlew.bat` marked as modified automatically after `git clone` on some old version of git, like people on Ubuntu `16.04` who are using the archived apt repo http://us.archive.ubuntu.com for installing git which is currently still at [v2.7.4-0ubuntu1.10](http://us.archive.ubuntu.com/ubuntu/pool/main/g/git/) from/based on 2016, issue may occur on other distros as well which are at old git versions. Although for ubuntu, [git PPA](https://git-scm.com/download/linux) can be manually added to get currently latest git `v2.31.1`.

**Comment by RalfWerner** [comment]
> Would you also like some German language combinations to be supported as well? ... made in future

No thank you I understand English pretty well! With _spelling_ I meant _typo_ or writing mistakes. ... so it comes - nice.
> It just fixes an issue of gradlew.bat marked as modified

I use WSL for`git clone` and CMD for`call gradlew *` (every line would be supplemented by`<cr>`) - no matter,it's just `touch`
> Very complicated logic and **no special need** for it anyway since user can easily configure in couple of minutes. **They will also complain about different behaviour from _normal._**

The behavior (constant unmotivated OS-KB) I has only noticed with my new SM-P610 device (tablet) as a problem and it does not occur with other apps. With the current `*.properties` possibilities, also working on the mobile phones is improved.
![grafik](https://user-images.githubusercontent.com/45426380/118364293-34c64e80-b598-11eb-8113-c3773c9e9c24.png)
Shot to: "but only _without_ BT-KB" above. By this setting, I expected to be able to display OS-KB with the `KEYBOARD` Extra Key even when BT-KB is coupled. Unfortunately, it did _**not work.**_

> No specific usage of X11 plugin in termux and it was never released officially.

Does that mean you _will not_ take a look at it, although it is the [best](https://github.com/termux/termux-app/issues/2059#issuecomment-841208020) XServer? You said nothing about _external KB at AVD_, so I suspect that does not test that either and also nothing ti my _recommend **merge now**_ so I assume you will _not_

**Comment by RalfWerner** [comment]
### Addendum to the shot above
and OS-KB Toggle with BT-KB. I have another video (1:14 without sound <10MB) created on this topic:

https://user-images.githubusercontent.com/45426380/118678580-6f7cf080-b7fd-11eb-9f7f-273e4685aecc.mp4

This is a Supplement to the [1st](https://github.com/termux/termux-app/pull/1953#issuecomment-817729184) (at begin) and created with v113. There is a solution but _only with the Android Settings_ (in german on my SM-P610), even if it is quite complicated. The Termux Settings have _no influence_ on it and will changed (1:10) without my actions (0:58). I do not seem to understand the meaning of the 2nd choice.

**Comment by agnostic-apollo** [comment]
@cmosetick Does the issue still happen with changes in recent termux versions? Current F-Droid version is `v0.116`.

Issue should be closed if its fixed.
