### ISSUE TITLE
Not install

### ISSUE THREAD

**Issue by ReniSalcedo79** [termux/termux-app#1997]
**Problem description**

Do not install any Termux version of F-Droid in Motorola One Hyper
-->

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:All
* Android OS version:10
* Device model:Motorola One Hyper

**Comment by xeffyr** [comment]
Before installing Termux from F-Droid, or if you don't know the source from where apk was downloaded, first **uninstall** (yes, open Android settings --> applications and uninstall) the application and plugins:
* Termux
* Termux:API
* Termux:Boot
* Termux:Widget
* Termux:Float
* Termux:Styling
* Termux:Tasker

If you think you have not plugins installed, strongly suggesting to go through application list in Android settings and double check.

***

Application and add-ons should come from same source because of design requirement all apks should be signed with same key. Google Play and F-Droid builds are signed with *different keys*.
