### ISSUE TITLE
Add special keys with volume key shortcuts

### ISSUE THREAD

**Issue by AnderRasoVazquez** [termux/termux-app#2]
Here's the list that uses "Terminal emulator" https://github.com/jackpal/Android-Terminal-Emulator
I find those shortcuts super useful, would be nice to implement them to Termux.
![photo_2015-10-26_16-51-27](https://cloud.githubusercontent.com/assets/3936719/10734135/1113e73e-7c02-11e5-93c5-2158577ed21f.jpg)
Bajar = Down
Subir = Up
Espacio = Space

Keep up the good work! =D

**Comment by fornwall** [comment]
Hi, thanks for the feedback!

Since the terminal emulation of Termux comes from the Android Terminal Emulator project, these shortcuts should already work (let me know if you have any problem with them)!

They are documented at http://termux.com/help/#touch_keyboard which is also available by long pressing on the terminal and choosing the `Help` context menu entry!
