### ISSUE TITLE
Publish a Release apk in Github Releases

### ISSUE THREAD

**Issue by chromer030** [termux/termux-app#2011]
**Feature description**

Please publish a release apk for every version , because fdroid is very slow in updating its repositiory.
I know we can use debug apk from github action but it has more size in compare to release version.
Thank you.
**Reference implementation**

**Comment by Yonle** [comment]
Well i agree with this

**Comment by agnostic-apollo** [comment]
We don't have access to signing keys for the F-Droid releases, they manage it themselves. So we can't release an APK that's compatible with F-Droid releases on github.

We currently have 3 different variants, google play, f-droid and debug builds, which aren't compatible with each other. We already have to deal with a lot of users reporting issues about google play/f-droid incompatibility, adding another variant would cause even more issues.

> I know we can use debug apk from github action but it has more size in compare to release version.

The [latest](https://github.com/termux/termux-app/runs/2398803082) one is `89MB`, the [last fdroid release](https://f-droid.org/en/packages/com.termux/) is `85MB`, and `v0.109` added a lot of code, so increased size is likely due to it. So "more size" would be insignificant. Moreover, obfuscation has been disabled in `v0.109`, so even F-droid releases after that will have similar sizes to debug builds.

**Comment by agnostic-apollo** [comment]
The [fdroiddata](https://gitlab.com/fdroid/fdroiddata) [current build server activity](https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=7&from=&hidebots=0&hideanons=1&hideliu=1&limit=500) shows that termux `v0.109` builds have been [failing internally](https://f-droid.org/wiki/page/com.termux/lastbuild_109). A commit is [referenced](https://gitlab.com/fdroid/fdroidserver/commit/e2214ebc4b1920dfeeb1c3830f1865cac30c4f7b) which is probably the issue. Been happening since the 15th, that's probably why an update still hasn't been released. So kindly wait, it should hopefully be released soon.

**Comment by agnostic-apollo** [comment]
I have updated the [README](https://github.com/termux/termux-app) with detailed info about this. I have also added the debug APK link in the [`v0.111`](https://github.com/termux/termux-app/releases/tag/v0.111) release. I guess adding the debug APK link to each release is something doable by maintainers so that users who want to quickly get the update can do so without having to look for it.

Closing this for now since currently there are no plans for an alternate source. Can be opened again if ever needed.

**Comment by hrap1919** [comment]
BTW, I just uploaded the release build of my fork https://github.com/hrap1919/termux-app/releases/tag/v0.111. It is built manually with the developer keys, so it is compatible with the artifacts builds from the main branch. It has no bootstrap-archives and can be installed as an "update" of the full debug build.

**Comment by agnostic-apollo** [comment]
According to the `metadata/com.termux.yml` [file history](https://gitlab.com/fdroid/fdroiddata/-/commits/master/metadata/com.termux.yml) referenced by `Build Metadata` on [Termux F-Droid page](https://f-droid.org/en/packages/com.termux/), the F-Droid guys have tried to fix the build failures 3 times already, but it [failed today](https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=7&from=&hidebots=0&hideanons=1&hideliu=1&limit=500) as well. And currently only `v0.109` has been added to the [`metadata/com.termux.yml`](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.termux.yml#L677) file, the later versions would probably be added after the current build succeeds.

**Comment by jspricke** [comment]
Hi,

the app fails to build because of:
```
2021-04-22 00:26:39,572 ERROR: Found unknown maven repo 'https://maven.pkg.github.com/termux/termux-app' at termux-shared/build.gradle
```
You are using a private maven repo which is not allowed on F-Droid.

New version are not picked up because you changed the version code logic making the F-Droid bot fail to pick them up. If you could revert a6ae656, that would solve it.

Thanks!

**Comment by jspricke** [comment]
For reference, you can find the list of allowed maven repos here: https://f-droid.org/docs/Build_Metadata_Reference/#build_srclibs
maybe you can use one of them?

**Comment by agnostic-apollo** [comment]
Hi @jspricke,

Thanks for reporting in. We were previously hosting on Bintray but had to [move](https://github.com/termux/termux-app/commit/397a78f24803fd4bb11142d8dddea36ccf6fbb2d#diff-0dbd147c4293319111519eda200fb44ed0897976baee77b219b3d8ce176d18d0) to Github Packages since its being shut down. Just to be clear, are you saying that our Github Packages Maven repository [here](https://github.com/orgs/termux/packages?repo_name=termux-app) is not allowed by F-Droid and we need to shift to one that is allowed before builds will succeed? If yes, any reference implementations you know of would be of great help if you have the time, otherwise will look ourselves. Thanks

>New version are not picked up because you changed the version code logic making the F-Droid bot fail to pick them up. If you could revert a6ae656, that would solve it.

I will change back the logic and make a new release. Will there will be a jump in versions on F-Droid?

Thanks a lot.

**Comment by jspricke** [comment]
> Just to be clear, are you saying that our Github Packages Maven repository [here](https://github.com/orgs/termux/packages?repo_name=termux-app) is not allowed by F-Droid and we need to shift to one that is allowed before builds will succeed?

Yes.

> If yes, any reference implementations you know of would be of great help if you have the time, otherwise will look ourselves. 

See the link in my comment above.

> I will change back the logic and make a new release. Will there will be a jump in versions on F-Droid?

Thanks! F-Droid updatebot will find the new version then, so all should be fine.

**Comment by agnostic-apollo** [comment]
> Yes.

Okay, I asked caused the move was made on Feb 12, before the `v0.108` [release](https://gitlab.com/fdroid/fdroiddata/-/commit/541b879f742d77977f5b3c2c15126638666865c4) on Feb 21, which succeeded and is currently available. I see that patches were made for `terminal-view` and `terminal-emulator` packages for `v0.108` in `com.termux.yml`. The `v0.109` added a new package named `termux-shared` but its patch is not added to [`v0.109` in `com.termux.yml`](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.termux.yml#L685), likely why the build is failing, But will look into moving the packages to a different repository since patches can't be expected to be done on every release.

Thanks again.

**Comment by jspricke** [comment]
Ha, I totally missed that, I adopted the patch, so it should work now. Thanks!

**Comment by agnostic-apollo** [comment]
Great, I assume we still need to move the repository for future versions to comply with policy? Thanks.

**Comment by jspricke** [comment]
> Great, I assume we still need to move the repository for future versions to comply with policy? Thanks.

There should be no need. F-Droid has a policy for used maven repos, not for published repos (afaik).

**Comment by agnostic-apollo** [comment]
That's good to hear. Thanks again for checking in and your contributions :)

**Comment by agnostic-apollo** [comment]
So the patch was [applied](https://gitlab.com/fdroid/fdroiddata/-/commit/3dac4f6e59129f2c7288c20bd4f9de9ad0de6d6c) yesterday for update to `v0.111` by @jspricke and its build was [successful](https://gitlab.com/jspricke/fdroiddata/-/jobs/1203977298#L2769).

The main build logs are posted on [F-Droid monitor](https://monitor.f-droid.org/builds) site, if someone wants to see [failed log for v0.109](https://monitor.f-droid.org/builds/log/com.termux/109).
