### ISSUE TITLE
Question: What is the mechanism of killing processes in Termux

### ISSUE THREAD

**Issue by mitnk** [termux/termux-app#2015]
I was running `crond` with Termux in another phone work very well. I recently switched to a new phone, the battery optimizer may have issues, and causing the `crond` process killed randomly.

![image](https://user-images.githubusercontent.com/177049/115942788-73f40900-a4de-11eb-807d-f7b595dda75d.png)

> the `pss` here is: `ps ax | sed 's|/data.*/||'`

Note that the `crond` is killed, but the shell process (pid 2717) is not.

I want to understand how these things happen in the background. Where could I find more clues on how this `crond` is killed. I've locked this app, and acquired the wake lock. I've set the OS NOT to do any battery optimization on app `Termux` and `Termux-API`.

![image](https://user-images.githubusercontent.com/177049/115942878-10b6a680-a4df-11eb-845d-650936c9eefc.png)
![image](https://user-images.githubusercontent.com/177049/115942882-190ee180-a4df-11eb-8add-5ad7203cb6e8.png)

```
$ termux-info
Application version:
0.110
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 5.4.61-qgki-01148-g376d4ad #1 SMP PREEMPT Sat Apr 17 03:38:45 CST 2021 aarch64 Android
Device manufacturer:
OnePlus
Device model:
LE2110
```

I've tried v0.108, same issue in this phone. I know the main issue must be due to this phone. But I want to know if there is anything we can do in termux side. (e.g. Does the OS have the ability of killing only one of processes in Termux? etc)

**Comment by agnostic-apollo** [comment]
> Does the OS have the ability of killing only one of processes in Termux? etc)

Usually the activity and services running in app's main process should be all or nothing. Check [here](https://developer.android.com/guide/components/processes-and-threads.html) and [here](https://stackoverflow.com/questions/24883738/does-android-kill-each-service-or-the-whole-process). But empty processes that are not linked to a component may get killed too, as per [this](https://stackoverflow.com/questions/33335246/process-being-killed-on-marshmallow-but-not-on-lollipop). A related issue to yours is posted in termux/termux-boot#5 and the solution is to use `termux-job-scheduler` implemented in termux/termux-api-package#42.

**Comment by mitnk** [comment]
Thanks @agnostic-apollo, I've tried `termux-job-scheduler`. It is much stable than crond, but has the issue of mix interval is 15 minutes. I'll check other resources you posted.

**Comment by agnostic-apollo** [comment]
Welcome. From a "quick look" the min interval of 15mins is a limitation of android `JobScheduler setPeriodic()` used by [termux-api](https://github.com/termux/termux-api/blob/v0.47/app/src/main/java/com/termux/api/JobSchedulerAPI.java#L160) and probably doesn't work in doze mode. I guess `AlarmManager` can be implemented instead to provide shorter intervals. It can be looked into into in future.

**Comment by mitnk** [comment]
Some follow up: I found it is one specific service who killed `sshd`:

```
$ adb logcat | grep sshd
06-13 12:57:20.255  1722  1722 E OPLUS_KEVENT_RECORD: OPLUS_KEVENT payload:10348,path@@/data/data/com.termux/files/usr/bin/sshd
06-13 12:57:20.274 28862 28862 I sshd    : Server listening on :: port 8022.
06-13 12:57:20.274 28862 28862 I sshd    : Server listening on 0.0.0.0 port 8022.
...
06-13 12:57:58.269 29371 29371 I sshd    : Starting session: shell on pts/1 for u0_a348 from 192.168.0.105 port 49231 id 0

06-13 13:00:12.184  8930 10124 I Athena  : OppoClearSystemService : K [28862][10348]sshd(0), reason: 71
06-13 13:00:12.184  2087  2826 E AthenaKillerManagerService: o-kill [28862] sshd
06-13 13:00:19.069  8930 10124 I Athena  : OppoClearSystemService : K [29371][10348]sshd(0), reason: 71
06-13 13:00:19.070  2087  9518 E AthenaKillerManagerService: o-kill [29371] sshd
```

Seems I need to fill up a bug-report for the phone vendor or find a way to disable this "Athena" service.

**Comment by agnostic-apollo** [comment]
Disabling system services itself would likely require root. You could try a less aggressive custom ROM if you are willing to root. Or try adding termux to exemptions in your phone's killer app. Check https://dontkillmyapp.com/oneplus

**Comment by mitnk** [comment]
Thanks. I won't try rooting the system. I've try every thing adjusting the settings (most items listed in this page). Nothing works.

<a href="https://dontkillmyapp.com/oneplus"><img id="badge-shareable" width="306px" src="https://dontkillmyapp.com/badge/oneplus3.svg"></a>

**Comment by mitnk** [comment]
@agnostic-apollo Do you know the differences between the shell process (e.g. bash) and the background job (e.g. sshd, crond) in Termux? I mean why `sshd` got killed but not the shell process?

**Comment by agnostic-apollo** [comment]
Exempting termux from app killer would reduce chances of `com.termux` app process from being killed but not demonized processes like `sshd` due to empty process issue as described above. Probably the only way to reduce empty process from being killed is OS/kernel level modification. Even without app killers, Android Low Memory Killer (LKM) would kill app or empty processes under memory pressure. So exemption would need to be made in `ActivityManager` or adjustment of `minfree` values. For more info on LKM and OOM, check [here](https://forum.xda-developers.com/showthread.php?t=2751559), [here](https://lwn.net/Articles/317814/), [here](https://github.com/mcgill-cpslab/mobile-research/wiki/How-Android-manages-background-processes%3F) and [here](https://www.linuxjournal.com/content/android-low-memory-killer-or-out).



> Do you know the differences between the shell process (e.g. bash) and the background job (e.g. sshd, crond) in Termux? I mean why `sshd` got killed but not the shell process?

The difference is as per below. The `bash` shell process is the child process of `com.termux` app process, so still attached to a component. Whereas `sshd` has been demonized and not attached to `com.termux` and inherited by `init`. So `bash` shell would get killed when and if termux app process is killed. For `sshd`, you can run run it with `sshd -D` so its not demonized and leave it running in a separate termux session, this way `sshd` would be child process of `bash` shell process and hopefully won't be killed. If you already have `sshd` running, then kill it first with `pkill sshd` otherwise running command again won't start it since port would already be taken. You can confirm this with `sshd -D -dd`. You can also run it with `nohup sshd -D &>/dev/null &` so it runs in [background, (not daemon)](https://stackoverflow.com/a/66240690) if you don't want a separate session for it.


```
$ sshd
$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
u0_a449  10309 30676  5 12:09 ?        00:00:10 com.termux
u0_a449  10361 10309  0 12:09 pts/0    00:00:00 /data/data/com.termux/files/usr/bin/bash -l
u0_a449  10920     1  0 12:12 ?        00:00:00 sshd
u0_a449  10930 10361  3 12:12 pts/0    00:00:00 ps -ef
```

**Comment by mitnk** [comment]
This detailed info make a lot of sense to me. And the `nohup ... &` tip worked (far stable). Thanks a ton!

**Comment by agnostic-apollo** [comment]
You are welcome a megaton!

**Comment by agnostic-apollo** [comment]
@mitnk btw you can run `crond` in foreground too with `-n` flag, like `nohup crond -n &>/dev/null &` so that `bash` shell process is the parent process and `crond` doesn't get killed due to empty process issue after `pkill crond`.

Setup job with `crontab -e` and add `* * * * * date >> ~/cron.log`. Can later edit the job from file under `/data/data/com.termux/files/usr/var/spool/cron` and restart `crond`.

**Comment by mitnk** [comment]
Got it. Thanks @agnostic-apollo!

**Comment by agnostic-apollo** [comment]
Welcome!

**Comment by WMCB-Tech** [comment]
>  Seems I need to fill up a bug-report for the phone vendor or find a way to disable this "Athena" service.
@mitnk

I had the same issue regarding Athena service killing some background processes. apparently it can be disabled using adb:
```
adb shell pm uninstall -k --user 0 com.coloros.athena
```

**Comment by agnostic-apollo** [comment]
Yeah, that's the usual route if an app is being used to kill other apps instead of the android framework. Hopefully, nothing else breaks because of it, some other system app might be relying on it and may cause battery drain. Check `logcat` or BetterBatteryStats`, etc. If everything is fine, then great.

**Comment by mitnk** [comment]
Thanks @WMCB-Tech, I uninstalled it, and the background jobs are now quite stable. adb rocks :)

**Comment by TREYWANGCQU** [comment]
> Exempting termux from app killer would reduce chances of `com.termux` app process from being killed but not demonized processes like `sshd` due to empty process issue as described above. Probably the only way to reduce empty process from being killed is OS/kernel level modification. Even without app killers, Android Low Memory Killer (LKM) would kill app or empty processes under memory pressure. So exemption would need to be made in `ActivityManager` or adjustment of `minfree` values. For more info on LKM and OOM, check [here](https://forum.xda-developers.com/showthread.php?t=2751559), [here](https://lwn.net/Articles/317814/), [here](https://github.com/mcgill-cpslab/mobile-research/wiki/How-Android-manages-background-processes%3F) and [here](https://www.linuxjournal.com/content/android-low-memory-killer-or-out).
> 
> > Do you know the differences between the shell process (e.g. bash) and the background job (e.g. sshd, crond) in Termux? I mean why `sshd` got killed but not the shell process?
> 
> The difference is as per below. The `bash` shell process is the child process of `com.termux` app process, so still attached to a component. Whereas `sshd` has been demonized and not attached to `com.termux` and inherited by `init`. So `bash` shell would get killed when and if termux app process is killed. For `sshd`, you can run run it with `sshd -D` so its not demonized and leave it running in a separate termux session, this way `sshd` would be child process of `bash` shell process and hopefully won't be killed. If you already have `sshd` running, then kill it first with `pkill sshd` otherwise running command again won't start it since port would already be taken. You can confirm this with `sshd -D -dd`. You can also run it with `nohup sshd -D &>/dev/null &` so it runs in [background, (not daemon)](https://stackoverflow.com/a/66240690) if you don't want a separate session for it.
> 
> ```
> $ sshd
> $ ps -ef
> UID        PID  PPID  C STIME TTY          TIME CMD
> u0_a449  10309 30676  5 12:09 ?        00:00:10 com.termux
> u0_a449  10361 10309  0 12:09 pts/0    00:00:00 /data/data/com.termux/files/usr/bin/bash -l
> u0_a449  10920     1  0 12:12 ?        00:00:00 sshd
> u0_a449  10930 10361  3 12:12 pts/0    00:00:00 ps -ef
> ```
> 
> Without daemon
> 
> ```
> $ pkill sshd
> $ nohup sshd -D &>/dev/null &
> [1] 26275
> $ ps -ef
> UID        PID  PPID  C STIME TTY          TIME CMD
> u0_a449  17590 30676  1 12:52 ?        00:00:26 com.termux
> u0_a449  22888 17590  0 13:04 pts/1    00:00:00 /data/data/com.termux/files/usr/bin/bash -l
> u0_a449  26275 22888  1 13:25 pts/1    00:00:00 sshd -D
> u0_a449  26287 22888  3 13:25 pts/1    00:00:00 ps -ef
> ```

GOOD JOB.
THANKS A LOT
