### ISSUE TITLE
Can't input Chinese in Termux with Google Pinyin Input

### ISSUE THREAD

**Issue by zengxu-yang** [termux/termux-app#202]
Termux 0.42
Google Pinyin Input 4.3.3.138040165-armeabi-v7a
Android 5.1.1

There is a language switch key in the Google Pinyin Input panel for the users to switch between Chinese and English inputs. It works for all other apps but Termux. In Termux the language switch key is replaced by a number row, thus making users unable to switch to Chinese.
![screenshot_2016-11-26-01-36-31](https://cloud.githubusercontent.com/assets/15492931/20638588/54a6ac98-b379-11e6-88fd-34db588a2093.png)
![screenshot_2016-11-26-01-37-33](https://cloud.githubusercontent.com/assets/15492931/20638587/54a678ae-b379-11e6-994d-7672536c4f4a.png)

**Comment by rchunping** [comment]
I can't input chinese too.

**Comment by pggdt** [comment]
I got the same problem too

**Comment by BlackGlory** [comment]
You may swipe the extra keys view to the left, there is a feature named [Text Input View](https://wiki.termux.com/wiki/Touch_Keyboard#Text_Input_View), input Chinese characters there.

**Comment by zengxu-yang** [comment]
> You may swipe the extra keys view to the left, there is a feature named [Text Input View](https://wiki.termux.com/wiki/Touch_Keyboard#Text_Input_View), input Chinese characters there.

I just tried the Text Input View in Termux 0.73. It worked. Thanks!

**Comment by muyinliu** [comment]
[SwiftKey](https://play.google.com/store/apps/details?id=com.touchtype.swiftkey) is the only one input method I found that can input Chinese in Termux, **but SwiftKey's Chinese input method is the worse Chinese input method** compare to Baidu/Sougou/Google/... input methods. Its word dictionary is so bad that make me crazy and it **can NOT remember the words I already typed many times**. So SwiftKey is the only choose and be patient with it... Note: there is no hope to make Microsoft improve SwiftKey because there are too many feedback on the Google Play page of SwiftKey already and SwiftKey's developer ignore them for years😅
