### ISSUE TITLE
(Repository is under maintenance or down) how i solve it guys

### ISSUE THREAD

**Issue by alpha77753** [termux/termux-app#2038]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by xeffyr** [comment]
See https://github.com/termux/termux-packages/issues/6726.

Don't use Termux from Play Store.

**Comment by momen-absi** [comment]
GPG error: https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C9F2CB506F14B4
E: The repository 'https://github.com/gushmazuko/metasploit_in_termux/raw/master gushmazuko InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
