### ISSUE TITLE
ESC-c (reset) does not clear scrollback

### ISSUE THREAD

**Issue by thewisenerd** [termux/termux-app#207]
ctlseqs.txt in xterm source says that ESC c is the keycode for a full reset. This is the same for many terminals.
excerpt from ctlseqs.txt
```
ESC c     Full Reset (RIS).
```

the "reset" binary (on my android phone, from toybox) writes the ESC-c sequence when run. output from strace.
```
write(1, "\33c", 2)                     = 2
```

while this works on desktop terminals (via adb shell), this doesn't work so well on termux or other android terminal emulators. is this intended behavior? will this be fixed?

**Comment by fornwall** [comment]
It's a behaviour that varies between terminal emulators, e.g. the macOS terminal doesn't clear scrollback either.

Currently I think this is desirable - if you need to use reset to fix a broken terminal state it's not always the case that you want to loose scrollback history. So, I'm closing this for now, let me know if you have a compelling use case where clearing scrollback history is important!

**Comment by JonasT** [comment]
@formwall I use `reset` in gnome-terminal all the time to clear scrollback very often before lengthy output so I can find it's beginning, because sometimes pagers break (e.g. I was told in IRC that the pager `less` was supposed to properly touch scroll but for me it just didn't, making it a bit of a pain to use compared to plain output) and they're not as straightforward (for someone not using them all the time) to add additional different commands without losing the old output of the previous program to scroll through. It is one of the main reasons I find debugging in `termux` a bit painful despite having a relatively large screen & bluetooth keyboard compared to desktop - the other one being that termux scrollback appears to be hardcoded to not long enough for various types of output to scroll through
