### ISSUE TITLE
Expand, increase the output of the shell (strings, memory).

### ISSUE THREAD

**Issue by xb3b6** [termux/termux-app#2071]
I use some programs that print 5000 lines to the output, but Termux displays only 2500 lines, truncates the beginning of the output.  
It is necessary to increase the output of lines, there is enough power everywhere.

**Comment by Grimler91** [comment]
Isn't it easier to just `tee` the output to a file? Scrolling 5000 lines in termux, without the possibility to goto a specific line or search for a specific string, sounds quite miserable.

You could also use tmux and set the number of scrollback lines, as explained here https://stackoverflow.com/a/18777877

**Comment by xb3b6** [comment]
Surprised by this answer.  
I'm talking about the standard (frequent operation) information output. 
It should be in Termux, tmux is overkill.

**Comment by agnostic-apollo** [comment]
The limit is actually [2000](https://github.com/termux/termux-app/blob/master/terminal-emulator/src/main/java/com/termux/terminal/TerminalSession.java#L121). Support can be added for more.

`for i in {1..2001}; do echo $i; done`

**Comment by xb3b6** [comment]
Even standard **curl** often fails (lacks output). If the shell does not take up a lot of memory, then you need to extend the Termux output as much as possible.

**Comment by xeffyr** [comment]
@xb3b6 Terminal lines are limited since their increase has negative impact on console rendering performance (lags when selecting text or changing font size). For some devices (ROMs) less significant, for some more. It can be increased to 5000 lines, but not more.

`tmux` has configurable scroll back buffer. You can run commands in it instead.

**Comment by agnostic-apollo** [comment]
It should be user configurable with `termux.properties`. Default can stay at `2000` for less ram devices, even though its pretty low. Like QuickEdit app which displays text as an image instead of text, there are limits by android on number of lines and on how many characters can be shown per line. For android `10` with font size `8`, line spacing `0sp`, limit is `650751` lines. For android `7`, max possible limit is like half that. So increasing it likely shouldn't cause problems, but will probably depend on user font size, will have to experiment.

**Comment by agnostic-apollo** [comment]
Yeah, rendering was also what I was thinking off that may have a negative performance impact. Lot of calls are made for it. But newer devices might be capable enough.

**Comment by xeffyr** [comment]
> So increasing it likely shouldn't cause problems, but will probably depend on user font size, will have to experiment.

Increasing scrollback cause lags at least on Lineage OS ROMs. For example, if console filled with thousands lines of output, resizing text become unresponsive and takes effect in 1-2 seconds. Selection works better, though lags are still noticeable.

2000-5000 lines is safe choice. But yes, Termux can have scrollback buffer configurable.

**Comment by agnostic-apollo** [comment]
I see, can experiment and see the impact and put a max limit so users can't go beyond.

Who knows if further optimizations can be made to the terminal to increase the overall performance. Lot of code exists now for lot of things which may not be as efficient as it should be. But that's time consuming stuff to look into.

**Comment by xeffyr** [comment]
Terminal rendering performance is actually old issue but since https://github.com/termux/termux-app/pull/628 it doesn't take much attention.

**Comment by agnostic-apollo** [comment]
> Terminal rendering performance is actually old issue but since #628 it doesn't take much attention.

Thanks for this. And yes, that indeed should be looked into at some point. But lot of "dangerous" and unknown code, so should be done with better understanding of it.

With 0b4bbaf2, I even went to the max limit of `50000` rows and didn't notice lags on my LG G5 Android 7.0, resizing took a 1-2s but that's expected. Rendering from what I see is only focused for the row currently visible, but buffers and indexing would probably have an impact. Users can do it at their own risk.
