### ISSUE TITLE
extra-keys-style = none does not work

### ISSUE THREAD

**Issue by freebrowser1** [termux/termux-app#2074]
**Problem description**
I have an onscreen keyboard which already contains esc, ctrl, tab and arrow keys, so I set in termux.properties

extra-keys-style = none

which should be a valid choice written in the comment above that line.

**Steps to reproduce**
Perform the steps above.

**Expected behavior**
The line with ESC / TAB / CTRL ... above the keyboard should not appear.

* Termux application version: 0.113
* Android OS version: 10.x
* Device model: Oneplus 6

**Comment by agnostic-apollo** [comment]
The `none` is a [valid value](https://github.com/termux/termux-app/blob/v0.113/app/src/main/java/com/termux/app/terminal/io/extrakeys/ExtraKeysInfo.java#L234) and is working fine. Like it would show `UP`, `DOWN`, etc instead of arrows. The extra keys **does not** have anything to do with onscreen keyboard and has no influence on it.

What you instead want is to add the [`extra-keys`](https://wiki.termux.com/wiki/Touch_Keyboard) value manually without `ESC`, `TAB`, `CTRL`, etc to override the [default value](https://github.com/termux/termux-app/blob/v0.113/termux-shared/src/main/java/com/termux/shared/settings/properties/TermuxPropertyConstants.java#L204): `[[ESC, TAB, CTRL, ALT, {key: '-', popup: '|'}, DOWN, UP]]`

**Comment by freebrowser1** [comment]
Thanks, that works !

**Comment by agnostic-apollo** [comment]
welcome
