### ISSUE TITLE
packages that uses user doesn't work anymore after reinstalling

### ISSUE THREAD

**Issue by ReyterYT** [termux/termux-app#2080]
just a few minutes ago i was backing up my data and restoring it in a new termux installed from f-droid and after that packages that uses my user doesn't work because user u0_a615 does not exists on the packages like postgresql and such is there a way to fix this or am i supposed to drop all of my datas

**Comment by xeffyr** [comment]
> that packages that uses my user doesn't work because user u0_a615 does not exists

Expected behaviour. User is assigned by Android OS and there no way to avoid that. Never restore data as root and you won't have uid/gid mismatch.

Use backup/restore method exactly as in https://wiki.termux.com/wiki/Backing_up_Termux

> postgresql and such is there a way to fix this or am i supposed to drop all of my datas

Postgresql database shouldn't depend on system user name. You are not providing the error messages, so it is unknown what the issue with Postgresql.

**Comment by ReyterYT** [comment]
i guess im gonna drop my data then, also thanks for the extra info for the user its helpful so i dont do anymore mistake other than myself. thanks for the response have a great day

**Comment by agnostic-apollo** [comment]
You can try something like [this](https://www.reddit.com/r/termux/comments/nad1iv/how_can_i_restore_termux_data_from_lower_version/gxt90m2?utm_medium=android_app&utm_source=share&context=3) to restore permissions.

**Comment by ReyterYT** [comment]
ill try opening it tomorrow with a vpn since my country blocks reddit for **safety** reason

**Comment by agnostic-apollo** [comment]
Oh boy...

To change ownership to `termux` app user and restore `selinux` contexts for `$PREFIX` and `$HOME`, you can do something like the following from a **non-root** [failsafe session](https://wiki.termux.com/wiki/Recover_a_broken_environment). Note that `id -u` must expand in the current **non-root** shell, outside `su` root shell, to get the current/new user of termux, so don't run the following commands if you are already inside a root shell started with `su`/`sudo`. A fresh fail safe session will be a non-root shell as the current termux user.

```
path=/data/data/com.termux/files/usr; su -c "chown $(id -u):$(id -u) -R $path; restorecon -v $path"
path=/data/data/com.termux/files/home; su -c "chown $(id -u):$(id -u) -R $path; restorecon -v $path"
```

This may affect programs that require root owned files instead of `termux` app user owned, like `~/.ssh` if you use `ssh` from a `root` shell. It would depend on your setup, we can't make guesses what may break. If messing with root, you are also less likely to get "official" support from @termux for personal issues.
