### ISSUE TITLE
Checkra1n CLI doesn't work on Termux 

### ISSUE THREAD

**Issue by quaziqbal** [termux/termux-app#2113]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version: all versions tested 
* Android OS version: Android 11
* Device model: Asus zenfone 6 (Rooted)

**Comment by Grimler91** [comment]
Report checkr1an issues to the checkra1n authors. Hard to know what "doesn't work" actually means, but I guess you are trying to run binaries compiled against glibc which won't work [since android is not linux](https://wiki.termux.com/wiki/Differences_from_Linux). Try in a chroot environment instead.

**Comment by xeffyr** [comment]
> Is there any workaround?

Rooted device --> [Linux Deploy](https://github.com/meefik/linuxdeploy/releases/tag/2.6.0) --> Chroot
