### ISSUE TITLE
Apk size increased?

### ISSUE THREAD

**Issue by MrSimsure** [termux/termux-app#2153]
Hello, i sticked with the play store version of termux until last week, mainly because i didn't know about the movement to f-droid.
I tried installing the latest f-droid version but suddenly noticed that the clean installation of termux now weight 182MB, i remembered the play store version to be a lot smaller when i initially installed it, so i got i back to check, and in fact the latest play store version was just 82MB on a fresh install.
Is this normal? Are the play store apk threaded in some ways that make the final installation lighter?
Initially i tought that could be for the different arch versions inside the apk, checking the f-droid downloaded apk the lib folder contains all the different arch versions of the main libraries, this used to be different when the app was on play store?
There is something that can be done or all this additional 100MB actually added content that cannot be reduced?
Thanks

**Comment by xeffyr** [comment]
Play Store APK is smaller because it contains the bootstrap archive only for one architecture. Each bootstrap is about 20 MB.

F-Droid contains bootstrap archives for all architectures, since it doesn't support splitting APKs. Technically, there is a hack to be able submit a per-architecture build variant, but it all about messing up with version numbers (each release will mean 4 different versions, aka v0.116 = v0.116 + v0.117 + v0.118 + v0.119).

Also don't forget that nowadays Termux removed BusyBox and uses full-blown utilities which result increased initial installation size.

**Comment by agnostic-apollo** [comment]
Termux APKs require a [bootstrap zip](https://github.com/termux/termux-packages/releases) containing binaries required for minimal shell environment.

F-Droid does not support split APKs so APKs published there contain zips for all 4 architecture so size is roughly `~80MB` on F-Droid . Termux App source code itself is pretty small. Play store supported split APKs so APK size was `~20MB`.

Then the `bootstrap.zip` is first extracted unzipped by android to app native directory under `/data/app/com.termux-<suffix>/lib` only for your phone's architecture. So that increases size to `100MB` (`80`+`20`) for F-Droid. You can find real path with `adb shell pm path com.termux`.

Then the extracted `bootstrap.zip` in app native directory is unzipped and installed at `/data/data/com.termux/file/usr` when you first open termux. That size likely differs depending on filesystem block size, etc and may be roughly `~70MB`. Lot of other stuff have also been added since last playstore release.

So `80+20+70=170MB` for F-Droid and `20+20+70=110MB` for play store.

**Comment by agnostic-apollo** [comment]
> (each release will mean 4 different versions, e.g. v0.116 = v0.116 + v0.117 + v0.118 + v0.119).

That's just insane for users and devs.

> User: App won't install from F-Droid.
> Devs: Uninstall from playstore...
> User: Still won't install
> Devs: Yes, because installing wrong version not meant for your architecture. Which model and architecture is your phone? Have you installed a custom ROM?
> User: `<this>` architecture.
> Now go on F-Droid and install `<this>` version.

Then we later find out some plugin app from playstore was still installed... Best wait until F-Droid officially supports its somehow if possible. Haven't checked up on it.

**Comment by MrSimsure** [comment]
Having a phone with very low storage every MB i can save is gold, but if nothing can be done to decrease the fresh installation size, i will probably stick with the play store version untili get a new phone.

**Comment by agnostic-apollo** [comment]
As per dccd155b, you can now download architecture specific debug build APKs. Check https://github.com/termux/termux-app#installation for what they are. They are not compatible with F-Droid termux app or plugin releases, install plugins from respective Github Actions github page of each plugin. Their termux-app link is added in each release https://github.com/termux/termux-app/releases. Currently latest one is at https://github.com/termux/termux-app/actions/runs/992053369

**Comment by Pokherali** [comment]
I am bit new to github. I have been using termux for past 3 years and learned a lot. But since it's no longer supported in google app store. I wanna install it from github directly (not from fdroid). Can some one help me with it. Share me a steps or a YouTube video links if any. Done lots of searching in internet and YouTube and found nothing helpful on installing termux from github directly. Thanks

**Comment by agnostic-apollo** [comment]
Checking `README` should be the first place to look.

https://github.com/termux/termux-app#github

**Comment by Pokherali** [comment]
Still not having any idea. As I said I am newbie to github. Can you @agnostic-apollo please write down the needed steps. Thanks.

**Comment by TEFLIS** [comment]
v

**Comment by XOXO045** [comment]
Vh

**Comment by k53a48** [comment]
I'm getting 268 Mbit increased size,🤖❤️‍🔥🦾

**Comment by tofa2050** [comment]
> Hello, i sticked with the play store version of termux until last week, mainly because i didn't know about the movement to f-droid. I tried installing the latest f-droid version but suddenly noticed that the clean installation of termux now weight 182MB, i remembered the play store version to be a lot smaller when i initially installed it, so i got i back to check, and in fact the latest play store version was just 82MB on a fresh install. Is this normal? Are the play store apk threaded in some ways that make the final installation lighter? Initially i tought that could be for the different arch versions inside the apk, checking the f-droid downloaded apk the lib folder contains all the different arch versions of the main libraries, this used to be different when the app was on play store? There is something that can be done or all this additional 100MB actually added content that cannot be reduced? Thanks
