### ISSUE TITLE
chromeos: ctrl+w closes window

### ISSUE THREAD

**Issue by philips** [termux/termux-app#216]
ctrl+w closes windows under ChromeOS. It would be nice to figure out how to disable that behavior so emacs keybindings in bash work.

**Comment by philips** [comment]
Seems the ChromeOS team knows about it but has no workaround: https://www.reddit.com/r/chromeos/comments/53plbc/temporarily_disabling_chrome_keyboard_shortcuts/

**Comment by philips** [comment]
cc @denniskempin

**Comment by gordol** [comment]
i think this can be closed...

ctrl + w does not close termux when ran under chrome OS currently: 

Version 61.0.3163.90 (Official Build) beta (64-bit)
Chromebook PIxel LS

**Comment by robzon** [comment]
Great news! Maybe we should wait until things work in stable though?

**Comment by denniskempin** [comment]
This issue is not really within the realm of control for termux. ChromeOS
consumes some keyboard shortcuts at the system level and won't expose them
to apps.

We have recently added support for Android apps to consume most shortcuts
and fall back to ChromeOS behavior if the key goes unhandled. This allows
access to shortcuts such as ctrl-w. So the issue should be fixed from now
on.
Feel free to file a bug at crbug.com if you run into related issues!

**Comment by philips** [comment]
Confirmed that my chromebook flip running beta can do Ctrl + W.
