### ISSUE TITLE
Unable to install bootstrap

### ISSUE THREAD

**Issue by Ftwrr** [termux/termux-app#2168]
![Screenshot_2021-07-08-02-09-08-64_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/76021496/124808461-8df7a080-df91-11eb-9fbe-1d896dedd9b6.jpg)

**Comment by agnostic-apollo** [comment]
So I tested it out and created a work profile in android 10 rooted avd and then ran `/sbin/su -mm -c mount /data/user/10/com.termux /data/data/com.termux` after removing the primary user check and managed to get termux working in the work profile as well. I didn't test much, but `apt` worked, but `am` didn't, but if someone has root, then `am` could be usable too. The `mount` command was done in the global namespace which broke the primary user termux since it should be done in the right namespace normally, but that would have required changes or time and possibly magisk manager to be installed in work profile as well. Unmount can be done with `/sbin/su -mm -c umount /data/data/com.termux`.

>Alternate way is to check write access to $PREFIX
>You can't rely on /data/user/150/

Yeah, checking for `/data/data/com.termux/files` was enough in my tests.

Basically, its possible to add restricted support for multiple users for rooted users or where bind mount is done by default by the OS like in Samsung's case. I didn't add that support yet since that would require more time, cause users should be shown a prompt for that and if they want to accept the risks, also a shared preference for the choice and possibly a warning in termux settings about the restricted termux, and that @termux won't be obligated to provide much support for broken stuff.

As for current issue, @Ftwrr still hasn't sent the output for `stat /data/data/com.termux` so still not sure why its failing on their device. The latest [debug build](https://github.com/termux/termux-app/actions/runs/1017820181) has added the call for `getFilesDir()`, so if missing directory is the issue, hopefully it should work.

The build will also show the secondary user/work profile info on bootstrap installation failure. Note that `USER_ID` and `/data/user/<id>` are different even though its `/data/user/0` for primary user `0`.

### Secondary User

![Secondary Test User](https://user-images.githubusercontent.com/31106828/125161099-db465e80-e199-11eb-94ca-f5c369a1b28a.png)

### Work Profile

![Island Profile](https://user-images.githubusercontent.com/31106828/125161106-e4373000-e199-11eb-92e0-c486c37000a5.png)

**Comment by agnostic-apollo** [comment]
Looking more closely into aosp code, `/data/user/0/com.termux` or `/data/data/com.termux` would not be created by a call to [`Context.getFilesDir()`](https://cs.android.com/android/platform/superproject/+/android-11.0.0_r1:frameworks/base/core/java/android/app/ContextImpl.java;l=711). It gets the data directory file by calling [`getDataDir()`](https://cs.android.com/android/platform/superproject/+/android-11.0.0_r1:frameworks/base/core/java/android/app/ContextImpl.java;l=2523) which would actually just log an exception if the data directory is not `null` and doesn't exist and is being run by the system user, without actually creating it. If its `null`, then an exception will be thrown, but that likely doesn't apply in our case. The [`ensurePrivateDirExists()`](https://cs.android.com/android/platform/superproject/+/android-11.0.0_r1:frameworks/base/core/java/android/app/ContextImpl.java;l=668) wouldn't create it either since it makes the `mkdir` syscall only, which wouldn't create the parent directories of `files`. I checked and deleted the data directory with `root` after installing and running an example app and then called `getFilesDir()` and it logged as expected `Failed to ensure /data/user/0/<package_name>/files: mkdir failed: ENOENT (No such file or directory)`. The data directory is not necessary for app to run and is normally created by android on install or update and not on every app start. So missing directory issue wouldn't be fixed by the call.

**Comment by Saudi43** [comment]
اي

في الأربعاء، ١٤ يوليو ٢٠٢١ ١٠:٣٤ ص agnostic-apollo ***@***.***>
كتب:

**Comment by agnostic-apollo** [comment]
Another potential reason for failure could be that the OP's android creates the `/data/user/0/com.termux` directory and not the symlink from `/data/user/0` to `/data/data`, since `Context.getFilesDir()` returns `/data/user/0/com.termux`, which is what apps are supposed to use. In that case, official termux likely can't be used on the device (without root).

**Comment by gitblogman** [comment]
> @Ftwrr it would be better if you posted the full error so that I can see the full path and is it always the same path or different every time?
> 
> However, also try the debug build apk for `v0.117` and see if it works. I attempted to fix it with termux/termux-app@dc8bdfe.
> 
> https://github.com/termux/termux-app/releases/tag/v0.117
> 
> You also need to uninstall termux and all plugins you have already installed from F-Droid before installing debug build.
> 
> https://github.com/termux/termux-app#installation

Man this link only shows the debug build apk but unable to download any plz help

**Comment by agnostic-apollo** [comment]
Install `v0.118.0+` and post errors if any.

**Comment by Grimler91** [comment]
@BlackKDX 0.118+ (i.e. 0.119) is not released yet. Install from github in the meanwhile, see wiki: https://github.com/termux/termux-app/wiki/Termux-on-android-5-or-6

**Comment by BlackKDX** [comment]
Thank you my friend

**Comment by w311ang** [comment]
> The `mount` command was done in the global namespace which broke the primary user termux since it should be done in the right namespace normally,

for https://github.com/termux/termux-app/issues/2168#issuecomment-877621546. You can mount it for Termux in other users separately, I used this module https://github.com/HuskyDG/magic_proc_monitor

**Comment by realyukii** [comment]
I have same issue however I can't provide any logs/screenshot due to:
- it's from tv box / stb
- I can't adb into it, the usb isn't detected and no adb over wifi feature (it's android 10)
- thus I also can't scrcpy into it

it have internet connection, though.
