### ISSUE TITLE
Add officially supported Arch Linux version Termux (Build flavor)

### ISSUE THREAD

**Issue by stevenleeS0ht** [termux/termux-app#2176]
Currently, There is some unofficial support for `archlinux` on `Termux`.

But it is a little bit buggy and take a lot of time to setup.

And the repo of Arch variant of `Termux` is usually from `ArchLinux ARM`.

**Since `Termux` use `build.sh`  and Arch use `PKGBUILD` , both of them are shell script and have similar structure and procedure flow.**

As a result, write a program to mapping the `build.sh` to `PKGBUILD`  (just change the function name) won't be difficult.

And then use `makepkg` of `pacman` to build according to the generated `PKGBUILD` file.

Because a lot of computer hackers and geeks use Arch Linux, and Termux is intend for hackers and geeks.

As a result, add official support on Arch Linux would make Termux more popular.

**Comment by stevenleeS0ht** [comment]
@fornwall , is this realistic?

**Comment by xeffyr** [comment]
>  is this realistic

Will be realistic as soon as everyone of our dev team will consider current approach with our build system flawed and non-viable for support in future. Package manager change is possible, but pointless and will require to **shut down** existing apt repositories in order to free space for the new ones.

If you are talking about using Arch distro as Termux base, then this becomes problematic:
* Libc and toolchain. Those needs to be patched, so programs can run in Termux natively without proot. *There is a one simple question: who will maintain that? - That's a question for which I always ask when a custom libc or related stuff is requested. Never got an answer.*
* Rootfs. We have choices: prefix like in current implementation or `proot`. Each has pros and cons. Proot is not stable, applies some performace penalty and doesn't resolve all issues with rootless chroot. Though it has potential to resolve https://github.com/termux/termux-app/issues/2155, can be used to run software from normal Linux distributions, etc.

\- These are only basic issues to consider. Typicaly there are more.

Do you think that presence of `makepkg` will resolve all possible issues with compilation? Nope, if Termux will not change its base. Most of software compilation issues arise from use of NDK system root instead of traditional GNU libc and Linux headers.

https://github.com/termux/termux-packages has support for building packages on device, if you need a way for making custom packages.

There is [UserLAnd](https://userland.tech/) which accomplishes your request (use Arch as environment). So why Termux should become its clone? It will be literally same, with few application interface differences.

Just for note, Termux is a terminal emulator application with extra packages.

> As a result, add official support on Arch Linux would make Termux more popular.

If Termux will use Arch packages, it won't receive official Arch support anyway. Packages are needed to be either executed under proot or patched for Anroid NDK and prefix.
