### ISSUE TITLE
keep app data media

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-app#2215]
**Feature description**

Keep app data media directories after uninstalling Termux.

Can Termux users have the option to keep app data when uninstalling termux.apk? Termux users would then have the option of keeping app data in Android/{data,media}/com.termux after uninstalling Termux from Android.

**Reference implementation**

Does another app/terminal emulator have this feature?
zoom.apk

Provide links to more background information.
https://zoom.us/
https://zoom.us/client/latest/zoom.apk 

When uninstalling zoom.apk the user has the option to keep app data:
![Screenshot_20210809-125246](https://user-images.githubusercontent.com/27742457/128745057-58dc5c2b-867e-476c-a08f-a29856920f1c.png)

**Comment by xeffyr** [comment]
This will be possible only once Termux will switch to the latest target SDK. Since latest target SDK introduced big problems with packages (#1072), this can't be done currently.

**Comment by agnostic-apollo** [comment]
Unfortunately, no. I decided against doing that due to a [bug in android 10](https://gist.github.com/agnostic-apollo/58def38fdb1c90563454974108ae52df). Until enough users on different manufacturer devices report that the bug does not exist on their phone, this won't be added.

@xeffyr only `compileSdkVersion` needs to be bumped, not `targetSdkVersion`.

**Comment by SDRausty** [comment]
> Since latest target SDK introduced big problems with packages (#1072), this can't be done currently.

Thank you for your quick replies; Do you think future versions of the SDK will continue to harbor this bug?

**Comment by agnostic-apollo** [comment]
@xeffyr and I are talking about separate problems. The ones he mentions does not apply to your question. Read the post I sent, bug has been fixed on android 11 in AOSP and possibly some devices on android 10. But since F-Droid users will not be able to uninstall termux app once installed other than with adb/root, this can't be added. Note that even F-Droid app by default is not a system privileged app like play store on devices, and shows the uninstall prompt instead of directly uninstalling in background, so will trigger bug.
