### ISSUE TITLE
Build termux as a system app

### ISSUE THREAD

**Issue by TREYWANGCQU** [termux/termux-app#2222]
Hello,  Where could I find any wiki about building process or libs? I wanna rebuild termux as a system app.

Thanks a lot

**Comment by xeffyr** [comment]
What do you mean by system app? Do you have any issues installing it into `/system/app/Termux/Termux.apk` with extracting libs into `/system/app/Termux/lib/arm` and `/system/app/Termux/lib/arm64`

**Comment by TREYWANGCQU** [comment]
> What do you mean by system app? Do you have any issues installing it into `/system/app/Termux/Termux.apk` with extracting libs into `/system/app/Termux/lib/arm` and `/system/app/Termux/lib/arm64` ?

Cool. I'd add the libs.
The main idea is as following:
when termux is a  system app, I could
- logout rooted state
- still modify hosts to block **Ads**;
- manage apps;
- et al.

**Comment by agnostic-apollo** [comment]
What android version are you on?

>still modify hosts to block Ads;

How do you plan on doing this?

>manage apps;

You would need to add `android.permission.INSTALL_PACKAGES` and `android.permission.DELETE_PACKAGES` permission to termux `AndroidManifest.xml` and install app as system privileged in `/system/priv-app`. But even then `pm install` may not work since supposed to use java. It's failing with `Error: java.lang.NullPointerException` on my android `7` but could be a device specific issue, works with root.

Using a [`sudo`](https://github.com/agnostic-apollo/sudo) interactive shell or running scripts with it is easy enough anyways. Keeps `HOME` separate too.

**Comment by fuyasu** [comment]
Pls i need hack facebook termux  easy command

**Comment by TREYWANGCQU** [comment]
> What android version are you on?
> 
> > still modify hosts to block Ads;
> 
> How do you plan on doing this?
> 
> > manage apps;
> 
> You would need to add `android.permission.INSTALL_PACKAGES` and `android.permission.DELETE_PACKAGES` permission to termux `AndroidManifest.xml` and install app as system privileged in `/system/priv-app`. But even then `pm install` may not work since supposed to use java. It's failing with `Error: java.lang.NullPointerException` on my android `7` but could be a device specific issue, works with root.
> 
> Using a [`sudo`](https://github.com/agnostic-apollo/sudo) interactive shell or running scripts with it is easy enough anyways. Keeps `HOME` separate too.

**Comment by agnostic-apollo** [comment]
UID would still be for an app even with higher permissions. You can't make it a `system` user app with current termux exec problems as per #2189

You can also get path with `adb shell pm path com.termux | cut -d: -f2-`
