### ISSUE TITLE
[Bug]: Restarting phone and probably putting it on an sdcard cause this error

### ISSUE THREAD

**Issue by Minecrafter11231** [termux/termux-app#2238]
## Transcript

```
exec("/data/data/com.termux/files/usr/bin/login"): Permission denied

[Process completed (code 1) - press Enter]
```

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_CODE**: `114`  
**TARGET_SDK**: `28`  
**IS_DEBUG_BUILD**: `false`    
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.14.141-20440625`  
**SDK_INT**: `29`  
**RELEASE**: `10`  
**ID**: `QP1A.190711.020`  
**DISPLAY**: `QP1A.190711.020.A013GXXU4AUG5`  
**INCREMENTAL**: `A013GXXU4AUG5`  
**SECURITY_PATCH**: `2021-07-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  
**APK_RELEASE**: `F-Droid`

### Steps to reproduce the behavior.

Restart your device open termux and it if it didn't
pop up you probably need to put termux on an sdcard

### What is the expected behavior?

i exepct it to open and run fine

### Hardware

**MANUFACTURER**: `samsung`  
**BRAND**: `samsung`  
**MODEL**: `SM-A013G`  
**PRODUCT**: `a01corextc`  
**BOARD**: `k39tv1_bsp_1g_titan`  
**HARDWARE**: `mt6739`  
**DEVICE**: `a01core`  
**SUPPORTED_ABIS**: `armeabi-v7a, armeabi`  

**VERSION_NAME**: `0.114`

**Comment by agnostic-apollo** [comment]
Termux cannot be installed on sd card.

**Comment by xeffyr** [comment]
Some devices put it on sdcard automatically (not sure, but probably there were reports on this), regardless of AndroidManifest configuration.

**Comment by agnostic-apollo** [comment]
@Grimler91 said a guy who reported on email confirmed that installing `v0.117` on sd card was failing bootstrap installation.

```
Creating directory file at path "/data/data/com.termux/files/usr-staging/bin" failed.
```

Android shouldn't allow it to install on sdcard due to [`installLocation="internalOnly"`](https://developer.android.com/guide/topics/data/install-location) in [`AndroidManifest.xml`](https://github.com/termux/termux-app/blob/v0.117/app/src/main/AndroidManifest.xml#L5) but since it is, likely reason is that termux files dir `/data/data/com.termux/files` gets changed too or access is lost, although only apk install path should change, not data path. I am not sure of the real reason.

Anyway, 24ea83d6 (not yet released) should help with finding real reason. If someone wants to test now instead of waiting for next release, uninstall Termux app and ALL plugins installed from F-Droid as per instructions at https://github.com/termux/termux-app#Installation and then install universal debug apk from https://github.com/termux/termux-app/actions/runs/1153239976. Then send the new report generated which will have more info to debug the issue.

**Comment by Grimler91** [comment]
> @Grimler91 said a guy who reported on email confirmed that installing v0.117 on sd card was failing bootstrap installation.

The person wrote:

> I has used Termux on the SD Card but i changed to the internal storage and after it works correctly

Not sure if he had manually selected to install to ext sdcard somehow or if android selected it for him

**Comment by suhan-paradkar** [comment]
> Not sure if he had manually selected to install to ext sdcard somehow or if android selected it for him

Well.. some vendors like Samsung allow apps to be moved to sdcard regardless of app's manifest...
This option needs to be enabled in developer's options and then the app needs to be moved to sdcard

**Comment by xeffyr** [comment]
Yes, but that's still unclear what is actually with OPs case.

Here is how this option looks like:
![Screenshot_20210823-183945_Settings](https://user-images.githubusercontent.com/25881154/130477597-8883b560-a7cf-495d-a3e7-993d3ec6074e.jpg)

If enabled, I can move Termux to external SD card freely:
![Screenshot_20210823-184022_Settings](https://user-images.githubusercontent.com/25881154/130477648-afcdd19b-7c4d-4d10-a8b5-ffb27cad024f.jpg)

![Screenshot_20210823-184032_Settings](https://user-images.githubusercontent.com/25881154/130477673-5fa57b0c-90d6-4928-8612-660029f10343.jpg)

I have moved it, but it still works because only APK file and .so libraries are being moved. Android moves application by creating a fixed-size encrypted EXT4 volume in `/storage/XXXX-XXXX/.android_secure`. No prefix content is actually being moved.
![Screenshot_20210823-184211_Termux](https://user-images.githubusercontent.com/25881154/130477687-d7cf5a11-5beb-4714-b3fe-db72f4d6a3c0.jpg)

Besides standard application moving functionality, there are other ways which can move data directory as well, like link2sd. They require root and also can lead to whatever issues (ownership + SELinux) when application was reinstalled or something wrong happened on device reboot.

**Comment by agnostic-apollo** [comment]
Install `v0.118.0+` and post errors if any.
