### ISSUE TITLE
[Bug]: 0 sessions

### ISSUE THREAD

**Issue by roman542** [termux/termux-app#2251]
### Problem description

Glitch causes termux to not close

### Steps to reproduce the behavior.

1. Start
2. Acquire wakelock
3. Exit (from the terminal)

### What is the expected behavior?

Exit without permanent notification

### System information

* Termux application version: 0.117 (fdroid)

**Comment by agnostic-apollo** [comment]
That is expected behaviour. People have daemons runnings in the background but not necessarily a terminal session.

https://github.com/termux/termux-app/blob/v0.108/app/src/main/java/com/termux/app/TermuxService.java#L334

Use exit button in notification instead of just typing `exit` if you want to release wakelock and dismiss notification.
