### ISSUE TITLE
[Bug]: Some terminal sequences may not be parsed properly

### ISSUE THREAD

**Issue by buttaface** [termux/termux-app#2272]
### Problem description

The kakoune editor package was recently updated and no longer works well in Termux because of visual glitches, even when running the linux version remotely over ssh. I reported the issue at mawww/kakoune#4339 and was told the problem is likely related to Termux not handling some terminal formatting sequences correctly, as kakoune v2021.08.28 replaced its ncurses dependency "with a custom terminal escape sequence backend."

### Steps to reproduce the behavior.

Open any file in kakoune v2021.08.28, even when running over ssh in linux and viewed in Termux.

### What is the expected behavior?

Proper formatting without certain lines being randomly highlighted in white, which changes when scrolling or if the on-screen keyboard pops up or down.

### System information

* Termux application version: 0.83 - 0.117
* Android OS version: 6-11
* Device model: Samsung

**Comment by buttaface** [comment]
Thanks, man, I've been stuck using the prior ncurses version of kakoune until this is fixed. Unfortunately, I can't test it out as I don't have any extra devices for the next week, so if you think it works now, please push it into an official release and I will try it then.

**Comment by agnostic-apollo** [comment]
You are welcome. Yeah, seems to be working as per my tests and have already pushed it to `master` so should be available in next release.

**Comment by korakinos** [comment]
For anybody else confused why they still encounter this bug: There hasn't been a new release since the issue was closed, so in order to get the fix, you need to use a development build. You can get one from Github actions:

https://github.com/termux/termux-app/actions/workflows/debug_build.yml

(I also reinstalled my termux plugins, termux-styling and termux-api, from Github actions because the F-Droid app did not let me combine their released versions with the dev build of termux-app.)

See also this discussion on why there is no new release yet:

https://github.com/termux/termux-app/discussions/3213
