### ISSUE TITLE
[Feature]: Some features for package companion apps.

### ISSUE THREAD

**Issue by twaik** [termux/termux-app#2292]
### Feature description

1. It is possible to implement companion apps for Termux packages and it is allowed to send `RUN_COMMAND` intent to `termux-app` when external application got permission from user and there is `allow-external-apps` flag in `~/.termux/termux.properties`. But what if we want to install package which requires external app but does not want to touch `termux-app`'s security properties? I think we can export one more `RunCommandService` which will be able to communicate with caller app using `AIDL/Binder`, it is possible to use existing intent parser. We can store public key of companion application in build.sh of a package (and maybe other info like one or more GP/F-Droid/direct download `URL`'s to download the app if it is not embedded to a package, paths of binaries allowed to be executed, etc.) and then verify app connection using `Binder.getCallingUid()` and Android's `PackageManager` ([example](https://stackoverflow.com/a/3825410/4984168). We can call it "trusted companion" or "trusted app".
2. It would be wonderful to be able to connect/bind sockets using ContentProvider. You can try check if there is `s` in `mode` and connect to a given path or if there are `st` bind there instead of connecting. I have doubts if it can be implmented without bumping minSdkVersion (but anyway it can be implemented using JNI). It will allow us to create/share sockets/files without using hacks/tricks.

**Comment by agnostic-apollo** [comment]
>But what if we want to install package which requires external app but does not want to touch termux-app's security properties?

External apps should not be allowed to modify termux properties. The `RunCommand` service and `termux-tasker` both require `RUN_COMMAND` permission requested by external app and then additionally requires user to enable `allow-external-apps` internally from within the app as well. That should stay, since at least `RUN_COMMAND` permission is guaranteed by the OS itself and should be safe. The `allow-external-apps` provides extra protection and more control to the user, and also prevents access in case user was fooled into granting permission to a malicious app. That design shouldn't change even if some `AIDL/Binder` or socket sharing mechanism is implemented.

I did write about allowed binaries/commands in https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent#privacy, but of course that still would be protected with dual protections above.

Why do you want to bypass `allow-external-apps`? Things like `Binder.getCallingUid()` and `ContentProvider.getCallingPackage()` would only be safe as long as a malicious app is not using a "trusted" package name itself. Lot of forkers/copy cats out there.

>It would be wonderful to be able to connect/bind sockets using ContentProvider.

If this and other stuff needs to be implemented, then send a pull request and we can see if it can be merged, depending on security practices.

**Comment by twaik** [comment]
> External apps should not be allowed to modify termux properties.

That is what I mean. We can specify paths of binaries allowed to be executed by specific application in `build.sh`. This way other external apps will not be able to fire commands and companion application will be able to do what it needs to do. `AIDL/Binder` as well as `PendingIntent` can be used to verify application's identity.

> would only be safe as long as a malicious app is not using a "trusted" package name itself

That is why I suggested to use public key verification.

> If this and other stuff needs to be implemented, then send a pull request and we can see if it can be merged, depending on security practices.

I can try but I do not think I am good enough to write something this like.

**Comment by agnostic-apollo** [comment]
>We can specify paths of binaries allowed to be executed by specific application in build.sh

It would depend on what those commands are capable of. With `RUN_COMMAND` permission and `allow-external-app`, anything can be done and they take only a couple of minutes to configure. When/if `termux.properties` write support is implemented, then `allow-external-apps` should be togglable in termux settings as well, even though its a one liner command now and not really hard, and shell users should be used to shell commands. If instead of anything, users/you want a more fine grained control to allow only specific commands via intents, that should be possible to implement, but still that must only be allowed after both internal and external permissions are enabled and by default access to any and all apps should not be allowed, regardless of "trusted apps". You haven't given any reason for why enabling internal/external permissions is such a burden that it should be bypassed for said trusted apps.

>That is why I suggested to use public key verification.

Where will the trusted app store the private key? Will it not be open source? The private key could just be used by any malicious app using the trusted app package name.

> I can try but I do not think I am good enough to write something like this.

Didn't you say you already were working on something? And I haven't implemented aidl myself, never needed it, and it will most likely be lot of work and I don't have time to learn and implement currently, specially considering I don't know what exactly needs to be implemented since I don't know how `termux-x11` works in detail, or will any suggested design even work or would be an ideal solution for an `x11` app. And even after next release, lot of higher priority work needs to be done. If you want me to look into it for `termux-x11` to be usable for non-termux apps, then you will have to wait, and I probably won't be able to do it anytime soon. However, if something small needs to be done in `ContentProvider`, like `s` mode support, then that can be implemented/merged earlier if you can confirm its working.

**Comment by xeffyr** [comment]
IMO, the [proposal](https://github.com/termux/termux-app/issues/2292#issue-1005686053) suggests to implement a door for acquiring the `RUN_COMMAND` and `allow-external-app` non-interactively, with potential of extending scope to user-defined applications.

Otherwise I do not see any reason why this can be useful. We already can use shared user id and one signature key for main app and add-ons.

If that's all about making Termux:X11 app to be compatible with Termux, then there are 2 variants:
* Releasing it on F-Droid.
* Introducing official (non-debug) releases on GitHub.

In any case, access to app signature private key must be limited, e.g. it will be accessible only by its creator and GitHub actions like done with "auto builds" GPG key for packages. But I guess that would break the whole idea of these "trusted' applications. Signature keys accessible by outside collaborators are no way, since they are posses high risk of leaking or misuse (i.e. signing custom apps).

> Where will the trusted app store the private key? Will it not be open source? The private key could just be used by any malicious app using the trusted app package name.

I guess that's about public key of certificate used for signing the apk file.

**Comment by agnostic-apollo** [comment]
If public key is of apk signing, then that has issues too. If app is FOSS and published via Github/Gitlab, then keystore can be encoded as `base64` and could be added to Github/Gitlab secrects by the maintainer but that doesn't prevent the key from being leaked from the maintainer's local system and would be an issue for non-FOSS too. If F-Droid publishes the app too, then it will have a separate keystore which maintainer doesn't have access to (unless custom F-Droid server), so two public keys will need to be added. Using apk signature as security makes sense when used with `sharedUserId`, since app itself will have the same signature as plugins and android will protect against misuse, but has issues with external apps if keystore can't be expertly protected.

Also when targetting sdk `11`, to [get signature](https://github.com/termux/termux-app/blob/dcedf394343f97284359f33a52e264089a335751/termux-shared/src/main/java/com/termux/shared/packages/PackageUtils.java#L179), each app will need to be to `AndroidManifest` as well due to [package visibility changes](https://github.com/termux/termux-app/wiki/Termux-Libraries#target-sdk-30-package-visibility).

**Comment by twaik** [comment]
@agnostic-apollo Looks like I have a plan of bypassing this, but I need your permission. 
1. Package registers a program as a viewer for a specific mime type.
2. Android app sends `Intent.ACTION_SEND` with a URI of Unix socket. Or our of nothing, it does not matter.
3. Termux receives it and executes xdg-open. Registered viewer starts my executable and it connects with my external app and does something I need.

**Comment by xeffyr** [comment]
`xdg-open` in Termux is a symlink to `termux-open`, so basically you are proposing to reflect `ACTION_SEND` onto another application.

`Android app` (sends uri) --> `Termux: xdg-open $uri` (sends uri) -->  `Viewer: view $uri`

Termux is not necessary in this case.

***

There no plans to drop symlink "xdg-open" in favor of traditional one from Linux distributions.

**Comment by twaik** [comment]
Yeah, you are right. Looks like there is no option of triggering my app from a companion app. Thanks.
