### ISSUE TITLE
[Bug]: Magisk Hide Magisk App

### ISSUE THREAD

**Issue by MedzikUser** [termux/termux-app#2301]
### Problem description

When I have root with magisk and hidden applications, any command with sudo or su gives me Permission Denied and when I have regular applications it works fine

### Steps to reproduce the behavior.

When I have root with magisk and hidden applications, any command with sudo or su gives me Permission Denied and when I have regular applications it works fine

### System information

* Termux application version: 0.117
* Android OS version: 11 (cutom rom lineageos 18.1 root)
* Device model: E6853

**Comment by agnostic-apollo** [comment]
The `termux-app` does not provide support for Magisk issues. Even magisk doesn't officially support MagiskHide anymore. Check https://github.com/topjohnwu/Magisk/issues/1152

If errors are found to be caused by termux, then this issue can be reopened if you provide proof of it.

You should probably check logcat over adb to see if magisk is logging reasons for denials.
