### ISSUE TITLE
[Bug]: can't install termux from f-droid

### ISSUE THREAD

**Issue by seyo-IV** [termux/termux-app#2326]
### Problem description

Installing termux gives an unknown error.

### Steps to reproduce the behavior.

Install termux from f-droid app.

### What is the expected behavior?

Successful install.

### System information

* Termux application version: 0.117
* Android OS version: 11
* Device model:
OnePlus 7t

**Comment by xeffyr** [comment]
https://github.com/termux/termux-app#installation

**Comment by egeres** [comment]
I can't seem to install termux:boot from f-droid. I get a pop-up notification from google play protect that reads "harmful app blocked", and the version of termux:boot from the store is 4 years old. Even if I press "continue" and install I get an error  that reads "Failed to install due to an unknown error". My system specs are:

- Termux application version: 0.118
- Android OS version: 12
- Device model: Galaxy Note 10+
