### ISSUE TITLE
Termux API

### ISSUE THREAD

**Issue by GabrielTK** [termux/termux-app#236]
Good Evening,
Just a quick suggestion, why don't you expose an API so other apps can start termux sessions with specifoc binaries?
Thank you,
Gabriel

**Comment by GabrielTK** [comment]
Like this: https://github.com/jackpal/Android-Terminal-Emulator/wiki/Launching-Terminal-Emulator-for-Android-from-another-App

**Comment by Neo-Oli** [comment]
You can do this with Termux:Widget for apps that can handle shortcuts and you can do it with Termux:Task for Tasker (and Tasker plugin compatible software). But you can only launch scripts in a specific folder. This is for security reasons, as otherwise a rogue app could launch arbitrary Tasker commands (and for example, steal your ssh and gnupg keys)

**Comment by xeffyr** [comment]
Related to https://github.com/termux/termux-app/issues/804.
