### ISSUE TITLE
[Bug]: Cannot execute latest nodejs binary

### ISSUE THREAD

**Issue by DeepzUa** [termux/termux-app#2389]
### Problem description

When upgrade to latest version nodejs (17.0.0), cannot run binnary

~ $ node
CANNOT LINK EXECUTABLE "node": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/bin/node"...

### Steps to reproduce the behavior.

Upgrade to new version nodejs

### System information

* Termux application version: 0.116
* Android OS version: 11
* Device model:
Moto g(9) plus

**Comment by Grimler91** [comment]
Upgrade your packages, `pkg upgr`

**Comment by CarlosEX** [comment]
## Erro..

Checking availability of current mirror: ok
Get:1 https://grimler.se/termux-packages-24 stable InRelease [16.8 kB]
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease                                                 Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:1 https://grimler.se/termux-packages-24 stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B0076E490B71616B
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  403  Forbidden
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release                                                403  Forbidden
Reading package lists... Done
W: GPG error: https://grimler.se/termux-packages-24 stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B0076E490B71616B
E: The repository 'https://grimler.se/termux-packages-24 stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.                                                  N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.       N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by thunder-coding** [comment]
@CarlosEX See #2067
