### ISSUE TITLE
[Bug]: Android 12 update broke scroll up

### ISSUE THREAD

**Issue by sepisuomi** [termux/termux-app#2400]
### Problem description

I recently updated to Android 12. Now when I try to scroll up in the terminal by swiping up, it just does the equivalent of pressing the up arrow, so it shows previously typed commands. Basically, I can't see previously printed output anymore, having to pipe into less all the time.

### Steps to reproduce the behavior.

Open termux, try to swipe up, you just get older commands typed in.

### What is the expected behavior?

Show previously printed commands.

### System information

* Termux application version: 0.117
* Android OS version: 12
* Device model: Google Pixel 5A

**Comment by agnostic-apollo** [comment]
Working fine on emulator with mouse click scroll.

Pinging @xeffyr who has a real device.

Also go in termux settings and set log level to verbose and enable terminal view key logging, then run `logcat` command and scroll up and then `Ctrl+C` to stop it and then post transcript.

**Comment by sepisuomi** [comment]
Thanks for your quick reply. I reset termux and now I can't replicate it; if it happens again I will follow your instructions and post the transcript.

**Comment by xeffyr** [comment]
> Pinging @xeffyr who has a real device.

Never had such issue.

> I reset termux and now I can't replicate it;

Basically you need to just call `reset` (maybe `stty sane` will also work) command or tap button `Reset` in context menu. The described issue happens when some program was either terminated abnormally or in other way messed up terminal settings.

This is not Termux bug, but just how terminal works. Note that similar behavior where scrolling acts as mouse wheel equivalent is expected behavior when using programs like `vim` or `tmux`.
