### ISSUE TITLE
Update the version for devices with older versions of Android

### ISSUE THREAD

**Issue by codingwith3dv** [termux/termux-app#2410]
### Feature description

Please update the app for older versions of Android. The last update for Android 6 ( according to my device ) was done at 2019. Many useful packages are not available in the older versions. 

### Additional information

Example:

the older version only supports node 12.x.x

Hence, development is very hard since we have to make the source backward-compatible

**Comment by Grimler91** [comment]
Feel free to volunteer and update and maintain packages for these old android versions. Support was dropped in the [beginning of 2020](https://github.com/termux/termux-packages/issues/4467), and [announced around a year before](https://github.com/termux/termux-packages/issues/2874). 

Since none of the current maintainers have android 5 or 6 devices (AFAIK) it is highly unlikely that anyone will want to spend time on porting packages for these old android versions.

**Comment by codingwith3dv** [comment]
Oh i see. So does that mean there won't be further updates for older versions? 😞

**Comment by Grimler91** [comment]
Well, not from me at least.

Note that if you are using termux on android 5 or 6 you will want to change the game- and science-repo urls to point to github instead, as bintray repos are down. See README in https://github.com/termux/game-packages-21-bin and https://github.com/termux/science-packages-21-bin

**Comment by codingwith3dv** [comment]
Oh alright! 👍 Anyways thank you so much for your reply! I Appreciate it!
