### ISSUE TITLE
Termux not working with form csrf token in laravel project

### ISSUE THREAD

**Issue by bhiantara** [termux/termux-app#2431]
### Feature description

create project laravel using termux its work fine but have problem with csrf token in input form, so i'm trying to inspect element and see csrf token already inside in form but after submit form, browser will be direct to expired page that because csrf token. how can i solve this problem?

### Additional information

-

**Comment by Grimler91** [comment]
Use the [bug report template](https://github.com/termux/termux-packages/issues/new?assignees=&labels=bug+report&template=01-bug-report.yml&title=%5BBug%5D%3A+). 

Note that:

* laravel is not a [termux package](https://github.com/termux/termux-packages/tree/master/packages/laravel), I have no idea what it is
* You haven't steps for reproducing the issue, or why you think this is a termux issue rather than an issue with "laravel"
* You haven't provided any information about your device or termux version

**Comment by bbek18** [comment]
So how can android device works for bug haunting req
