### ISSUE TITLE
[Feature]: add storage symlinks to media folders

### ISSUE THREAD

**Issue by Efreak** [termux/termux-app#2481]
### Feature description

Please add symlinks to `/storage/emulated/0/Android/media/com.termux` and it's counterpart on sdcard, suggested names being `internal-media` and `external-media`, or replacing `shared` and `external-1` on devices that don't have access to those folders.

### Additional information

On all devices I currently use (Android 11), files in this directory can be read and written, making it an ideal location to store data in order to make it accessible to both Termux and other apps. I can download an image here, modify it with an app, and upload it in termux, all without making unnecessary copies (termux-share/termux-open/termux-storage-get).

Files in external-1 are inaccessible to other apps, as this is a private data folder.

Files in movies, music, pictures, shared, dcim, and downloads are all inaccessible due to android restrictions:

<details>
<summary>ls: cannot open directory: Permission denied</summary>

```
~/storage
✦ ❯ ls|while read ln; do stat -c $'%N\n\n' $ln; ls $ln; done
'dcim' -> '/storage/emulated/0/DCIM'
ls: cannot open directory 'dcim': Permission denied


'downloads' -> '/storage/emulated/0/Download'
ls: cannot open directory 'downloads': Permission denied


'external-1' -> '/storage/9C33-6BBD/Android/data/com.termux/files'


'external-media' -> '/storage/9C33-6BBD/Android/media/com.termux'
7-9.jpg  7.png  aw  dl.sh  humblebundle/  links.txt  sources/  termux.tar  youtube-dl/


'internal-media' -> '/storage/emulated/0/Android/media/com.termux'
githubs.txt  logcat.txt  packages.txt  places.txt     the-way  upx.out.stripped
ins          packages    pkgs          rust-bins.zip  upx.out  upx.zip


'movies' -> '/storage/emulated/0/Movies'
ls: cannot open directory 'movies': Permission denied


'music' -> '/storage/emulated/0/Music'
ls: cannot open directory 'music': Permission denied


'pictures' -> '/storage/emulated/0/Pictures'
ls: cannot open directory 'pictures': Permission denied


'shared' -> '/storage/emulated/0'
ls: cannot open directory 'shared': Permission denied


~/storage
✦ ❯
```
</details>

<details>
<summary>screenshot of Android/media/com.termux in FX</summary>

![SmartSelect_20211218-151700_FX](https://user-images.githubusercontent.com/749751/146657963-c4b2ca59-979a-4fae-9637-6c5aceb03d18.jpg)
</details>
Edit: I think the entire `media` directory is actually accessible, but putting everything in a com.termux subfolder is probably a good idea.

**Comment by nathaneltitane** [comment]
I was about to open another feature ticket describing a very similar request:

Rationale: the current $HOME/storage/ directory contents labeling makes no sense and is quite confusing even (personal experience in wrapping my head around how Termux made storage media accessible when I first started using it)

For most part, I end up removing $HOME/storage and them making new directories under $PREFIX: media and storage

I then scripted a utility that:
- links /storage/emulated/0 as $PREFIX/storage/internal
- finds external storage (i.e.: SD or other) through a 'cat /proc/mounts' knowing the default format support is either FAT or exFAT, and is labelled by android when formatted as [aA0-zZ9][-][aA0-zZ9] and links that item to $PREFIX/storage/external
- links $PREFIX/storage/internal to $PREFIX/media/internal
- links $PREFIX/storage/external to $PREFIX/media/external
- links $PREFIX/storage/external-[n] to $PREFIX/media/external-[n] (when detected)

We know that Termux is not to be labeled as just any other GNU/Linux based distribution, nor is it not, but there are some directory use cases that make sense, such as this one and would make some newcomers' lives easier if they were implemented, as they are well-known to must GNU/Linux users that eventually flock to Termux (I would hope).

This also underlines one other thing: why does a user have to 'termux-setup-storage' rather than have Termux set it up on first login?

I hope we can come to some agreement on making this a little better for a future release :)

**Comment by nathaneltitane** [comment]
@xeffyr thoughts?

**Comment by Grimler91** [comment]
Sounds good, some thoughts:

$PREFIX/storage is not really standard, using $PREFIX/media/ as the main dir, and possibly linking $PREFIX/storage there might make more sense: https://tldp.org/LDP/Linux-Filesystem-Hierarchy/Linux-Filesystem-Hierarchy.pdf. 

One downside with putting the folder in $PREFIX instead of $HOME can be that newcomers "can't see" the folder, it doesn't appear in `ls` after opening a shell in home.

For backward compatibility the existing symlinks should be kept as well in any case, users might have scripts assuming `~/storage/shared` for example (could add an arg to termux-setup-storage to not create them)

> why does a user have to 'termux-setup-storage' rather than have Termux set it up on first login?
It's an optional feature, and not all users might be comfortable granting termux access to shared storage

> finds external storage (i.e.: SD or other) through a 'cat /proc/mounts' 
Seems easier to just get them through java, as done currently

**Comment by agnostic-apollo** [comment]
`$PREFIX` also isn't accessible through SAF and lot if not most users don't even know what `$PREFIX` is. Also much harder to type `$PREFIX/storage` than `~/storage` too, even though former may be more FSH compliant, but then again, it should probably be `$PREFIX/home/termux` too if we were following standards.

**Comment by nathaneltitane** [comment]
> `$PREFIX` also isn't accessible through SAF and lot if not most users don't even know what `$PREFIX` is. Also much harder to type `$PREFIX/storage` than `~/storage` too, even though former may be more FSH compliant, but then again, it should probably be `$PREFIX/home/termux` too if we were following standards.

yeah, following standards would be nice :)

**Comment by nathaneltitane** [comment]
> Sounds good, some thoughts:
> 
> $PREFIX/storage is not really standard, using $PREFIX/media/ as the main dir, and possibly linking $PREFIX/storage there might make more sense: https://tldp.org/LDP/Linux-Filesystem-Hierarchy/Linux-Filesystem-Hierarchy.pdf. 
> 
> One downside with putting the folder in $PREFIX instead of $HOME can be that newcomers "can't see" the folder, it doesn't appear in `ls` after opening a shell in home.
> 
> For backward compatibility the existing symlinks should be kept as well in any case, users might have scripts assuming `~/storage/shared` for example (could add an arg to termux-setup-storage to not create them)
> 
> > why does a user have to 'termux-setup-storage' rather than have Termux set it up on first login?
> 
> It's an optional feature, and not all users might be comfortable granting termux access to shared storage
> 
> > finds external storage (i.e.: SD or other) through a 'cat /proc/mounts' 
> 
> Seems easier to just get them through java, as done currently

in all fairness, even with the folder being placed under $HOME, it was difficult to get a handle on what it was and how to work around getting into the storage devices themselves... although that may have simply been due to the way things were labeled and some lack of clarity regarding where to find information (wiki etc).

I'm happy this suggestion seems to make sense to you 😊
