### ISSUE TITLE
[Bug]: no install

### ISSUE THREAD

**Issue by spz2020** [termux/termux-app#2483]
### Problem description

i'm install Termux in github And my open...

sh: /system/etc/mkshrc[9]: getprop: not found
android:/data/data/com.termux/files/home $

### Steps to reproduce the behavior.

install Termux in github

### System information

* Termux application version: 0.117-github
* Android OS version:7.1
* Device model:DLI-AL10

**Comment by Gurren-Joestar** [comment]
So, you mean you had an issue because you install Termux from an apk from github? Am I right?

**Comment by agnostic-apollo** [comment]
The error is from `/system/etc/mkshrc` which is sourced if `mksh` shell at `/system/bin/sh` is run. By default, `/system/bin/sh` would only be run by termux if a failsafe session is started and it automatically [adds `/system/bin` to `$PATH`](https://github.com/termux/termux-app/blob/v0.117/termux-shared/src/main/java/com/termux/shared/shell/TermuxShellUtils.java#L65) so that error should not be thrown.

Is the error from a clean install of termux from github right after bootstrap installation or have you modified termux or restored any backup or changed default shell? Have you installed termux on external sd card?

https://cs.android.com/android/platform/superproject/+/android-7.1.1_r61:external/mksh/mkshrc;l=9

**Comment by spz2020** [comment]
Is the error from a clean install of termux from github right after bootstrap installation or have you modified termux or restored any backup or changed default shell? Have you installed termux on external sd card?
not no all

**Comment by agnostic-apollo** [comment]
Can you reinstall and check again? Maybe make a screen recording like with https://f-droid.org/en/packages/com.orpheusdroid.screenrecorder/

**Comment by spz2020** [comment]
okd

**Comment by Thakordilip143** [comment]
![Uploading Screenshot_20230906-071045.png…]()

**Comment by Thakordilip143** [comment]
Aa
