### ISSUE TITLE
[Bug]: Can't switch input method correctly

### ISSUE THREAD

**Issue by ghost** [termux/termux-app#2503]
### Problem description

Termux cannot switch input mode correctly, The keyboard used is Gboard

### Steps to reproduce the behavior.

https://user-images.githubusercontent.com/83487691/147869300-583ad600-cdbc-4ac1-8b68-f2e9240c4564.mp4

### What is the expected behavior?

ls

### System information

Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.148 #1 SMP PREEMPT Thu Dec 9 02:49:28 CST 2021 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
VTR-AL00

**Comment by stareatmyname** [comment]
The issue here is that when the text input view is unfocused while it is still shown, the touch keyboard will not restore to null/password input when the text input is left. Another way to reproduce:
1. swipe left into text input view
2. click on the terminal screen, somewhere with text (or anywhere in a tui), such that the blinking cursor in the text input disappears
3. swipe right into extra keys view

If on google's keyboard, the suggestion strip will remain on screen, unlike in previous versions. Words typed into the terminal will be buffered for text prediction.

**Comment by agnostic-apollo** [comment]
@stareatmyname I can confirm this, will look into it. Thanks

**Comment by cwitte** [comment]
@stareatmyname I'm also having the same problem on a Samsung tab s7.
Is there anything I could do to help debug this?

**Comment by agnostic-apollo** [comment]
No specific need. Issue was likely caused when I fixed another bug with 2b7aa5e8. Will try fixing the above case before next release.
