### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by rfiyoy** [termux/termux-app#2617]
Hello,

I had the app installed on another phone and I used it to work remotely from the phone. One thing that I need to do is download pdfs with scp command and open them, I was able to do this through the termux-open command.

I got a new phone and when trying to do this I get an error saying "This file could not be accessed. Check your connection or make the file name shorter." 

Im using the same pdf viewer from the old phone, the files are the same ones so I don't understand what changed. Does anyone have a solution for this? 

Thanks

_Originally posted by @DanRH90 in https://github.com/termux/termux-app/discussions/2616_

**Comment by Grimler91** [comment]
Since recent termux versions you need to set `allow-external-apps = true` in ~/.termux/termux.properties for some commands like termux-open to work as before, see https://github.com/termux/termux-app/commit/dcedf394.

This was added as part of a security fix by @agnostic-apollo: https://termux.org/general/2022/02/15/termux-apps-vulnerability-disclosures.html
