### ISSUE TITLE
Termux cannot access sdcard 

### ISSUE THREAD

**Issue by urain39** [termux/termux-app#262]
Android 7.1 termux cannot access sdcard and may not have a storage device permission

安卓7.1termux不能访问sdcard，可能是没有储存设备权限

**Comment by fornwall** [comment]
Hello! See https://termux.com/storage.html about the `termux-setup-storage` command.

**Comment by gerroon** [comment]
termux-setup-storage does not work for me on Nougat, it does not do anything whatsoever when trying to write to external except getting "permission denied"

I see in the logs

"Not granting permission android.permission.WRITE_EXTERNAL_STORAGE to package com.termux because it was previously installed without"
