### ISSUE TITLE
[Feature]: su to drop privileges

### ISSUE THREAD

**Issue by luke-jr** [termux/termux-app#2681]
### Feature description

By default, Termux's `su` just prints "No su program found on this device. Termux does not supply tools for rooting, see e.g. http://www.androidcentral.com/root for information about rooting Android."

Which makes sense, but I am trying to drop from root to the Termux user, not escalate to root.

It would be nice if Termux's su could handle dropping privileges.

**Comment by agnostic-apollo** [comment]
That's not going with possible with just `su`. App contexts are complicated. I was working on a script to implement that, but likely won't be released anytime soon.

Check https://github.com/termux/termux-api/issues/402#issuecomment-904799297.

**Comment by freebrowser1** [comment]
When I need a root shell, I just enter `sudo bash` and then Magisk pops up and I confirm (you can however grant always root access to Termux), run elevated commands and then press ctrl+D to exit the root shell.
But is that what you mean ?

**Comment by luke-jr** [comment]
No. I have a root shell, and I want to lose the privileges so I'm the normal Termux user.

This is what I'm doing right now, but I have to install a C compiler...

```c
#include <assert.h>
#include <sys/types.h>
#include <unistd.h>
#include <grp.h>

int main() {
        const gid_t groups[] = {10535, 3003, 9997, 20535, 50535};
        assert(0 == setgroups(sizeof(groups)/sizeof(*groups), groups));
        assert(0 == setgid(10535));
        assert(0 == setuid(10535));
        const char *argv[] = {"bash", "--login", NULL};
        execvp("/data/data/com.termux/files/usr/bin/bash", argv);
        assert(0);
}
```

**Comment by luke-jr** [comment]
(Also, I don't want to install Magisk or root my phone...)

**Comment by agnostic-apollo** [comment]
> Also, I don't want to install Magisk or root my phone

How do you get a root shell without doing that? Are you using vulnerabilities?

And you can run termux commands from root with `RUN_COMMAND` intent.

.https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent

**Comment by luke-jr** [comment]
>How do you get a root shell without doing that? Are you using vulnerabilities?

No, just "Rooted debugging" (ADB).

>And you can run termux commands from root with RUN_COMMAND intent.

But not a fully functional shell (in the same pty), right?

**Comment by agnostic-apollo** [comment]
>No, just "Rooted debugging" (ADB).

Do you mean `adb root`? If yes, then you won't be able to enter termux app domain without patching sepolicy for which you would require Magisk `supolicy`.

> But not a fully functional shell (in the same pty), right?

It would be better to tell what you are trying to do overall instead of asking for problem solution.

If you want to run commands from pc, then either use `ssh` or use `/system/bin/run-as` command with `adb` which both will provide a shell. For the later you will have to setup the shell environment yourself. For `run-as` you will need to use github debug build (not F-Droid), search the issues, it has already been discussed.

https://wiki.termux.com/wiki/Remote_Access

https://github.com/termux/termux-app#github

Closing since not a `termux-app` issue itself and feature won't be provided by it.
