### ISSUE TITLE
[Feature]: integration with the app shizuku 

### ISSUE THREAD

**Issue by lakshaysiwach** [termux/termux-app#2710]
### Feature description

This would allow non root devices to use termux as if the device is rooted. Please read this article to know how to integrate it with termux and it's benifits (https://www.xda-developers.com/implementing-shizuku/)

### Additional information

https://github.com/RikkaApps/Shizuku
https://www.xda-developers.com/implementing-shizuku/

**Comment by agnostic-apollo** [comment]
`adb` `shell` user != `root` user. And termux already provides `android-tools` package with `adb` binary.

`adb` integration into the app is planned for plugin commands, but may directly use `android-tools` package instead of shizuku, or both may be supported, depending on shizuku lib code itself.

**Comment by lakshaysiwach** [comment]
Okay thanks, i thought shizuku is meant to root permission to apps on non rooted Android devices. So i thought may i could now use external wifi adaptor on my device using kali in termux because only rooted device support this but now i see those two are different things

**Comment by agnostic-apollo** [comment]
I agree that shizuku would unify control across apps but I avoid adding third party library code to termux app that hasn't been reviewed by me and/or at least belongs to a big company like google, etc that likely would have good security practices. Shizuku works across apps and adb has high privileges, so design must be safe. It may be technically possible to offload shizuku stuff to a `sharedUserId` plugin without affecting termux-app itself. Will see when the time comes, likely not anytime soon.

>Except using adb on the command line is not as simple as one would expect, due to — what I imagine — are interactions between parts of the OS, the shell, and the unhandled use-case of using adb on a local terminal. 

Don't understand what you mean. Shizuku would have better support for calling system services with java code instead of `service call` command due to allowing custom objects to be passed, but otherwise for other commands, `adb shell` would work just fine.

> there are vendor-specific bugs on the Wireless Debugging functionality.
> I still can't always remember how to get adb working,

Shizuku would require root or wireless debugging as well. So those issues would be same for `android-tools` and shizuku. There are videos for enabling, I plan to add it to our docs as well.

https://shizuku.rikka.app/guide/setup/
