### ISSUE TITLE
Init error

### ISSUE THREAD

**Issue by danicaStarR** [termux/termux-app#2718]
### Problem description

In China.
I newly downloaded a Termux apk,
Then I installed and opened it, it said unable to download the source (bootstrap), then I went to the provided bootstrap site, and then, it show "Error 522".
- i am in pain! 

### Steps to reproduce the behavior.

😵

### System information

* Termux application version: v0.73
* Android OS version: 6.0.1
* Device model: Vivo

**Comment by wmcbtech30** [comment]
Download the offline bootstrap version of Termux app
https://archive.org/download/termux-repositories-legacy/termux-v0.79-offline-bootstraps.apk

and since https://termux.net is hijacked. you may as well install packages manually via `dpkg` through this archive
https://archive.org/download/termux-repositories-legacy/termux-repositories-legacy-24.12.2019.tar/

**Comment by danicaStarR** [comment]
And the apt is not work
![](https://user-images.githubusercontent.com/103302052/163714763-de279554-d380-4130-9863-bdd74025d71e.png)

**Comment by agnostic-apollo** [comment]
Only termux.net provided legacy debs repo and that is gone now too. The archive site has debs, install manually as suggested. Check #2651
