### ISSUE TITLE
[Bug]: Install termux as a system application.(root)

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-app#2726]
### Problem description

If you install termux as a system app (requires root and is installed in /system/app), it will not automatically install the bootstrap and you will have permission issues if you try to install it manually.

![6cdcece3fd88cac6](https://user-images.githubusercontent.com/57583560/164711043-add8378b-a81a-47cf-907b-bad1b24d8b09.jpg)

### Steps to reproduce the behavior.

1.Get root
2.Install termux as a system application
3.Open termux

### System information

* Termux application version:0.118.0
* Android OS version:10
* Device model:HUAWEI

**Comment by Grimler91** [comment]
Termux needs to be installed at `/data/data/com.termux`. Other paths (system app or on external storage) are not supported. See also https://github.com/termux/termux-packages/issues/2902

**Comment by agnostic-apollo** [comment]
>/data/data/com.termux

The data directory of system apps would also be that, that's not an issue.

Issue is that, OP probably installed bootstrap in non-system mode and then moved app to system. If he didn't, then lib load exception/crash would have been thrown since he wouldn't have extracted them manually.  Since `$PREFIX` would exist, bootstrap wouldn't need to be installed, so no crash.

However, the real issue would be android 10 exec restrictions, system apps are not exempt from them like `untrusted_app`.

OP needs to patch sepolicy on every boot.

https://github.com/termux/termux-app/issues/2445#issuecomment-985484952

**Comment by 2096779623** [comment]
> > /data/data/com.termux
> 
> The data directory of system apps would also be that, that's not an issue.
> 
> Issue is that, OP probably installed bootstrap in non-system mode and then moved app to system. If he didn't, then lib load exception/crash would have been thrown since he wouldn't have extracted them manually. Since `$PREFIX` would exist, bootstrap wouldn't need to be installed, so no crash.
> 
> However, the real issue would be android 10 exec restrictions, system apps are not exempt from them like `untrusted_app`.
> 
> OP needs to patch sepolicy on every boot.
> 
> [#2445 (comment)](https://github.com/termux/termux-app/issues/2445#issuecomment-985484952)

The same issue occurs with Android 7

**Comment by agnostic-apollo** [comment]
You haven't posted any logs or errors. And you need to extract native libs inside apk to relevant paths and give proper permissions.
