### ISSUE TITLE
I updated a package in termux and now it won't start...

### ISSUE THREAD

**Issue by KalmanReti** [termux/termux-app#277]
complaining about readline.so.6 being a missing dependency.

I tried updating the entire app from the Google Play store, but that didn't fix it.

I believe I'd installed a real shell a long time ago; I suspect this shell has the dependency, but there seems no way to get it to fall back to busybox.

Unfortunately, I have some files I need to get off and I believe totally uninstalling and reinstalling would lose them.

**Comment by fornwall** [comment]
There is fortunately a way to save your data!

1. Pull out the drawer from the left.
2. Long press on the `NEW SESSION` button.
3. In the resulting dialog, press the `FAILSAFE` button. This creates a limited shell using only the Android system tools.
4. Run `rm -Rf $PREFIX`.
5. Exit all Termux sessions.
6. Start up Termux again. You should now get a clean working install.

Note that the above instructions assume that the files you want to save are under $HOME and not $PREFIX (as $PREFIX is normally used only for system files) - otherwise you would need to copy them from $PREFIX to $HOME before removing $PREFIX.

Let me know if this works ok for you!

**Comment by KalmanReti** [comment]
It did indeed work. Thanks.
