### ISSUE TITLE
[Bug]: Termux doesn't apply configuration in termux.properties

### ISSUE THREAD

**Issue by rendiix** [termux/termux-app#2836]
### Problem description

The configuration in termux.properties is not applied. So cursor style, extra keys don't change.
![Screenshot_20220615-140010357](https://user-images.githubusercontent.com/16639978/173763197-91b147e1-e0be-409f-b27d-bc9f4e2c90f0.jpg)

### Steps to reproduce the behavior.

Install termux from GitHub action 

### What is the expected behavior?

Can change the cursor style, change the extra key and others

### System information

Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PACKAGE_VARIANT=apt-android-7
TERMUX_APP_PID=26590
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_VERSION=0.118.0+4ccd3f2
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
0.187
Android version:
11
Kernel build information:
Linux localhost 4.14.190-perf #1 SMP PREEMPT Tue Mar 8 00:02:53 CST 2022 aarch64 Android
Device manufacturer:
asus
Device model:
ASUS_I001DE

**Comment by agnostic-apollo** [comment]
Restart termux or run `termux-reload-settings`.

If created file with root, then check https://github.com/termux/termux-app/issues/2080#issuecomment-846575028

**Comment by rendiix** [comment]
> Restart termux or run `termux-reload-settings`.
> 
> If created file with root, then check [#2080 (comment)](https://github.com/termux/termux-app/issues/2080#issuecomment-846575028)

I've restarted termux also ran termux-reload-settings. my device is not rooted 
![Screenshot_20220615-172726809 (1)](https://user-images.githubusercontent.com/16639978/173806195-877cdf93-6c23-4740-9f8c-f18a53672b95.jpg)

**Comment by agnostic-apollo** [comment]
Set log level to verbose, run `termux-reload-settings` and post `Report Issue` output.

https://github.com/termux/termux-app#debugging

**Comment by agnostic-apollo** [comment]
This was actually a bug. Termux was storing the `File` object at app startup and was only reloading props from it. But since at app startup, the `termux.properties` file wouldn't exist during search, `null` was stored and default configs would be reloaded everytime. A force stop would have been required to fix the issue, or a reboot. I have fixed the issue locally and loading props will always search again for prop files. Thanks for reporting. Other users would have been affected to. like even just installing a fresh termux and trying to update the props.

https://github.com/termux/termux-app/blob/231ecff5f0837d1aa2831039b64afd07915e1cab/termux-shared/src/main/java/com/termux/shared/termux/settings/properties/TermuxAppSharedProperties.java#L16

https://github.com/termux/termux-app/blob/231ecff5f0837d1aa2831039b64afd07915e1cab/termux-shared/src/main/java/com/termux/shared/termux/settings/properties/TermuxSharedProperties.java#L32

https://github.com/termux/termux-app/blob/231ecff5f0837d1aa2831039b64afd07915e1cab/termux-shared/src/main/java/com/termux/shared/termux/settings/properties/TermuxPropertyConstants.java#L476

**Comment by AkioKiyota** [comment]
restarting device didnt solved in my case
is there any suggestions or anything i missed?

**Comment by RalfWerner** [comment]
What is the content of your `termux.properties` file?

**Comment by AkioKiyota** [comment]
GNU nano 7.2                                              .termux/termux.properties                                              Modified
### After making changes and saving you need to run `termux-reload-settings`
### to update the terminal.  All information here can also be found on the
### wiki: https://wiki.termux.com/wiki/Terminal_Settings

###############
# General
###############

### Allow external applications to execute arbitrary commands within Termux.
### This potentially could be a security issue, so option is disabled by
### default. Uncomment to enable.
# allow-external-apps = true

### Default working directory that will be used when launching the app.
# default-working-directory = /data/data/com.termux/files/home

### Uncomment to disable toasts shown on terminal session change.
# disable-terminal-session-change-toast = true

### Uncomment to not show soft keyboard on application start.
# hide-soft-keyboard-on-startup = true
### Uncomment to let keyboard toggle button to enable or disable software
### keyboard instead of showing/hiding it.
# soft-keyboard-toggle-behaviour = enable/disable

### Adjust terminal scrollback buffer. Max is 50000. May have negative
### impact on performance.
# terminal-transcript-rows = 2000

### Uncomment to use volume keys for adjusting volume and not for the
### extra keys functionality.
# volume-keys = volume

###############
# Fullscreen mode
###############

### Uncomment to let Termux start in full screen mode.
fullscreen = true

### Uncomment to attempt workaround layout issues when running in
### full screen mode.
# use-fullscreen-workaround = true

###############
# Cursor
###############

### Cursor blink rate. Values 0, 100 - 2000.
# terminal-cursor-blink-rate = 0

### Cursor style: block, bar, underline.
# terminal-cursor-style = block

###############
# Extra keys
###############

### Settings for choosing which set of symbols to use for illustrating keys.
### Choose between default, arrows-only, arrows-all, all and none
extra-keys-style = none

### Force capitalize all text in extra keys row button labels.
# extra-keys-text-all-caps = true

### Default extra-key configuration
# extra-keys = [[ESC, TAB, CTRL, ALT, {key: '-', popup: '|'}, DOWN, UP]]

### Two rows with more keys
# extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'], \
#               ['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]

### Configuration with additional popup keys (swipe up from an extra key)
# extra-keys = [[ \
#   {key: ESC, popup: {macro: "CTRL f d", display: "tmux exit"}}, \
#   {key: CTRL, popup: {macro: "CTRL f BKSP", display: "tmux ←"}}, \
#   {key: ALT, popup: {macro: "CTRL f TAB", display: "tmux →"}}, \
#   {key: TAB, popup: {macro: "ALT a", display: A-a}}, \
#   {key: LEFT, popup: HOME}, \
#   {key: DOWN, popup: PGDN}, \
#   {key: UP, popup: PGUP}, \
#   {key: RIGHT, popup: END}, \
#   {macro: "ALT j", display: A-j, popup: {macro: "ALT g", display: A-g}}, \
#   {key: KEYBOARD, popup: {macro: "CTRL d", display: exit}} \
# ]]

###############
# Colors/themes
###############

### Force black colors for drawer and dialogs
# use-black-ui = true

###############
# HW keyboard shortcuts
###############

### Disable hardware keyboard shortcuts.
# disable-hardware-keyboard-shortcuts = true

### Open a new terminal with ctrl + t (volume down + t)
# shortcut.create-session = ctrl + t

### Go one session down with (for example) ctrl + 2
# shortcut.next-session = ctrl + 2

### Go one session up with (for example) ctrl + 1
# shortcut.previous-session = ctrl + 1

### Rename a session with (for example) ctrl + n
# shortcut.rename-session = ctrl + n

###############
# Bell key
###############

### Vibrate device (default).
# bell-character = vibrate

### Beep with a sound.
# bell-character = beep

### Ignore bell character.
# bell-character = ignore

###############
# Back key
###############

### Send the Escape key.
# back-key=escape

### Hide keyboard or leave app (default).
# back-key=back

###############
# Keyboard issue workarounds
###############

### Letters might not appear until enter is pressed on Samsung devices
# enforce-char-based-input = true

### ctrl+space (for marking text in emacs) does not work on some devices
# ctrl-space-workaround = true

**Comment by RalfWerner** [comment]
Same in code block.
```
GNU nano 7.2 .termux/termux.properties Modified
After making changes and saving you need to run termux-reload-settings
to update the terminal. All information here can also be found on the
wiki: https://wiki.termux.com/wiki/Terminal_Settings

###############
General

###############
Allow external applications to execute arbitrary commands within Termux.
This potentially could be a security issue, so option is disabled by
default. Uncomment to enable.
allow-external-apps = true
Default working directory that will be used when launching the app.
default-working-directory = /data/data/com.termux/files/home
Uncomment to disable toasts shown on terminal session change.
disable-terminal-session-change-toast = true
Uncomment to not show soft keyboard on application start.
hide-soft-keyboard-on-startup = true
Uncomment to let keyboard toggle button to enable or disable software
keyboard instead of showing/hiding it.
soft-keyboard-toggle-behaviour = enable/disable
Adjust terminal scrollback buffer. Max is 50000. May have negative
impact on performance.
terminal-transcript-rows = 2000
Uncomment to use volume keys for adjusting volume and not for the
extra keys functionality.
volume-keys = volume

###############
Fullscreen mode

###############
Uncomment to let Termux start in full screen mode.

fullscreen = true
Uncomment to attempt workaround layout issues when running in
full screen mode.
use-fullscreen-workaround = true

###############
Cursor

###############
Cursor blink rate. Values 0, 100 - 2000.
terminal-cursor-blink-rate = 0
Cursor style: block, bar, underline.
terminal-cursor-style = block

###############
Extra keys

###############
Settings for choosing which set of symbols to use for illustrating keys.
Choose between default, arrows-only, arrows-all, all and none

extra-keys-style = none
Force capitalize all text in extra keys row button labels.
extra-keys-text-all-caps = true
Default extra-key configuration
extra-keys = [[ESC, TAB, CTRL, ALT, {key: '-', popup: '|'}, DOWN, UP]]
Two rows with more keys
extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'], \
['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]
Configuration with additional popup keys (swipe up from an extra key)
extra-keys = [[ \
{key: ESC, popup: {macro: "CTRL f d", display: "tmux exit"}}, \
{key: CTRL, popup: {macro: "CTRL f BKSP", display: "tmux ←"}}, \
{key: ALT, popup: {macro: "CTRL f TAB", display: "tmux →"}}, \
{key: TAB, popup: {macro: "ALT a", display: A-a}}, \
{key: LEFT, popup: HOME}, \
{key: DOWN, popup: PGDN}, \
{key: UP, popup: PGUP}, \
{key: RIGHT, popup: END}, \
{macro: "ALT j", display: A-j, popup: {macro: "ALT g", display: A-g}}, \
{key: KEYBOARD, popup: {macro: "CTRL d", display: exit}} \
]]

###############
Colors/themes

###############
Force black colors for drawer and dialogs
use-black-ui = true

###############
HW keyboard shortcuts

###############
Disable hardware keyboard shortcuts.
disable-hardware-keyboard-shortcuts = true
Open a new terminal with ctrl + t (volume down + t)
shortcut.create-session = ctrl + t
Go one session down with (for example) ctrl + 2
shortcut.next-session = ctrl + 2
Go one session up with (for example) ctrl + 1
shortcut.previous-session = ctrl + 1
Rename a session with (for example) ctrl + n
shortcut.rename-session = ctrl + n

###############
Bell key

###############
Vibrate device (default).
bell-character = vibrate
Beep with a sound.
bell-character = beep
Ignore bell character.
bell-character = ignore

###############
Back key

###############
Send the Escape key.
back-key=escape
Hide keyboard or leave app (default).
back-key=back

###############
Keyboard issue workarounds

###############
Letters might not appear until enter is pressed on Samsung devices
enforce-char-based-input = true
ctrl+space (for marking text in emacs) does not work on some devices
ctrl-space-workaround = true
```
You overwite EK=extra-keys three times! only the last is *activ* in my environment is:
![grafik](https://github.com/termux/termux-app/assets/45426380/9de3ec85-a18d-4ee0-a6d1-f3d8d7134bbc)
displayed after `termux-reload-settings`  as expected! *What is your expectation and do you get?*
