### ISSUE TITLE
[Bug]: When I open the app it shows me this (:/data/data/com.termux/files/home:$) 

### ISSUE THREAD

**Issue by AnasSdiq** [termux/termux-app#2844]
### Problem description

When I type (pkg install proot-distro) it shows for me (sh :pkg: inaccessible or not found)
![Screenshot_20220617-134708](https://user-images.githubusercontent.com/93283139/174283989-9344e4e7-d7d0-47ea-9141-1c2c58c340c4.png)

### Steps to reproduce the behavior.

install termux from github action builds
Execute (pkg install proot-distro)

### What is the expected behavior?

Installing proot-distro normally

### System information

* Termux application version: 0.118.0+bd6347d
* Android OS version: android 11
* Device model: Lenovo k12 note

**Comment by ask9027** [comment]
Same problem at fresh installation from recent github actions 
Android 12
Mi 11 Lite

Uploading Screenrecorder-2022-06-17-20-23-29-705.mp4…

**Comment by Kastilo** [comment]
Latest builds don't install the bootstrap packages, you can get around it by just installing the stable version and then installing the build artifact apks. For anyone who's curious about a workaround

**Comment by agnostic-apollo** [comment]
Thanks for the report. Check a2df7d79 for details. It actually came to me that this would happen when working on `termux.env` file, but forgot to fix it before pushing. It turned out to be more complicated to fix. I have added tests too since this is kinda dangerous since people's `$PREFIX` could be potentially be wiped if its falsely assumed to be empty due to some edge case. So test with caution. I have tested myself and on my daily device and seems to be working correctly.

You can install the latest build at https://github.com/termux/termux-app/actions/runs/2518728695 for the fix.
