### ISSUE TITLE
Failed to change zsh shell

### ISSUE THREAD

**Issue by VictorSantos97** [termux/termux-app#291]
I try to change the shell to zsh but I do not have success, maybe it is something very silly because I am new to termux, after I type 'chsh - zsh' I simply close the session with exit and when I open the app again it continues with the bash shell, please help.
![17626301_1933883003564584_7930251640785306129_n](https://cloud.githubusercontent.com/assets/22567103/24572006/d17f8f4a-163a-11e7-922b-fbc6288143f4.jpg)

**Comment by fornwall** [comment]
By default zsh in Termux is not visually different from bash - you are probably running zsh without seeing it.

You can check this by running `echo $ZSH_VERSION` to show the zsh version.

You might then want to install oh-my-zsh - that will bring some flair to zsh. Run `apt install curl git` to get the prerequisites, then run

    sh -c "$(curl -fsSL https://raw.githubusercontent.com/fornwall/oh-my-zsh/etc-shells-may-not-exist/tools/install.sh)"

Note that you need to install it from a special URL as in the above before https://github.com/robbyrussell/oh-my-zsh/pull/4564 gets fixed in oh-my-zsh upstream.

**Comment by stach** [comment]
You need to run the cshs command in the zsh shell. Not in the bash one.

**Comment by aliza-ada** [comment]
i how to del zsh and set default color On Termux?

**Comment by sdrausty** [comment]
`chsh bash` will give the default shell.  Edit your `.bashrc.` for color.  To colorize `ls` add `alias ls='ls --color=always'`.  See [addbashrc](https://github.com/sdrausty/TermuxArch/blob/master/archsystemconfigs.sh#L119&#L137) for more `.bashrc` alias examples.
