### ISSUE TITLE
Expose name and version as environment variables

### ISSUE THREAD

**Issue by sindresorhus** [termux/termux-app#292]
Many terminals (macOS Terminal, iTerm2, Hyper, …) exposes their name and version through the environment variables `TERM_PROGRAM` and `TERM_PROGRAM_VERSION`. It would be useful if Termux did the same.

Example:

```
~
❯ echo $TERM_PROGRAM        
Hyper

~
❯ echo $TERM_PROGRAM_VERSION
1.3.1
```

---

This would make the Termux detection in https://github.com/sindresorhus/clipboardy/pull/10 nicer.

// @Rudloff

**Comment by Neo-Oli** [comment]
This would also make https://github.com/termux/termux-packages/pull/422 completable.

**Comment by fornwall** [comment]
@Neo-Oli Hm, `TERM_PROGRAM` and `TERM_PROGRAM_VERSION` would only indicate the terminal emulator used, so if e.g. ssh:ing into Termux it would indicate the terminal emulator used, not Termux.

Perhaps we (also) need something like a `TERMUX=0.49` environment variable to indicate that we are running inside Termux regardless of terminal emulator used?

Or something else more standard, perhaps change `uname -o` to return `Termux` instead of `Android`? Any ideas/opinions?

**Comment by Rudloff** [comment]
I don't think changing `uname` is a good idea, it might break some scripts or Makefiles.
However, we could use the [`os-release` file]( https://www.freedesktop.org/software/systemd/man/os-release.html) which is used by most Linux distributions.

**Comment by Neo-Oli** [comment]
Yes, I like the os-release file idea. If it's just a file we don't need to clutter the environment with unnecessary variables.

**Comment by xeffyr** [comment]
Implemented in https://github.com/termux/termux-app/commit/e03858f0659c108f12d44b5c162586a66d351765 as environment variable `TERMUX_VERSION`.
