### ISSUE TITLE
[Bug]: Compiling Problem

### ISSUE THREAD

**Issue by harsh7i** [termux/termux-app#2943]
### Hello all
I need a Terminal Emulator for my android app project.
So i want to used Termux as my Terminal Emulator.
As wiki i implemented these implementions to my build.gradle file.
```shell
implementation 'com.termux:termux-shared:0.117'
implementation 'com.termux.termux-app:terminal-view:0.117'
```
And then when i started to compile, it showing an error.

### Steps to reproduce the behavior.

* Started an project with these
![IMG_20220818_115008](https://user-images.githubusercontent.com/100824266/185308233-0e0ad21e-6c54-48a1-aa39-2a0183111b11.jpg)
![IMG_20220818_114952](https://user-images.githubusercontent.com/100824266/185308320-5c94fada-4118-46dd-9dce-d89ea24ad832.jpg)

Then I begins compilation.
And i found the error

### What is the expected behavior?

![IMG_20220818_113901](https://user-images.githubusercontent.com/100824266/185308620-98827930-6c5d-497f-8a05-abc1d58faed7.jpg)

### System information

* Termux application version:
* Android OS version: 
* Device model:

**Comment by Rillian-Grant** [comment]
It seems like you've got an android API version mismatch between Termux and your app, see: https://github.com/termux/termux-app/blob/211340781bcb0576ffe100fda2e0ed87d7333d53/gradle.properties#L18

Termux uses an older SDK version due to issues with some of the security restrictions of more recent versions.

Are you intending to use the whole Linux environment of Termux or just the terminal emulator as I'm pretty sure that the older SDK version is only needed for the former.

**Comment by agnostic-apollo** [comment]
The `implementation 'com.termux:termux-shared:0.117'` library you are using is using `minSdkVersion=24`, but your own project is using `minSdkVersion=21`. Since a dependency library cannot have a  higher `minSdkVersion` than your own, you are getting an error.

So either
- Set `minSdkVersion=24` in your own project.
- Or use `implementation 'com.github.termux.termux-app:termux-shared:211340781b'` based on 211340781b build which is using `minSdkVersion=21` since we recently dropped it after `0.118.0` release to re-add support for android  5/6.

**Comment by harsh7i** [comment]
> The `implementation 'com.termux:termux-shared:0.117'` library you are using is using `minSdkVersion=24`, but your own project is using `minSdkVersion=21`. Since a dependency library cannot have a higher `minSdkVersion` than your own, you are getting an error.
> 
> So either
> 
> * Set `minSdkVersion=24` in your own project.
> * Or use `implementation 'com.github.termux.termux-app:termux-shared:211340781b'` based on [2113407](https://github.com/termux/termux-app/commit/211340781bcb0576ffe100fda2e0ed87d7333d53) build which is using `minSdkVersion=21` since we recently dropped it after `0.118.0` release to re-add support for android  5/6.

### Hello @agnostic-apollo Sir

* Thanks for the reply

This Time I used
`implementation 'com.github.termux.termux-app:termux-shared:211340781b'`
As you say.
But i found a new issue

I didn't understand about this please help me.

This appears when i began to compiling project.

![IMG_20220819_152524](https://user-images.githubusercontent.com/100824266/185595546-e818f2bc-35b2-447b-a96a-890bab112df9.jpg)
