### ISSUE TITLE
[Bug]: Intent not working if termux not in background

### ISSUE THREAD

**Issue by noenic** [termux/termux-app#2957]
### Problem description

I made a kind of application that allows to launch scripts with termux when we press the buttons of my android head unit, it works well, but the termux application must be launched at least once since the last reboot, I can't get an error message, I just have the impression that termux does not respond to the intent.

Here is my java code : 
```
public void startActivityByIntentName(Context context, String component) {
        Intent intent = new Intent();
        intent.setClassName("com.termux", "com.termux.app.RunCommandService");
        intent.setAction("com.termux.RUN_COMMAND");
        intent.putExtra("com.termux.RUN_COMMAND_PATH", "/data/data/com.termux/files/home/"+component);
        intent.putExtra("com.termux.RUN_COMMAND_BACKGROUND", true);
        intent.putExtra("com.termux.RUN_COMMAND_SESSION_ACTION", "0");
        context.startForegroundService(intent);

}
```
thanks

### Steps to reproduce the behavior.

I actually don't know to reproduce this

All I can say is that something is wrong with the intent call or termux when the termux-app is not already "started" after a reboot.
after opening it everything works, even after closing termux in the task manager it still execute the intent

### What is the expected behavior?

I guess it should execute the RUN_COMMAND, even after a reboot or when the app is not already in the background.

### System information

* Termux application version: 0.118.0
* Android OS version: 10 
* Device model: FYT uis7862  android head unit

**Comment by agnostic-apollo** [comment]
There might be something like `Auto Start` disabled or other battery optimizations enabled for termux in head unit ROM.

https://dontkillmyapp.com/xiaomi

To get the exact error, you would need to get `logcat` dump with `adb` or root from your head unit. Maybe wireless adb works if usb debugging is not possible.

https://github.com/termux/termux-app#debugging

Closing since issue is likely not related to termux, unless proof is provided.
