### ISSUE TITLE
[Feature]: list Termux plugins

### ISSUE THREAD

**Issue by babaric-dev** [termux/termux-app#2961]
### Feature description

In some of my scripts, the user is required to have Termux:API / Termux:GUI etc. Is it possible to list all of them?

### Additional information

nil

**Comment by agnostic-apollo** [comment]
I have already added support locally to export version variables of all supported plugins, including GUI/X11 and will push changes soon. `TERMUX_API_VERSION` was already added in `0.118.0` but variable name has now been changed to `TERMUX_API_APP__VERSION_NAME` due to variable scoping recently implemented.

Of course variables will be exported at the time the shell was started so won't be updated if app gets installed or uninstalled after shell started, unless `termux.env` file is sourced before checking.

https://github.com/termux/termux-app/releases/tag/v0.118.0

https://github.com/termux/termux-app/commit/afc06cfd0a9855e8443d0b62cd57d8fa9e4547a1

https://github.com/termux/termux-app/commit/03e1d14e1e65e054eeeb0ad672a46c2c17254d3e
