### ISSUE TITLE
bash colon redirect input error

### ISSUE THREAD

**Issue by ghost** [termux/termux-app#300]
If I run a script with something like this in it:

: << 'SKIP'
some text
SKIP

I get the following error:
/data/data/com.termux/files/home/someScript[6]: can't create temporary file /data/local/shvs1y3e.tmp: Permission denied

**Comment by fornwall** [comment]
Are you sure that just having

```bash
: << 'SKIP'
some text
SKIP
```

in a file is enough to trigger it (I cannot reproduce that), or do you have anything more in the script that could cause this?

**Comment by dogear42** [comment]
@fornwall 

Ah, good point!  My bad for not testing that in isolation.

The script containing those lines is called from inotifyd.

So: 
inotifyd ~/someScript ~/notes

**Comment by fornwall** [comment]
@dogear42 I still think we need to see (at least the relevant part of) `~/someScript` here.

**Comment by dogear42** [comment]
I reproduced the issue with minimal scripting, below.

I ran inotifyd to use the script.  I then edited a file in the ~/notes directory, and it erred twice while trying to invoke the script.

I then hit ctrl+c and catted the script in question.

My PS1 generated [~], so that is not really part of anything there.

```
$ inotifyd ~/someScript ~/notes
/data/data/com.termux/files/home/someScript[3]: can't create temporary file /data/local/sh8ej2ck.tmp: Permission denied
/data/data/com.termux/files/home/someScript[3]: can't create temporary file /data/local/sho46ur3.tmp: Permission denied
^C[~]
$ cat someScript
:<< 'SKIP'
some text
SKIP
echo "stuff";

```

If I do everything the same, except remove the first 3 lines from the script (the here document redirected to : ), I get:

```
stuff
stuff
stuff
stuff
stuff
stuff
stuff
stuff
stuff
stuff
stuff
stuff
stuff
stuff
stuff
stuff
stuff
stuff
```

**Comment by xeffyr** [comment]
Seems to be fixed.
