### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by paopaokiller** [termux/termux-app#3047]
### Feature description

My problem : /data/data/com.termux/cache/apt/archives/partial/unzip_6.0-9_aarch64.deb - open (2: No such file or directory)

### Additional information

I have run the command: termux-setup-storage

**Comment by agnostic-apollo** [comment]
Likely issue is that your device internal storage gets too low when apt downloads packages and when it gets below a limit, android clears the cache directories of apps, resulting in deb not being found. Free space or try to update single packages with `apt install` instead of all with `apt upgrade`.
