### ISSUE TITLE
[Feature]: Accessing Android/data or obb by mounting via SAF manually

### ISSUE THREAD

**Issue by donmor** [termux/termux-app#3117]
### Feature description

Using android 12, I can access Android/data using zarchiver by granting access manually. This hack may works with termux.

It may be a dup but this feature shoud not be abandoned.

### Additional information

I found a solution on jianshu (a Chinese website): https://www.jianshu.com/p/d02bc6266198
Google translator needed though

**Comment by agnostic-apollo** [comment]
You can try `termux-saf-*` commands from `termux-api` package/app if  using github builds.

https://github.com/termux/termux-api/pull/476

**Comment by smartm0use** [comment]
Thank you for your prompt replies and sorry if I open again the issue.
If I full understand termux doesn't access removable devices that are attached to USB port but only internal sdcard?
I am new on termux but this limitation sounds weird for me, because I'm following a guide to read external hard disk with AndronixApp and in the video the author attaches the drive and it is working.
He just says to format hard drive with Android system format...

What am I missing?

**Comment by smartm0use** [comment]
Ehm... I read about some limitations in newer versions of Android and for this I have downgraded it to 8.1 with LineageOS 17.1, as I reporter in the first post.

**Comment by agnostic-apollo** [comment]
If you have root access, just use that instead of saf or adb.

**Comment by smartm0use** [comment]
I do not have root access. Do you mean that if I have it I can see removable drives in "external-1" folder?

**Comment by agnostic-apollo** [comment]
You can see everything on the device with root. Need to be in global mount namespace if app is using `targetSdkVersion` `>= 30` on Android `>= 11` to see private app data directories of other apps, but that doesn't apply to termux currently. Access would also much faster than over saf/scoped/emulated storage, as long as you use `/data/media/` and `/mnt/` paths instead of `/storage/`.

You are using lineage os, getting root access should be easy, unless deliberately running non-rooted lineage.
