### ISSUE TITLE
[Feature]: Please remove 'max terminals reached' limitation

### ISSUE THREAD

**Issue by eisklwksjs** [termux/termux-app#3123]
### Feature description

When i tried to open 9th session, it shows 'max sessions reached' error
![Screenshot_20221202-111646_Termux](https://user-images.githubusercontent.com/90270441/205224436-8fc71e7f-81f4-4edc-8c99-bb9ef5e7e6ae.jpg)

### Additional information

Terminal emulator don't have this limit

**Comment by agnostic-apollo** [comment]
Running `am startservice -n com.termux/.app.TermuxService -a com.termux.service_execute -d "file://com.termux.file/data//data/com.termux/files/usr/bin/login"` should work too to open a session.

**Comment by eisklwksjs** [comment]
Yes, more sessions = more processing power = more memory consumption, i got it; just want to open few tabs; thats it; thanks, i dont even know about the method you mentioned above

**Comment by MasterInQuestion** [comment]
At least raising the default limit to 16? (8 was impractically low)
    [ ^ For current hardware probably no limit could be more sensible. ]
    Also instead of blocking warning:
    Change to confirmation of whether to continue instead?
    (warn about the memory usage)

    Bookmarking the very long &#x60;am&#x60; command is unwieldy.
    I remember in certain very distant version the limit was 32? (or no limit at all?)

    See also: [ https://github.com/termux/termux-app/issues/3791](https://github.com/termux/termux-app/issues/3791)

    ----

    One thing not quite right with the method:
    `am startservice -n 'com.termux/.app.TermuxService' -a 'com.termux.service_execute' -d '/data/data/com.termux/files/usr/bin/login';`
    .
    Is that the created session name, is not the usual "". (this would be the "$0")
    Plus the start-up working directory, won't be the same as that invoked usually. (seemingly unconditional "~/"?)

    Maybe it could be specified on the command line?
