### ISSUE TITLE
[Bug]: SSHD Password

### ISSUE THREAD

**Issue by qos-1a** [termux/termux-app#3128]
### Problem description

So I use my phone as a sshd and html server and everytime I connect to the ssh, it asks for password and I have to set the password using passwd manually on the phone. I can login to the terminal but next time I try to login and it will be happen again.

### Steps to reproduce the behavior.

Everytime login to the ssh it will happens

### System information

* Termux application version:0.117 installed with Andronix app
* Android OS version: 11 RKQ1.200826.002 MIUI Global 12.5.1
* Device model: Poco F3 Global

**Comment by Grimler91** [comment]
It should ask for password every time, so seems it is working as it should.

Do you have to run `passwd` every time? Why?

**Comment by qos-1a** [comment]
I have to run passwd everytime when I login, otherwise idk why it says permission denied.

**Comment by Grimler91** [comment]
Permission denied happens if you type the wrong password a couple of times, so are you giving it the right password? Only other reason I can think of for permission denied is if you have played around as root or something (would help to see exactly what you are running and exactly what the error message is).

You mention andronix, so what exactly is your setup and what are you running? Please provide steps to reproduce issue.

Note that this is the bug tracker for termux, not andronix

**Comment by Grimler91** [comment]
Closing since we haven't heard from OP in a week, and from the information given I don't really think this is a termux issue
