### ISSUE TITLE
Suggestion: shorter name for packages script?

### ISSUE THREAD

**Issue by v0idst4r** [termux/termux-app#321]
Maybe `pkg` instead of `packages`? It's just more convenient especially when typing on a 5" screen. :p

**Comment by Wetitpig** [comment]
Actually why is the `packages` command necessary? `apt` is enough.

**Comment by v0idst4r** [comment]
Not sure, it's just a little convenient apt wrapper I guess.

**Comment by fornwall** [comment]
The `packages` command is basically to run `apt update` before doing an actual operation.

It's a lot easier to inform users about running `packages install xxx` or `packages upgrade` instead of always having to remember to run an `apt update` first.

It would be best if we could configure `apt` itself to always do that, but if we still need a wrapper script for that I think the suggestion to have a shorter name such as `pkg` for it is a good one!

**Comment by fornwall** [comment]
Thanks - `pkg` is now the preferred short name if you update to the latest version of the `termux-tools`!

The old alias `packages` is kept around for compatibility, at least for now.
