### ISSUE TITLE
[Bug]: When i try to uninstall termux my device reboots

### ISSUE THREAD

**Issue by flic420** [termux/termux-app#3227]
### Problem description

I've installed termux using google play and when I try to uninstall it my device restarts, so I can't uninstall it.

### Steps to reproduce the behavior.

Termux > app info > uninstall

### System information

* Termux application version: 0.101
* Android OS version: 12
* Device model: YT-706F

**Comment by 2096779623** [comment]
You want to run Termux on Lenovo Yoga tab 11 with Windows rt OS?

**Comment by 2096779623** [comment]
https://github.com/termux/termux-app#google-play-store-deprecated

**Comment by agnostic-apollo** [comment]
> You want to run Termux on Lenovo Yoga tab 11 with Windows rt OS?

It should have android.

https://m.gsmarena.com/lenovo_yoga_tab_11-ampp-10988.php

> I've installed termux using google play and when I try to uninstall it my device restarts,

That would be a device/os issue, not a termux issue. Report to leneno.

You can try running `adb logcat > logcat.txt` from pc and then try uninstalling and when device reboots, check end of `logcat.txt` for any `Exception` or errors that are thrown that are causing the reboot.

You can also try uninstalling termux with adb with `adb shell pm uninstall com.termux` since that may succeed if issue is related to GUI uninstallation.

https://developer.android.com/studio/command-line/adb
