### ISSUE TITLE
[Bug]: sudo output doesn't work unless it's a tty

### ISSUE THREAD

**Issue by jgilmore** [termux/termux-app#3259]
### Problem description

The supplied sudo command works to carry a file, but fails if the output is redirected.

### Steps to reproduce the behavior.

~ $ sudo cat l                                 
-----BEGIN OPENSSH PRIVATE KEY-----                 -----END OPENSSH PRIVATE KEY-----
~ $ sudo cat l > l.bak                         
~ $ cat l.bak                                   

l.bak has a size of zero

### What is the expected behavior?

Sudo should not block cat's output, even when redirected.

I need this to fix busted permissions on my home directory. Apparently on Android setting the user and permissions correctly isn't sufficient, and so now I have to invoke ssh as "sudo ssh" for it to work. Probably selinux extensions, but I haven't found any way to fix them.

They're busted because temux doesn't have a package manager. It has a package borker, and installing rsync broke my ability to use ssh by removing the required libraries. (It's not like there's no mechanism to prevent this, several different "conflicts with" notations could have been added to various packages, but weren't.) Which required a complete reinstall to fix which required banking up and restoring the gone directory, which is now borderline unusable.

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by agnostic-apollo** [comment]
Redirection happens in current user's shell instead of root shell and current user won't have write access if ownership is messed up.

You could probably use `sudo -s` command if using my variant of `sudo` instead of `tsu` or run `sudo su` first to start a interactive root shell.

https://github.com/agnostic-apollo/sudo#script

To fix ownership, check https://github.com/termux/termux-app/issues/2080#issuecomment-846575028
