### ISSUE TITLE
[Feature]: I need to add one edittext and button 

### ISSUE THREAD

**Issue by safalbhatia** [termux/termux-app#3277]
### Feature description

I need to add one edittext and button.
When I write any text in Edittext then show in Terminal editable Text. After Click Button Command Run. Like softkeyboard enter. Pls help me Any one do this pls message me bhatiasafal786@gmail.com

### Additional information

![WhatsApp Image 2023-03-01 at 11 57 26 PM](https://user-images.githubusercontent.com/27086730/222335774-29d34c4e-37d4-4707-91bd-17c96a4e8555.jpeg)
Pls Help Me. I need Functionality.

**Comment by agnostic-apollo** [comment]
That's already implemented

https://web.archive.org/web/20230129015239/https://wiki.termux.com/wiki/Touch_Keyboard#Text_Input_View

And you seem to have installed termux from playstore. That is not supported.

https://github.com/termux/termux-app#google-play-store-deprecated

https://github.com/termux/termux-app#Installation

**Comment by safalbhatia** [comment]
Paid Task If You can do this

**Comment by agnostic-apollo** [comment]
Have you check text input mode on Github and F-Droid builds by swiping left on extra keys? Although, should exist on playstore ones too. If you are asking for something else, then explain more clearly because cannot understand you.

**Comment by safalbhatia** [comment]
I need this type of functionality. When i add text in edittext then show in
terminal screen and Keyboard enter click work when click on button.
My WhatsApp +918082408061

**Comment by agnostic-apollo** [comment]
If you mean to type text into terminal as soon as you type text in edit text, then that would cause problems. What if you type text directly into terminal, and then switch mode and then type text in edit text and then switch again to terminal, then there would be no synchronization between both texts and also erasing text would not erase text from terminal. Moreover, if text is typed as soon as you type in edit text and terminal is showing that text, and then you move cursor to random place in edit text and modify text, then won't easily be able to reflect the modification in the terminal since terminal is not a text field.

**Comment by safalbhatia** [comment]
1) Can i add button After click button command run?
2) How i detect what text enter in terminal?
3) In Button click how we detect what i enter in terminal

**Comment by safalbhatia** [comment]
I need this type of functionality. Can you pls provide that.

**Comment by Grimler91** [comment]
Maybe this is about the issue on some samsung devices where text does not appear until enter is pressed. For that, see workaround in wiki: https://wiki.termux.com/wiki/Terminal_Settings#Workaround_issues_with_some_keyboards

**Comment by safalbhatia** [comment]
You can do this functionality.

**Comment by safalbhatia** [comment]
Hello Sir,
From tomorrow My

mTerminalView.getContentDescription()

Come Null. I don,t know why pls help
