### ISSUE TITLE
"libcrypto.so" is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by RerumNovarum** [termux/termux-app#33]
$ ssh
CANNOT LINK EXECUTABLE DEPENDENCIES: "libcrypto.so" is 32-bit instead of 64-bit
$ df -h
CANNOT LINK EXECUTABLE DEPENDENCIES: "libcrypto.so" is 32-bit instead of 64-bit

**Comment by fornwall** [comment]
The `df` issue has been fixed in the `termux-tools` package, update with `apt update && apt upgrade`.

About the `ssh` problem, it seems that you are trying to execute a system binary, not the one supplied by Termux. See https://termux.com/common-problems.html#cannot-link-executable-cannot-locate-symbol--referenced-by- for how to work around that!

**Comment by matclab** [comment]
I seem to have the same problem with the mount command however the given link is dead...

**Comment by empjustine** [comment]
https://github.com/termux/termux.github.io/blob/5a29abb4654e8d91cd96038b2fca5b199eca1246/common-problems.md

**Comment by matclab** [comment]
Thanks !

Le dim. 13 nov. 2016 à 20:50, Cássio Oseki <notifications@github.com> a
écrit :
