### ISSUE TITLE
[Bug]: Storage breaks and cannot be fixed

### ISSUE THREAD

**Issue by ttoocs** [termux/termux-app#3320]
### Problem description

The [wiki ](https://wiki.termux.com/wiki/Termux-setup-storage) says that the permission denied error can be fixed. This is not the case on my Samsung A03.
- Resetting storage permissions only enables music/video/photos, but not the global file permission.
- "This app doesn't support the latest version of Android. If this app can't access photos and videos, it also won't be allowed to access music, audio, other files."
- Toggling the permissions for "Music and audio" and "Photos and videos", will toggle each other too.
- When Music+Photos are disabled, toggling on "Files" will toggle those to on, but itself will still stay off.
- Rerunning termux-setup-storage doesn't fix, no storage folder is created, even though it returns 0.
  -  Running with permissions all disabled, will again enable photos and music, but the file permission stays disabled. Still no folder.
- I have some weird transient where some folders/files can still be seen, I have no idea how/why, but it seems there's some odd-state going on there too.

However, somehow, when you first install the app, it works correctly. (I'm not sure the permission-screen status, as it was working, and so I was content with my life)
- It seems some updates will break this, and then I'm unable to recover.

I'd love this to get fixed somehow, it seems https://developer.android.com/training/data-storage/manage-all-files is what we might actually want, but would be an API bump?
- I am a programmer (tho not android), so if someone gives me a list of things to read to catch-up and point me on my way I can also continue to investigate this.

### Steps to reproduce the behavior.

Have a system update, or permissions reset? Not sure.
-- Will spend some time this evening seeing if I can reproduce it reliably.

### What is the expected behavior?

Able to read and write files on the SDcard.

### System information

* Termux application version: 0.118.0 - FDroid (2022-01-10)
* Android OS version: 13,
* Andorid Build number: TP1A.220624.014.A037WVLS3CWC1
* Device model: Galazy A03s (SM-A037W)

**Comment by agnostic-apollo** [comment]
Try rebooting your device. For Termux F-Droid builds, Android Settings -> Apps -> Termux -> Permissions -> Files and media -> Allowed management of all files should grant storage permission as per AOSP. If you are seeing something else, then maybe Samsung broke legacy storage for old apps. Manage external storage should not have any effect for termux since it is using `targetSdkVersion` `28`, but you can check Android Settings -> Apps -> (Advanced ->) Special app access -> All files access -> Termux.

>Able to read and write files on the SDcard.

Note that external sd card will not be readable even with the permission (although some samsung phones allow it). You will only be able to read external/public storage of internal sd card.


Closing since not a termux app issue.
