### ISSUE TITLE
Broken play store link

### ISSUE THREAD

**Issue by anirudh-chhangani** [termux/termux-app#337]
The link to play store is broken or at least not available in India.

<img width="882" alt="screen shot 2017-06-08 at 8 26 36 am" src="https://user-images.githubusercontent.com/2513446/26910427-5e7e1f5a-4c24-11e7-894b-d94a43c32c3a.png">

**Comment by vishalbiswas** [comment]
It is blocked globally. We don't know the real reason until @fornwall comes online.

**Comment by fornwall** [comment]
Termux got pulled from Google Play `because it violates the payments policy`.

Unfortunately no more specific information were given, but I suspect the donate link in the app description caused the issue. Will read up on the payment policy of google play and submit an updated description without the donate link, so hopefully it will be put back!

**Comment by SilentProgramer** [comment]
Thanks for the update, Fredrik :) Hoping to see Termux back on the store soon

**Comment by fornwall** [comment]
Good news - the app is up again after removal of the donate link (try again in a few hours if not, it could be caching issues if it doesn't work)!
