### ISSUE TITLE
[Feature]: Add "Run Command" button

### ISSUE THREAD

**Issue by xmha97** [termux/termux-app#3376]
### Feature description

Please add "Run Command" button at the bottom.

### Additional information

Like YTDLnis:

![Screenshot_2023-05-05-19-45-14-942_com deniscerri ytdl](https://user-images.githubusercontent.com/23485114/236512102-946bab73-da2a-4530-a745-b7b3a1acbd61.jpg)

**Comment by TomJo2000** [comment]
The Default Termux interface is meant to [emulate a Terminal](https://en.wikipedia.org/wiki/Terminal_emulator) in order to let the user interact with a command shelll such as Bash, Zsh, Fish, etc.
As such commands are run by hitting enter after inserting a command onto the command line.
This is an intentional design decision.
