### ISSUE TITLE
Problems with termux-location

### ISSUE THREAD

**Issue by Meeett** [termux/termux-app#340]
termux-location take a wile but I doesn't get a result or error...
I tried [-p provider] [-r request], too...

**Comment by francoyo1998** [comment]
I'm having the same problem... did you fix it?

**Comment by ivangsp** [comment]
same problem  here, did of any u fix it

**Comment by xeffyr** [comment]
> It seem its common problem.

It becomes a common problem when:

1. You have GPS location disabled but trying to use it anyway through API.
2. You are trying to acquire GPS location in home.
3. You have NET location disabled but trying to use it anyway through API.
4. You are using a custom rom (like LineageOS) without google apps.
5. Your rom has a broken implementation of net location provider.
6. You can't use network location because google services are blocked in your country. - in this case use GPS-only.

\- now I hope you may know why it may not working.

**Comment by YEDrekt** [comment]
@xeffyr Is there any way to acquire GPS location in home or a building?

**Comment by xeffyr** [comment]
> GPS location in home or a building?

GPS requires a signal from satellites. This signal is usually low, but some devices able to catch it near window.
