### ISSUE TITLE
[Bug]: spanish keyboard's alt key makes accents and cannot be used for shortcuts

### ISSUE THREAD

**Issue by amaramth** [termux/termux-app#3407]
### Problem description

This physical keyboard is spanish, termux interprets it as a u.s. keyboard which is as desired, but the keyboard shortcuts alt + e, alt + i, alt + u, alt + n, alt + ` produce accented characters. alt + c and alt + s also produce special characters. Also, after an accented character is produced, all accentable characters are accented until after switching to another app and typing.

To be clear, this is the regular alt key, not altgr.

### Steps to reproduce the behavior.

Use a physical spanish keyboard. Open nano. Press alt + u.

### What is the expected behavior?

The last operation is undone.

### If that's wontfix, there also exists the bug produced by:

In termux type alt + u, u, echo.

### What is the expected behavior?

The string `üecho` is produced. Instead, `¨üëcḧö` is produced.

### System information

* Termux application version: 0.118.0
* Android OS version: 8.0.0
* Device model: F5321

**Comment by MrPocketMonsters** [comment]
Hi. I had the same issue. I solved it in my phone by going into Termux's settings, by holding the app in the launcher for a bit. 

You will see a menu with 4 items: Termux, Termux:API, About and Donate.

Go to Termux > Terminal I/O

Turn on the option "Soft Keyboard Only If No Hardware" and go back to Termux to check if the problem is fixed.

**Comment by amaramth** [comment]
Thank you, that resolves this issue for me.
