### ISSUE TITLE
Remote ssh prompt keeps showing on termux tooltip after exiting a ssh session

### ISSUE THREAD

**Issue by dbermond** [termux/termux-app#343]
After exiting from an ssh session the termux tooltip shows the remote ssh session prompt `[1]username@hostname:~` instead of showing `[1]`.

The ssh server that I'm connecting to is currently OpenSSH_7.5p1 running on Arch Linux x86_64.

**Comment by xeffyr** [comment]
That's because you don't have configured terminal title resetting, which some Linux distros have.

Default terminal title can be configured in the following way in `~/.bashrc`:
``` .bash
case "$TERM" in
	xterm*|rxvt*)
		PS1="\\[\\e]0;termux: \\w\\a\\]$PS1"
		;;
	*)
		;;
esac
```
It will be reset after each command finishes execution. So, in case when `ssh` disconnected you will no longer observe no longer valid `username@hostname:~` in your terminal title.
