### ISSUE TITLE
[Feature]: Rename `PREFIX` to `TERMUX_PREFIX` in v1.0

### ISSUE THREAD

**Issue by Rudxain** [termux/termux-app#3469]
### Feature description

This will reduce the likelihood of namespace collision with 3rd-party env vars.

Since v1.0 will be a major version, it is allowed to introduce breaking changes

### Additional information

`TERMUX_PREFIX` is already used in the context of packaging, so this would increase consistency in the ecosystem

**Comment by tareksander** [comment]
Firstly, the next release is 0.119, so I don't know if there will ever be a 1.0, and secondly I don't know if Termux even uses semantic versioning.

**Comment by TomJo2000** [comment]
That would be a **major, breaking, change** for the existing infrastructure, to very dubious benefit beyond "consistency",
which while laudable does not in itself justify such a change to a core component of the environment.

Unless you have _**concrete**_, _**widely used**_ examples of programs for which `$PREFIX` is producing breaking variable collisions;
there is no sense in breaking 1000+ packages, and potentially every single user's configs over a potential issue which is not practically happening.

The next release is slated to be 0.119, as far as I am aware there are no plans for a 1.0 release.

**Comment by Rudxain** [comment]
@TomJo2000 Those are good points.

I remember there was an issue about a name collision with some program, but I can't remember which. I tried searching for it, but couldn't find it (Google and GH didn't return helpful results)

**Comment by errr-maxx** [comment]
There is some collision with zsh completions, they use `$PREFIX` as "the part of the current word from the beginning of the word up to the position of the cursor"

**Comment by TomJo2000** [comment]
> `$PREFIX` is not relied on in any of packages.
I could have worded that better, sorry.

**Comment by agnostic-apollo** [comment]
It is not the internal termux packages that are the issue, but the user scripts that use it. Even plugins like termux-tasker and `RUN_COMMAND` intent support `$PREFIX` expansion.

However, `$PREFIX` has already been deprecated locally and a new variable `$TERMUX__PREFIX` under the `$TERMUX__` scope (note 2 underscores) is exported. In future, a property will be added that disables exporting `$PREFIX`, its default value may be `false` initially but may be set to `true` when `1.0` is released in future, whenever that happens.

An additional issue is 3rd party cross platform tools that use `$PREFIX` to check if they are running in termux on android, so they will have to switch to the new env variable, or a separate  variable that does not have `TERMUX` in its name since termux forks may change value of `TERMUX_ENV_PREFIX_ROOT` (`TERMUX`), although that is now exported as `$ENV__ROOT_SCOPE` as well, to allow dynamic checking of scopes.

https://github.com/termux/termux-app/blob/11d8e4ff8fd3517842a2687ac5779477cb572fae/termux-shared/src/main/java/com/termux/shared/termux/TermuxConstants.java#L903

https://github.com/termux/termux-app/blob/11d8e4ff8fd3517842a2687ac5779477cb572fae/termux-shared/src/main/java/com/termux/shared/termux/shell/command/environment/TermuxAppShellEnvironment.java#L30

>Firstly, the next release is 0.119, so I don't know if there will ever be a 1.0, and secondly I don't know if Termux even uses semantic versioning.

Next version will indeed be `0.119.0`, `1.0` will be released possibly when termux is provided as a library and has more internal refactoring and splitting and possibly TAPM and multiple rootfs support. All termux apps I maintain use semantic versioning since last release. 897d911a
