### ISSUE TITLE
[Bug]: cannot type letters on a numeric keyboard

### ISSUE THREAD

**Issue by bodqhrohro** [termux/termux-app#3487]
### Problem description

I try to use Termux on a smartphone with a hardware keypad (Qin F21 Pro).

When I press a numeric key, a symbol corresponding to its keycode is typed. Tried switching input methods (Kika, QinPad, T9KEYS), playing with software keyboard switches in Termux settings, tapping the terminal area so the virtual keyboard is activated: no luck.

### What steps will reproduce the bug?

1. Plug a hardware keyboard with numeric keys.
2. Install and activate one of aforementioned virtual keyboards.
3. Hit some numeric button.

### What is the expected behavior?

Key presses are propagated through the virtual keyboard correctly. Ideally, only the final symbol is propagated to the terminal, so no side effects because of intermediate symbols in TUI apps and so.

If there are technical obstacles to implement it, I'd like to see some fallback solution. For example, in MidpSSH it's possible to hit a menu item or a shortcut, which opens the platform's text box, with two actions: Type (send verbatim) and Enter (with LF in the end). There are also menu actions like that allowing to send a key sequence with a certain modifier (SHIFT/CTRL/ALT).

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
Updatable packages:
apt/stable 2.7.1-1 aarch64 [upgradable from: 2.3.13-3]
bash/stable 5.2.15-1 aarch64 [upgradable from: 5.1.12-2]
ca-certificates/stable 1:2023.05.30 all [upgradable from: 1:2021-10-26-0]
command-not-found/stable 2.2.0-5 aarch64 [upgradable from: 1.71]
coreutils/stable 9.3 aarch64 [upgradable from: 9.0]
curl/stable 8.1.2 aarch64 [upgradable from: 7.81.0]
dash/stable 0.5.12 aarch64 [upgradable from: 0.5.11.5]
debianutils/stable 5.7-1 aarch64 [upgradable from: 5.5]
dialog/stable 1.3-20230209-0 aarch64 [upgradable from: 1.3-20211214-0]
diffutils/stable 3.10 aarch64 [upgradable from: 3.8]
dos2unix/stable 7.5.0 aarch64 [upgradable from: 7.4.2]
dpkg/stable 1.21.22 aarch64 [upgradable from: 1.21.1]
ed/stable 1.19 aarch64 [upgradable from: 1.17-4]
findutils/stable 4.9.0-2 aarch64 [upgradable from: 4.8.0]
gawk/stable 5.2.2 aarch64 [upgradable from: 5.1.1]
gpgv/stable 2.4.2 aarch64 [upgradable from: 2.3.4]
grep/stable 3.11 aarch64 [upgradable from: 3.7-2]
gzip/stable 1.12-1 aarch64 [upgradable from: 1.11-3]
inetutils/stable 2.4-1 aarch64 [upgradable from: 1.9.4-12]
less/stable 633-1 aarch64 [upgradable from: 590]
libandroid-support/stable 28-3 aarch64 [upgradable from: 28-2]
libassuan/stable 2.5.6 aarch64 [upgradable from: 2.5.5]
libc++/stable 25c aarch64 [upgradable from: 23b-3]
libcap-ng/stable 2:0.8.3 aarch64 [upgradable from: 1:0.8.3-pre1-0]
libcrypt/stable 0.2-5 aarch64 [upgradable from: 0.2-3]
libcurl/stable 8.1.2 aarch64 [upgradable from: 7.81.0]
libevent/stable 2.1.12-2 aarch64 [upgradable from: 2.1.12]
libexpat/stable 2.5.0 aarch64 [upgradable from: 2.4.2]
libgcrypt/stable 1.10.2 aarch64 [upgradable from: 1.9.4]
libgmp/stable 6.2.1-2 aarch64 [upgradable from: 6.2.1]
libgnutls/stable 3.8.0-1 aarch64 [upgradable from: 3.6.16-1]
libgpg-error/stable 1.47 aarch64 [upgradable from: 1.43]
libiconv/stable 1.17 aarch64 [upgradable from: 1.16-3]
libidn2/stable 2.3.4 aarch64 [upgradable from: 2.3.2]
liblz4/stable 1.9.4 aarch64 [upgradable from: 1.9.3]
liblzma/stable 5.4.3 aarch64 [upgradable from: 5.2.5-1]
libmpfr/stable 4.2.0-p9-0 aarch64 [upgradable from: 4.1.0]
libnettle/stable 3.9.1 aarch64 [upgradable from: 3.7.3]
libnghttp2/stable 1.54.0 aarch64 [upgradable from: 1.46.0]
libssh2/stable 1.11.0 aarch64 [upgradable from: 1.10.0]
libtirpc/stable 1.3.3 aarch64 [upgradable from: 1.3.2]
libunistring/stable 1.1 aarch64 [upgradable from: 0.9.10-5]
lsof/stable 4.98.0 aarch64 [upgradable from: 4.94.0-1]
nano/stable 7.2 aarch64 [upgradable from: 6.0]
ncurses/stable 6.4-2 aarch64 [upgradable from: 6.2.20200725-6]
pcre2/stable 10.42 aarch64 [upgradable from: 10.39-2]
procps/stable 3.3.17-2 aarch64 [upgradable from: 3.3.17-1]
psmisc/stable 23.6-1 aarch64 [upgradable from: 23.4]
readline/stable 8.2.1 aarch64 [upgradable from: 8.1.1]
sed/stable 4.9-1 aarch64 [upgradable from: 4.8-2]
tar/stable 1.34-2 aarch64 [upgradable from: 1.34]
termux-am-socket/stable 1.5.0 aarch64 [upgradable from: 1.02]
termux-exec/stable 1:1.0 aarch64 [upgradable from: 1:0.9]
termux-keyring/stable 3.11 all [upgradable from: 2.4]
termux-licenses/stable 2.0-3 all [upgradable from: 2.0-1]
termux-tools/stable 1.38.3 all [upgradable from: 0.155]
unbound/stable 1.17.1-1 aarch64 [upgradable from: 1.13.2-1]
unzip/stable 6.0-9 aarch64 [upgradable from: 6.0-7]
util-linux/stable 2.39 aarch64 [upgradable from: 2.37.2-1]
xz-utils/stable 5.4.3 aarch64 [upgradable from: 5.2.5-1]
zlib/stable 1.2.13 aarch64 [upgradable from: 1.2.11-5]
Android version:
11
Kernel build information:
Linux localhost 4.19.127 termux/termux-packages#1 SMP PREEMPT Thu Oct 28 21:06:46 CST 2021 aarch64 Android
Device manufacturer:
unknown
Device model:
F21 Pro
```

**Comment by tea-enjoyed** [comment]
HI, I have the exact same issue. (Or similar)

I have a CAT S22 Flip which too, has a hardware keyboard on it.
I am able to type numbers, but no letters (because my T9 keyboard client isn't showing up or turning on).
Actually, I tried other keyboard clients (not just T9, QWERTY too) and noticed that the only one that worked is GBoard.
So, for now, the only workaround is to use GBoard (If you have a touch screen on the phone, which is unlikely and also inconvenient for phones with a numeric keyboard, as the screen is too small) or an external keyboard (also inconvenient and you probably need a dongle, might as well just use a laptop or something).
I also noticed that when GBoard is used, it's in a state where it doesn't have autocorrect and displays a number row instead, so maybe Termux tries to launch the client with this "mode", which isn't supported by the client.

A potential fix for this may be to launch other clients without any options, or just launch the keyboard in the normal state. Also, you (the developers) could add support for more clients in the form of a plugin on F-Droid.
If you want to do that, I use Traditional T9 (https://github.com/sspanak/tt9).

The fix seems pretty simple to me. (I don't know, I didn't make this app)
I figured this might help the developers resolve the issue.
Wish y'all the best.

**Comment by bodqhrohro** [comment]
> So, for now, the only workaround is to use GBoard (If you have a touch screen on the phone, which is unlikely and also inconvenient for phones with a numeric keyboard, as the screen is too small) or an external keyboard (also inconvenient and you probably need a dongle, might as well just use a laptop or something).

Or pasting text from another app.

By the way, on another phone with MessagEase, the keyboard's paste gesture is not working in Termux, so I had to paste via the context menu of the terminal only.

**Comment by tea-enjoyed** [comment]
> Or pasting text from another app.

Which is inconvenient too, especially when trying to change directories, install packages, ssh into a device (which is basically the whole purpose of this app.)
Also, wanted to mention that the Kika keyboard isn't working for me either.
The contributors might as well add support for it too, as well as Traditional T9, QinPad, T9KEYS, etc. (Shouldn't be too hard, as they're all T9 keyboard apps and operate in similar ways, if not the same ways.)
I could also do it myself in a new fork but I'm too lazy to learn how to develop Android apps and I barely know Java.

**Comment by tea-enjoyed** [comment]
I tried to use Termux with the Microsoft SwiftKey app (Another keyboard app) on a smartphone and it seems to be working fine.
I think that the app seems to accept normal keyboards, but just refuses to launch T9 clients. (Probably because they're weird and programmed differently)
What I saw on my side, is that it launches GBoard just fine, but when I change keyboards via the options menu in android, it refuses to launch Traditional T9. 
Just like what I said earlier, it's probably due to Termux trying to launch the T9 client with the number row enabled and autocorrect disabled, which isn't exactly possible, and the client just doesn't launch and returns an error.
I could connect my flip phone to my PC via ADB and diagnose the issue, but I'm pretty sure that we already identified the problem here.
In other circumstances, like text messaging, I can switch keyboards just fine and everything goes as expected.

**Comment by tea-enjoyed** [comment]
```
2023-07-09 17:06:29.061  1571-1571  PresentationScreen      com.android.systemui                 D  onNotificationPosted pkg=com.termux ,channelId=termux_notification_channel
2023-07-09 17:06:29.150   387-387   AndroidIME              com...gle.android.inputmethod.latin  I  AbstractIme.onActivate():86 PasswordIme.onActivate() : EditorInfo = inputType=Text imeActionName=UNSPECIFIED dump=[inputType=0x0 imeOptions=0x2000000 privateImeOptions=null actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.termux autofillId=1073741824 fieldId=2131231121 fieldName=null extras=null hintLocales=null contentMimeTypes=null ], IncognitoMode = false, DeviceLocked = false
2023-07-09 17:06:30.875  1374-2217  NotificationService     system_server                        W  Toast already killed. pkg=com.termux token=android.os.BinderProxy@3c3d68e

```

As you can see here Termux seems to be launching GBoard with a bunch of parameters like `IncognitoMode = false` (Incognito mode is disabled) and `hintText=null` (Disables text suggestions).
However, if we look at the initial app launch (a fraction of its log) with the T9 app set as the default on-screen keyboard:

```
2023-07-09 17:14:07.314  1571-1571  PresentationScreen      com.android.systemui                 D  onNotificationPosted pkg=com.termux ,channelId=termux_notification_channel
2023-07-09 17:14:07.402  2333-2333  Termux:TerminalView     pid-2333                             I  IME: finishComposingText()
2023-07-09 17:14:07.409  2333-2333  Termux:TerminalView     pid-2333                             I  IME: finishComposingText()
2023-07-09 17:14:07.430  2333-2333  Termux:TerminalView     pid-2333                             I  IME: finishComposingText()
2023-07-09 17:14:09.174  1374-2576  NotificationService     system_server                        W  Toast already killed. pkg=com.termux token=android.os.BinderProxy@6b10e5f

```
We can see that Termux seems to send a signal to close the on-screen keyboard (which didn't even show up) with the `finishComposingText()` function. I don't know why it does that. It doesn't seem to return an error. It just closes the client. The worst thing is that I barely have experience with Java and found nothing in the code (for now) that seems to accept my theory.

**Comment by sspanak** [comment]
Termux is somewhat special and requires some compatibility workarounds on the keyboard side. 

The main problem is the terminal input field is of [type NULL](https://developer.android.com/reference/android/text/InputType#TYPE_NULL). But usually, this is the type for checkboxes, dropdowns, or other inputs where you can't type, and it usually causes 12-key keyboards to stay invisible.

The second problem is Termux signals it does not want to take suggestions, which makes sense for QWERTY keyboards, but not for 12-key  keyboards because they must always provide suggestions, even if they are not words, but just the list of letters per key. Otherwise, it would be impossible to type.

Anyway, the good news is Traditional T9 now officially supports Termux. Anyone looking for a way to use them together, please try TT9 [v31.0 or higher](https://github.com/sspanak/tt9/releases).

**Comment by bodqhrohro** [comment]
It indeed works now, thanks a lot!
