### ISSUE TITLE
[Feature]: have termux show progress and eta also once job / task done as notification.

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [termux/termux-app#3488]
### Feature description

As said been wondering
Is there a way for termux too show notification on progress and eta also once job / task done?
Kinda always wanted that feature in android since all other apps do and keeps ya posted on progress , like adding arguments to add notification for it
While it's running in background or something not sure which way works best. 

### Additional information

Nope

**Comment by tareksander** [comment]
You can put a call to `termux-notification` at the end of your script.

**Comment by washingleavesandthensome23-434** [comment]
Got am example?

**Comment by tareksander** [comment]
Percent and eta can be shown in text, but you have to calculate it yourself. Anything could be running in a task, so there is no way to query progress easily. Run `termux-notification -h` for help.

**Comment by washingleavesandthensome23-434** [comment]
Is there no way this can be a standard integrated feature? Without having too add stuff too script?

Also termux-notification -h , isn't doing me any good 😕 just confuses me more

**Comment by tareksander** [comment]
Notification once done could be added, but progress updates depend on the program that is run. Notification example: `termux-notification -t "title" -c "content text"`. You can use `-i number` to set a notification id, which will update an existing notification with that id.

**Comment by washingleavesandthensome23-434** [comment]
That would be killer if devs could manage for sure , bout progress/eta ...gonna look into it more, also hope feature merge don't take too long , just noticed last termux release been months ago🙂 I highly appreciate termux for real

**Comment by washingleavesandthensome23-434** [comment]
OK so Been trying it out currently per termux api, since no integration into termux app currently,  noticed some issues,  the api check itself takes 3-4 secs on my script start , that kinda sux

**Comment by tareksander** [comment]
For the start issue, you can check [this](https://github.com/termux/termux-api/issues/552).

**Comment by RalfWerner** [comment]
> since no integration into termux app currently, noticed

@washingleavesandthensome23-434 Termux-API is a plugin of the Termux app for developers who want to use Android functions that go beyond a terminal. A terminal is also not a fortune teller. If **you** do not know how the progress of **your** trial is calculated, Termux does not know either.

**Comment by washingleavesandthensome23-434** [comment]
api check is being done
! termux-api-start 2>&1 >/dev/null | grep -iq error
there maybe a better way to check for it which I may not knowapi check is being done
! termux-api-start 2>&1 >/dev/null | grep -iq error
there maybe a better way to check for it which I may not know

**Comment by washingleavesandthensome23-434** [comment]
api check is being done
! termux-api-start 2>&1 >/dev/null | grep -iq error
there maybe a better way to check for it which I may not know

**Comment by washingleavesandthensome23-434** [comment]
Also:

`$ time -- sh -c '2>/dev/null pkg list-installed | grep -q termux-api && ! termux-api-start 2>&1 >/dev/null | grep -iq error'
real 4.87
user 5.44
sys 0.97`

**Comment by washingleavesandthensome23-434** [comment]
> For the start issue, you can check [this](https://github.com/termux/termux-api/issues/552).

Wow, that's the issue alright, hope it gets fixed soon 🙏

**Comment by RalfWerner** [comment]
Did you [readme](https://github.com/termux/termux-api#Readme)? The output is missing for your action `termux-api-start` [above](https://github.com/termux/termux-app/issues/3488#issuecomment-1616060907). It should be `Starting Service: Intent { cmp=com.termux.api/.KeepAliveService }` or [read](https://github.com/termux/termux-api#Readme) again. I'm not sure whether [this](https://github.com/termux/termux-api/issues/552). has to do with **your issue**. There is a thorough answer of @agnostic-apollo inside.

**Comment by agnostic-apollo** [comment]
As for the original issue, termux itself has no concept of progress of a notifications created with `termux-notification`, progress of what, a copy or move command, a download command, some conversion or processing, termux has no knowledge of it since it doesn't track which commands a user is running and progress of which command a user wants to show. User needs to update the notification themselves depending on what they are running, assuming the utility being used provides a progress. There should be examples of this on the internet if I remember correctly, search... There are examples for tasker, but can be modified for termux, https://www.reddit.com/r/tasker/comments/imr90i/help_adding_progress_notification_to_termux/

Progress can already been shown as a text percentage, support can also be added to show it as a [`ProgressBar`](https://developer.android.com/develop/ui/views/notifications/build-notification#progressbar), but not really a priority at this time and there is already a request for it at https://github.com/termux/termux-api/issues/600

Closing since not an issue of termux-app or termux-api
