### ISSUE TITLE
Native Video Feature Request

### ISSUE THREAD

**Issue by ed1d1a8d** [termux/termux-app#350]
How feasible would it be to add native video support for Termux? I am asking this in the context of this response: https://github.com/termux/termux-packages/issues/878#issuecomment-289184040

**Comment by xeffyr** [comment]
> native video support for Termux?

Since Termux is a terminal, it is not possible to perform output video on it. There are projects like https://github.com/termux/x11-packages - brings some X11/windows support for Termux, but you will have to install either VNC viewer or [Xorg XSDL](https://play.google.com/store/apps/details?id=x.org.server). Maybe, in future Termux will have own addon to perform video output, but for now it is kind of "wontfix".
