### ISSUE TITLE
[Bug]: termux sshd allow arbitrary usernames to login

### ISSUE THREAD

**Issue by NewUserHa** [termux/termux-app#3582]
### Problem description

termux sshd allow arbitrary usernames to log in, and all username will be logged in as the real user name `u0_number`, including `root`.
but it's still protected by the password set by the `passwd` before.

In termux, the `/etc/passwd` is empty.
Should this be fixed?
How is this archived?

### Steps to reproduce the behavior.

1. set sshd followed by https://wiki.termux.com/wiki/Remote_Access.
2. logging in with any username.

### What is the expected behavior?

it supposes that only the correct username can log in.

### System information

* Termux application version: 0.118
* Android OS version: 13

**Comment by TomJo2000** [comment]
This is an intentional patch seeing as Termux is effectively a single-user system.
See: [`packages/openssh/auth.c.patch`](https://github.com/termux/termux-packages/blob/master/packages/openssh/auth.c.patch)

Similar rationale applies to the Termux implementation of [`passwd`](https://github.com/termux/termux-auth), since termux does not have access to a traditional password [hashfile](https://en.wikipedia.org/wiki/Passwd#Shadow_file) such as `/etc/shadow`.
As stated, Termux is a rootless single user environment.
So no default password is set, since none is ordinarily needed for local operation.

Should the user wish to set a password for remote login via SSH, a non-standard implementation of `passwd` is provided which will adequately emulate the functions of the [`shadow` implementation of `passwd`](https://github.com/shadow-maint/shadow/blob/master/src/passwd.c) which are required for remote password login.

SSH login being disallowed without set a password or authorized public key is also an intended default, as otherwise anyone on the same network could log into any running Termux SSHD instance by default.

**Comment by agnostic-apollo** [comment]
Usernames are ignored, you always sign in with the user `sshd` is running with, which is normally the app user unless running it with root.
