### ISSUE TITLE
[Issue]: Input command in terminal programmatically

### ISSUE THREAD

**Issue by m-anshuman2166** [termux/termux-app#3613]
### Problem description

I've been using terminal-view in my project. It works fine but, I require that I programmatically run a command and terminal-view shows its output. I want to run command in TerminalView programmatically inside my activity's `onCreate`.

To do that, I've tried terminal.currentSession.write("... my command"). The command isn't even showing in terminal, let the running part be aside

### Steps to reproduce the behavior.

Try using write function in your terminalSession instance.
Eg : `terminal.currentSession.write("... my command")`

### What is the expected behavior?

The TerminalSession#write function should input the command in the terminal.

### System information

* Termux application version : N.A (Custom implementation)
* Android OS version: 33 (Android 13)
* Device model: RMX3371 (Realme GT Neo 3t)

**Comment by TomJo2000** [comment]
This sounds like an extremely convoluted way to not utilize a [Shell Script](https://en.wikipedia.org/wiki/Shell_script).

Needless to say, this is not a Termux related issue but a mismatch between what you think will solve what you are trying to achive, and the actual solution.
Otherwise known as the [X-Y Problem](http://mywiki.wooledge.org/XyProblem).
