### ISSUE TITLE
[Bug]: port 8022 won't open on Android 13

### ISSUE THREAD

**Issue by divinity76** [termux/termux-app#3677]
### Problem description

port 8022 won't open over WiFi LAN on Android 13. sshd is also unreachable. It worked on Android 12.

### Steps to reproduce the behavior.

nc -l 8022

### What is the expected behavior?

port 8022 should be reachable

### System information

* Termux application version: 0.118.0
* Android OS version: 13
* Device model: Samsung Galaxy S22 Ultra

**Comment by divinity76** [comment]
sorry false bug report, there was another problem

**Comment by TomJo2000** [comment]
If you have not set a password in Termux (using the `passwd` utility),
or otherwise imported a SSH key by appending the Public Key to the `~/.ssh/authorized_keys` file,
you will not be able to log in via SSH.

This is an intentional feature to prevent unauthorized remote access.
For more information please see this previous comment on the matter, which goes into more detail.
https://github.com/termux/termux-packages/discussions/18318#discussioncomment-7345528

**Comment by TomJo2000** [comment]
Additionally I'm not sure listening to Port 8022 with Netcat would even be helpful.

SSH connections are between a server (`sshd` or `dropbear`), in this case Termux.
And a client (`ssh` or PuTTY for example) on the remote side.

The reason Termux's `sshd` (and `dropbear`) bind to port 8022 by default is that Ports below 1024, such as the standard SSH Port, 22 - are "privleged" on Android and as such are not permitted to be used by regular apps.

Typically the connection from a remote host to Termux should bind from the remote host's Port 22 to Port 8022 on the phone running Termux/`sshd`.
```r
[Termux->sshd]:8022 <===> 22:[ssh<-ClientDevice]
# Bidirectional encrypted TCP/IP connection
```
