### ISSUE TITLE
Can the app I'm developing send termux a command?

### ISSUE THREAD

**Issue by rjsteinert** [termux/termux-app#371]
We're developing an app that would be great if we could send Termux a command. In particular, some commands to run a nodejs server.

**Comment by fornwall** [comment]
It's not possible at the moment to send an intent, but it would be nice to add one using custom permissions!

**Comment by rjsteinert** [comment]
Thanks for the response @fornwall. It's hard to express how excited I am about Termux. The potential of having a decent layer on top of Android's very sparse CLI capabilities under the hood. For Android applications we have to lean a lot on Java libraries, and for folks like myself who don't come from a Java background, this is a huge bummer. The potential of leaning on Termux to install things like Node.js so we can write our lower level code in Javascript opens up Android development to 90% of the rest of developers who do not do Java, or do not want to support a port of their library in Java. 

Sending an Intent to run a command would be a nice starting point, but perhaps Termux could be packaged to run inside of an Android app? For example, if it was bundled with Cordova, Javascript developers like myself would be be able to write our non-user facing code in Node, not to mention the power of being able to `exec('custom-cli > something')`. So many possibilities we expect when developing but have been deprived of on Android.

**Comment by danilomo** [comment]
Well, it would be very nice if an application could launch a script by calling startIntent or something like that.

Since this is not possible yet, my solution is to create a daemon for doing this job, using some sort of inter-process communication. The daemon will accept requests from the apps and start the commands for them. It should be manually started, or you can use Termux:boot to run it at boot time.

**Comment by xeffyr** [comment]
Closing in favor of https://github.com/termux/termux-app/issues/804.
