### ISSUE TITLE
[Bug]: 404 not found while pkg upgrade on a fresh installation

### ISSUE THREAD

**Issue by c0m4r** [termux/termux-app#3782]
### Problem description

![image](https://github.com/termux/termux-app/assets/6292788/fd0a5cca-7d65-405c-a0fb-1b51e10700a8)

### Steps to reproduce the behavior.

pkg upgrade

### System information

* Termux application version: 0.101
* Android OS version: 13

**Comment by twaik** [comment]
After installing Termux and opening it, you should do the following:

**1.** `termux-change-repo` (to select a nearby mirror to get updates from):
  - `SPACE` toggles highlighted options;
  - `ENTER` moves to the next screen;
Choose the first/topmost option on each screen. _(If that one fails, try another.)_

**2.** `pkg update && pkg upgrade` (to update your package database, then upgrade all packages)
On each prompt, press `y` and `Enter` to install newest versions available
**3.** `exit` (to exit Termux, so you can restart it yourself, all updated!)

**Termux on Google Play Store is OUTDATED**
Termux and its plugins are no longer updated on the Google Play Store. This is due to API requirements that introduce new restrictions, which break Termux's basic functionality.
Please switch to the F-Droid version!
Direct link: <https://f-droid.org/en/packages/com.termux>
**Before** you install it, You **must** __fully uninstall__ current Termux and all plugins. If you don't, you will get a cryptic `app not installed` error!
(that means uninstalling the main app, as well as Termux:API, :Styling, :Widget, :Task, :Float, :Boot)
If you need help with backing up your files:
<https://wiki.termux.com/wiki/Backing_up_Termux>

**Comment by c0m4r** [comment]
Ah, damn it. I became lost in thought and forgot to install Termux on F-Droid. Sorry for the confusion.
