### ISSUE TITLE
Please make termux movable to "external" adopted storage

### ISSUE THREAD

**Issue by srdegraaf** [termux/termux-app#392]
Hi,

I am trying to use termux on a Samsung Galaxy Tab Pro 8.4" with 16GB internal and 64GB external storage. Tablet is running LineageOS 13.0 (aka Android 6.0.1). Further, I am using nmilosevic's recipe for installing Fedora 25 and 26 under Termux. The problem I am running into relates to Google's inexplicable lack of support for ext4 on external SD cards and the two options I see for using an external SD card with Termux:

1) If I use my external SD card in "adopted storage" mode, Android formats it as ext4 (good), but then I can't move the Termux application to it. Further, termux-setup-storage does not recognize or make links to the external SD card. (In fact, of my "linuxy" apps, only XServer SDL, AndSMB and Hacker's Keyboard appear to be movable, pretty much - for me - defeating the purpose of the external SD card.) I run out of space on the internal SD card fairly quickly, with lots of space wasted on the external SD card.

2) If I use my external SD card in "portable storage" mode, then termux-setup-storage creates links to the external SD card (under /data/data/com.termux/files/home/storage) but since Android formats this as some ridiculous FAT variant (bad), it is useless for installing Fedora onto or for building any of the Linux software that I have written, which exploits/requires UNIX file system permissions.

Consequently, I request that you add the capability of moving the Termux application to external "adopted" storage. By the way, I don't really care that Android thinks my external SD card is "slow" compared to the built-in memory. I can live with slow better than I can live with lack of function.

Your Termux application is - by far - the best Linux under Android solution that I have seen. Unfortunately, all seem to be afflicted by Google's apparent refusal to "support" ext4 - despite using ext4 for Android... I hope the "move" feature is straight-forward to implement. Alternatively, do you have any guidance for how I can accomplish this move?

Thank you!

Dr. Stuart DeGraaf

**Comment by srdegraaf** [comment]
By the way, my tablet is rooted, if that has any bearing on how to make Termux movable to the "adopted storage" ext4 external SD card...

**Comment by sdrausty** [comment]
@srdegraaf Issues https://github.com/termux/termux-packages/issues/1176 and https://github.com/termux/termux-app/issues/376 are related to your question. In the best case scenario $PREFIX and $HOME are mounted from the external micro SD as far as those two issues are concerned. 

Please see https://duckduckgo.com/?q=mount+loop+device+site%3Atldp.org specifically http://www.tldp.org/LDP/LGNET//////////109/chirico.html Since you have root access you should be able to create a couple of large GB files, and mount them in $PREFIX and $HOME as native space on internal device from your external micro SD card. http://www.tldp.org/HOWTO/archived/Loopback-Root-FS/Loopback-Root-FS-3.html should be helpful also. Good Luck!

**Comment by srdegraaf** [comment]
@sdrausty Thanks for this information! I will digest it and give it a shot. Looks like a reasonable approach.

**Comment by sdrausty** [comment]
@srdegraaf I am very glad you have found this information interesting and useful. You are welcome. 

Even though this is a, while possibly not a very basic knowledge topic (think mounting floppy disk or cdrom disk from a file image off disk drive) in linux, for some reason; This is not practiced in Termux.

Please post your accomplishments, your output here... Especially how far were you successful in using nonroot

**Comment by lukas-buergi** [comment]
Why was this closed? I would really appreciate this feature on a fairly locked down tablet without root.

**Comment by xeffyr** [comment]
@lukas-buergi Termux is not moveable due to fixed prefix and special requirements to filesystem.

https://wiki.termux.com/wiki/Differences_from_Linux

**Comment by lukas-buergi** [comment]
> @lukas-buergi Termux is not moveable due to fixed prefix and special requirements to filesystem.
> 
> https://wiki.termux.com/wiki/Differences_from_Linux
I was under the impression adopted storage provided an ext4 file system and mounted the storage to the same place?

**Comment by xeffyr** [comment]
@lukas-buergi Adopted storage is EXT4. But as I wrote above, Termux uses a fixed prefix path, i.e. everything **must be** exactly under `/data/data/com.termux` which is not achievable if app was moved to adopted storage.

**Comment by isrgish** [comment]
** Phone/Tablet must be rooted **
You can move the main psrt of the installation (`usr` folder which has evvery thing in it) to an external card, but it's not for the faint of heart.
Here is the general idea.

1. Format an sd card (or a 2nd partition) as `ext4`.
2. Mount it manually.
3. Copy over the `usr` folder to a folder on the sd card.
4. Delete the `usr` folder from your device.
5. Make a symlink where the usr folder was, which is in `/data/data/com.termux/files` name it `usr`.
6. Viola you've got it done.

The main challange is that once you delete the `usr` folder from your device, you don't have accsess to your full termux installation. What I did was as follows:
1. When you start termux without a full installation, termux installs a minimial version of packages. Since we already have a file named `usr` it installs it as `usr-staging`.
2. I used failsafe mode to rename `usr` which is the link to our termux installation on the sd card. I renamed it to `usr-temp`. Then I renamed `usr-staging` to `usr`. Now I have a working minimal installation.
3. I installed the `tsu` package locally (downloaded in advance).
4. Now I was able to manually mount the sd card.
5. Now I renamed `usr` to `usr-staging` and `usr-temp` to `usr` for this you need to use again a failsafe session ans use `mv` from `/system/bin`.

You can setup a script to run everytime you reboot. I also use Total Commander to run an su command to mount it.
