### ISSUE TITLE
[Bug]: su: not found

### ISSUE THREAD

**Issue by diphons** [termux/termux-app#4014]
### Problem description

su command does't work with latest KernelSU version V1.0

exec: /system/bin/su: not found

This version work fine
F-Droid - Termux Versi 0.118.0 (118)
https://f-droid.org/id/packages/com.termux/

### Steps to reproduce the behavior.

su [enter]

### System information

* Termux application version: 188
* Android OS version: 14
* Device model: Alioth (POCO F3)

**Comment by twaik** [comment]
https://github.com/termux/termux-app/discussions/4000

**Comment by fornwall** [comment]
@diphons This has now have been fixed in version `3.0.6` in `termux-tools` - run `pkg up` to upgrade. Reference: https://github.com/termux-play-store/termux-apps/issues/10

Note that for the Google Play build, issues should be reported to https://github.com/termux-play-store/termux-issues/issues/new/choose for now, as they might very well be specific to the Google Play build (which indeed this was).
