### ISSUE TITLE
Termux crashes when displaying unicode combining accent characters

### ISSUE THREAD

**Issue by duxovni** [termux/termux-app#408]
For example, if I paste in a string containing "x" followed by U+0300, or cat a file containing that string, Termux crashes.

**Comment by xeffyr** [comment]
Closing as issue is outdated and not reproducible anyway.

No crash on `x` followed by U+0300 (`\xCC\x80`).
![Screenshot_20210203-193955](https://user-images.githubusercontent.com/25881154/106787055-e54abb00-6657-11eb-9526-635ee6aabcc2.png)

Maybe was fixed in one of previous releases or is device-specific.
