### ISSUE TITLE
su problem on Nougat with Magisk-14.0

### ISSUE THREAD

**Issue by HJarausch** [termux/termux-app#423]
First, using a Linux terminal other than Termux, the command
/sbin/su   (which is linked to /sbin/magisk)
works just fine.

But, when executing
/sbin/su
within Termux I get
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "OpenSSL_add_all_algorithms" referenced by "/system/lib/libsqlite.so" ...

On a different device running Marshmallow this doesn't happen.
ldd /sbin/magisk shows
libsqlite.so libselinux.so liblog.so libstdc++.so libc.so libm.so and libdl.so

On my Nougat device the missing symbol  'OpenSSL_add_all_algorithms'  is defined in
/system/lib/libcrypto
but not in 
/data/data/com.termux/files/usr/lib/libcrypto.so

So, the LD_LIBRARY_PATH is hurting here.

**Comment by HJarausch** [comment]
Sorry for the noise.
Termux's own su command does work (it unsets LD_LIBRARY_PATH)

By the way, with current Magisk (up to version 14.0), su -p does NOT preserve the environment.
The author of Magisk has promised me to fix this soon.
In the meantime I do the following just after su

. `pwd`/mysu.rc

where mysu.rc has the following lines:

pm grant com.termux android.permission.READ_EXTERNAL_STORAGE
pm grant com.termux android.permission.WRITE_EXTERNAL_STORAGE
export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
export PATH=$PATH:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets

**Comment by sjevtic** [comment]
I am seeing this exact problem as well (v0.59; all packages current), and Termux seems like it would be the best place to fix it since it since it looks like the shared libraries that ship with Termux don't include dependencies that are required by a lot of the system binaries in Android N.   I can work around the issue as suggested in #398 by putting /system/lib64 ahead of the Termux shared library directory:

`LD_LIBRARY_PATH=/system/lib64:/data/data/com.termux/files/usr/lib`

But this results in a paradox.  Since many Termux libraries and system libraries share the same names, the resulting collision causes Termux executables to use the system libraries that don't have dependencies required by the Termux executables.  Even apt doesn't work.

None of this was a problem on Android M, presumably because the system binaries had fewer dependencies that were fulfilled by the Termux libraries.  In the meanwhile though, I am constantly changing my LD_LIBRARY_PATH, depending on whether I am trying to run a Termux binary or a system binary.  It's painful.
