### ISSUE TITLE
Usable on 2nd user?

### ISSUE THREAD

**Issue by bharat226g** [termux/termux-app#46]
Termux app when installed in 2nd user and opened, complains that it can only be installed on primary account. 

Can it be made usable on 2nd user? Only for those commands not requiring superuser access.

**Comment by fornwall** [comment]
Unfortunately not! Since the app doesn't use chroot to setup a virtual file system it means that packages are built assuming that `/data/data/com.termux/files/usr` exists, which doesn't work for non-primary user accounts.

It may be changed in the future, but it's not something that's going to be done in the short term.

**Comment by timaschew** [comment]
Any news on this?

**Comment by xeffyr** [comment]
May be implemented in process of fixing https://github.com/termux/termux-app/issues/1072, but not before.
