### ISSUE TITLE
Volume keys don't seem to work on CM12.1 (bacon)

### ISSUE THREAD

**Issue by inducer** [termux/termux-app#5]
The volume keys don't seem to work on Cyanogenmod 12.1 on my OnePlus One. When I hit VolDown+d, the device vibrates as long as hold VolDown, and the "d" shows up as if nothing had happened.

**Comment by fornwall** [comment]
Hi, thanks for reporting!

I don't have a Cyanogenmod device available at the moment. In order to help diagnose the issue, can you check if the volume buttons work as shortcuts in TEA (check that settings says that Control key is Vol Down Key):

https://play.google.com/store/apps/details?id=jackpal.androidterm

**Comment by inducer** [comment]
You know what--this is totally my fault. I have (had) the volume keys mapped to Cursor right/left. (CM will let you do that.) This then obviously messes up your handling of these keys.

**Comment by fornwall** [comment]
Ok, thanks for the information, and great that it works for you now!

**Comment by r0bis** [comment]
You are a star. Has the same issue in CM13 - sorted now
