### ISSUE TITLE
SSHD running after exiting Termux

### ISSUE THREAD

**Issue by aneutron** [termux/termux-app#510]
Hey, first of all, thanks to the devs for the amazing work they're doing.

I noticed that when starting sshd and then exiting Termux, one can still acess the sshd server. Now it's normal given that it's a daemon and it should be running, but I still wanted to open a ticket for two main reasons:
- If it's not the desired behavior and it is a bug, then probably add it to the pending list.
- If it's not a bug, maybe reconsider the pros and cons of such policy, because particularly for SSHd and no _fail2ban-like_ system, it could pose a threat to the user if the sshd server is always running. 

Anyway, thanks for the amazing work ladies and gentlemen.

**Comment by Grimler91** [comment]
By exiting termux you mean closing all sessions I presume? 
That's comparable to logging out of all sessions on a normal Linux system (I.e. computer still running but no one logged into it), which would also leave services running.

I could agree that this might not be intuitive though. We could consider writing "close session" or "logout" instead of exit. Let's see what other people think.

**Comment by xeffyr** [comment]
> it could pose a threat to the user if the sshd server is always running.
Termux's SSH uses key-based authentication, so there no passwords. Is someone can brute force RSA or ED25519 (or such) keys ? I guess that no.
But it should be possible to compile and use tools like fail2ban or sshguard.

**Comment by aneutron** [comment]
Agreed, brute forcing an RSA key or any asymkey is quite unrealistic for normal actors. I guess maybe just close the issue then :+1:
