### ISSUE TITLE
Can we create an addon like Termux:Widget that would emulate the kernel mount subsystem? 

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-app#511]
Is there a possibility to create something like Termux:Widget that would emulate the kernel subsystem? Or a Termux package?  This should enable much space on devices.  Referencing issue https://github.com/termux/termux-app/issues/376

**Comment by xeffyr** [comment]
Not, we cannot create.

How much space you need for Termux ? I guess that typical Termux user use less than 4 GB on internal storage for packages and some data in home directory. For other files it is possible to use external sd card without root.

**Comment by xeffyr** [comment]
Why not use an emulator such as QEMU for this. With emulator you can run a desktop OS without root but will be slower. QEMU is already available in https://github.com/xeffyr/termux-x-repository

**Comment by sdrausty** [comment]
@xeffyr this issue is about filesystem space on devices, which includes the possibility of emulators.  Can QEMU mount these  `-rw-rw----  1  1149593340 Oct 21 03:12 hello -rw-rw----  1  2299186680 Oct 21 03:31 hello2  -rw-rw----  1 26440646820 Oct 21 05:33 hello3  -rw-rw----  1 48350334976 Oct 21 06:19 hello4` as filesystems?  **`adduser` and groups complements this topic** regarding complete control of application user system space.  This topic particularly references creating a massive file(s) on an external microSD that is(are) mounted in an Android application's userspace ($HOME/mountpoint and $PREFIX/tmp and similar).  See https://duckduckgo.com/?q=mount+loop+site%3Atldp.org&ia=web and https://github.com/termux/termux-packages/issues/1176 for more information about mouting loop devices in Linux.

**Comment by xeffyr** [comment]
This is for what emulators is. If you will run entire OS via user application you will can do nearly everything (not sure about this, but ping works without rooted host).

No one can/will implement a userspace emulated `kernel` or `mount emulation for ext4fs/fat`. No one will create an os emulator specially for Termux. **This will be very hard and it isn't worth it. If this feature was important for many people, then it would be done years ago.**

If your phone has small amount of memory, then buy new =). Or you need a hundreds of GBs in your phone/tablet ?
**OS images don't need to have executable bit set so they can be placed on external storage. And to mount a loop images, you have only two choices: root your device or use an emulator.**

Now about `adduser` and `groups`. Android's bionic C library does not support user lists as gnulibc, instead of this it use a hardcoded rules for user/group privilege separation. For more information, you can see file [android_filesystem_config.h](https://android.googlesource.com/platform/system/core/+/master/libcutils/include/private/android_filesystem_config.h) which is part of Android source code.
This file has these lines:
```
#define AID_APP_START 10000 /* first app user */
#define AID_APP_END 19999   /* last app user */
```
So first app user will be ```u0_a0``` and last user ```u0_a9999```, and you can have only ONE user per application but you can switch between them if you have root permission (via `su`). **Programs such as `adduser` will be useless in Android.**
