### ISSUE TITLE
A Little Padding?

### ISSUE THREAD

**Issue by lokesh-krishna** [termux/termux-app#516]
Text is pressed right against the edges of the screen presently. It would be really nice if padding were added. The most minimal amount possible but just enough to avoid this:

![screenshot_20171228-083845](https://user-images.githubusercontent.com/20235646/34399135-733ca770-eb7c-11e7-87eb-cb0aa5ccc143.png)

**Comment by Quasic** [comment]
Wow, my device is black, so I never noticed. How much padding do you think is necessary? I value screen space, but black isn't the only device color... I wonder if it could be made a setting.

**Comment by sdrausty** [comment]
Some devices are black.  A number are white.  A few are in many colors.  This topic is superfulous as every screen regardless of device color has a black border embedded in the glass surrounding the LED screen.  Some of these borders are wider than others, but this doesn't make any difference since it is black.  If device color should not appeal with Termux's default screen setting for the user, an addon is available. It is called Termux styling!  More information about your solution for this topic through the Termux Styling Addon is at this https://termux.com/add-on-styling.html link;  Enjoy.

**Comment by lokesh-krishna** [comment]
The request is not related to the color of the device at all. It is purely about the content being pressed right to the edges of the screen without any padding, which in my opinion just doesn't look very polished. It even looks almost like text is getting cut off at times. 

A simple 1px wide border on all sides should suffice, not compromising on screen real estate but still offering a better appearance.

**Comment by sdrausty** [comment]
> has a black border embedded in the glass surrounding the LED screen. Some of these borders are wider than others, but this doesn't make any difference since it is black. 

Hence, every screen has built in black padding which consumes no LED screenspace.

**Comment by Grimler91** [comment]
@sdrausty @lokesh-krishna Devices with curved screens/infinity edges/whatever you want to call it, that black border is pretty much none-existing.

It is quite hard to mark text all the way to the edge, I agree that padding, or an option to add padding, would be nice.

**Comment by sdrausty** [comment]
@Grimler91 @lokesh-krishna 
> It is quite hard to mark text all the way to the edge,

It is impossible to mark text all the way to the left edge of the screen.  Dragging the visual mode cursor one line up at the extreme right side of the screen accomplishes marking text all the way to the left border of the screen.  Adding 1px of padding will not change this text marking event whatsoever.  

> black border is pretty much none-existing
Many devices have a relatively large frame, even the ones that claim they do not have a picture frame so to say.  What is more, usually this picture frame comes in black, and this is because of a couple important reasons.  The thinnest padding encountered is about a couple of pixels wide frame around an LED IMOL and similar LED screen display.  

Either way smartphones and tablets come with padding, just like computers.  Take a closer look at the command window in Windows (tm).  Does it have padding? How about a CLI window in Linux?  Is there any padding in these examples?  

> an option to add padding, would be nice.
Possibly, but aren't there more important things like https://github.com/termux/termux-app/issues/465 Convert text navigation gestures into arrow key inputs and https://github.com/termux/termux-app/issues/12 Add overlay keyboard with Alt, Ctrl, Tab, arrow keys (and a few more keys) #97 to name two of many important issues.  This topic is superfluous:
```
unnecessary, especially through being more than enough: 

"the purchaser should avoid asking for superfluous information"


synonyms: surplus (to requirements) · nonessential · redundant · unneeded · excess · extra · (to) spare · remaining · unused · left over · in excess · waste · unnecessary · unneeded · 
[more]
```

Since we are on the topic of improving the app, what happened to the fly out menu full screen feature?  It appears to have disappeared with v0.59.  It was bomb!

**Comment by sdrausty** [comment]
@lokesh-krishna

> Take a closer look at the command window in Windows (tm). Does it have padding? How about a CLI window in Linux? Is there any padding in these examples?

Exame your screenshot closely.  The letters have perfect padding.  The capital L stands out nicely, doesn't it?  The capital W letters look way sexy to me.  How about you?  Don't you like their proximity to the left edge of the screen?  The big  I letters are awesome.  How they stand so impressively tall!  What about the L and the M?  I see a little padding at the left edge of the screen.  Do you see the padding now too?

**Comment by lokesh-krishna** [comment]
>  The letters have perfect padding. The capital L stands out nicely, doesn't it? The capital W letters look way sexy to me. How about you? Don't you like their proximity to the left edge of the screen? The big I letters are awesome. How they stand so impressively tall! What about the L and the M? I see a little padding at the left edge of the screen. Do you see the padding now too?

Not sure if this is sarcasm but just for the record, no, I don't think they have perfect padding. They could definitely use a little. 

As for the topic's value, it can easily be managed with tags for priority and even then, this is hardly going to be a blocker to those other issues you mentioned. If someone is able to make this happen, let them.

**Comment by sdrausty** [comment]
@lokesh-krishna I was admiring your screenshot.  Hence, I wrote a short poem of gratitude toward your work, the screenshot with the presentation.  

> I see a little padding at the left edge of the screen. Do you see the padding now too?  

Perfection is in the eye of the beholder.  Do you agree?

**Comment by Quasic** [comment]
I have a curved screen. I don't see a border, but it may be hard to tell, since it's all black.

**Comment by Spencer-H** [comment]
Some padding would be amazing

![20180705_234705](https://user-images.githubusercontent.com/14956139/42359122-2d1199f0-80ae-11e8-8a63-79d1f40313f9.jpg)
