### ISSUE TITLE
Install bootstrap.zip from local

### ISSUE THREAD

**Issue by Wolfram-Wolf** [termux/termux-app#521]
Earlier mentioned in issue #1, resulting in pull request #242 (which was not merged). Frequently flashing new ROMs means installing Termux again and again (downloading the bootstrap.zip every time). It would be highly convenient to be able to manually select a bootstrap package (from say /sdcard) when Internet is not available.

Best wishes.

**Comment by Wolfram-Wolf** [comment]
Any particular reason why this feature is being ignored? Lack of time... dissatisfaction with the idea... requires too much remodelling of code (meh!)... security issue...?

**Comment by Grimler91** [comment]
I would guess that it is due to lack of (free)-time that this and the other 147 issues (in this repo, and 322 in termux-packages) hasn't been resolved. 

I agree that it would be a nice feature and helpful for people that can't download the bootstrap, or that reinstall termux a lot as you said. 
#242 isn't the best way to implement this though. It bloats the app a lot since zips for all arches are baked into it. 
I imagine instead getting a dialog where the user can either choose to download the zip from the normal url, write a custom url or choose a local file. 

Best way to speed up the incorperation of this feature would be if someone implemented it (properly) and opened a pull request.

**Comment by 2EASY4HACK** [comment]
![screenshot_termux_20181027-222855](https://user-images.githubusercontent.com/42806798/47606012-44acd000-da38-11e8-9bd0-8a3595c3b5fe.png)
Please Help Me:(

**Comment by xeffyr** [comment]
@2EASY4HACK Connection interrupts may cause this.

**Comment by Wolfram-Wolf** [comment]
Closing issue in favour of the high speed distribution system.
