### ISSUE TITLE
Startup script

### ISSUE THREAD

**Issue by tondy67** [termux/termux-app#537]
When Android refresh the Termux app it start with it initial screen and I lose my work - path, current command  etc.
It's not ok for  runnig in background script.
So, It is possible to implement a startup script in settings which will be executed when termux start?
Or autosave sessions?
Great work. Thank you :)

**Comment by Grimler91** [comment]
What do you mean with "when android refresh the termux app"? Does android force-close termux?
(In that case probably due to memory shortage or similar) I've not experienced the same issue and usually have termux sessions running for days.

As for local settings that you want in every session, you can put it in ~/.bashrc. 
This file is sourced by every new terminal/session. 

If you want to run a script/start a daemon/similar when you start your device then you can look into https://github.com/termux/termux-boot#termuxboot which aims at helping with this.

**Comment by tondy67** [comment]
Hm, my device has 1GB memory. When I start termux, browser and editor and switch between them sometime termux lose it sessions and show me it initial screen
I meen "in backgrund" in terms of Android.
bashrc is a good hint. I'll try it. 
Thank you :)

**Comment by Grimler91** [comment]
@tondy67 I can't say for sure why your device closes termux, but at least [some android versions](https://android.stackexchange.com/questions/93545/apps-are-automatically-closing-restarting-and-phone-is-running-slow) force-closes apps when the RAM is running out, could be that this is happening to you. 

Anyways, glad to be of help.

**Comment by tondy67** [comment]
No. Android not close it. It is running. It only lose it session. It returns to home folder, welcome message etc. Maybe the problem is a my old tablet. Thank you again :)

**Comment by Quasic** [comment]
It happens to me too, but I thought it was actually closing, like after pressing exit. (The tab stays in recent apps, and it opens a new session when chosen.) Sometimes I can keep a session going for days, other times it loses the session when the timer rings or some other simple thing happens.

**Comment by tondy67** [comment]
The 'bashrc' works as expected. This resolve the problem with losed session. I still need to confirm when it happens automagically :)

**Comment by tondy67** [comment]
Well, I can confirm it. This happens when the device is not restarted long time and/or after switch off/on it. So I put one line in my bashrc file and voila :)
$ nano ~/.bashrc
# Start myscript.sh if it not
pidof myscript.sh || ~/myscript.sh
