### ISSUE TITLE
Building PHP error!

### ISSUE THREAD

**Issue by Anoxia** [termux/termux-app#548]
When i Building PHP in termux error with "/tmp not exist" , Please tell me how to make the parameters. Thanks!

**Comment by Grimler91** [comment]
See https://wiki.termux.com/wiki/Differences_from_Linux#Prefixed_System.

Since termux is a prefixed environment you need to patch the sources and replace "/tmp" with /data/data/com.termux/files/usr/tmp.
You might/will probably run into similar problems related to /etc or /usr. 

Why are you building the package instead of installing the one available through apt?

**Comment by Anoxia** [comment]
Thanks, I want to get a custom minimized package and learning more related knowledge.

**Comment by Grimler91** [comment]
@Anoxia It would be way easier to cross-compile the package from docker/ubuntu if you have access to a computer.
You can use the working [build script](https://github.com/termux/termux-packages/blob/master/packages/php/build.sh) and tweak it however you want. 

See the readme on how to setup a build environment in [ubuntu](https://github.com/termux/termux-packages#build-environment-without-docker) or [docker](https://github.com/termux/termux-packages#setting-up-a-build-environment-using-docker).

**Comment by Anoxia** [comment]
Thanks again! I'll try it.
