### ISSUE TITLE
Add adaptive icon

### ISSUE THREAD

**Issue by flipflop97** [termux/termux-app#552]
[Adaptive icons](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html) make app icons more consistent, it would be nice if Termux had one too.

**Comment by flipflop97** [comment]
Nvm, I meant to post this to Tilix.

**Comment by c-e-p-x-u-o** [comment]
Please add support for icon shape
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

**Comment by moneytoo** [comment]
So which would it be?

![adaptive](https://user-images.githubusercontent.com/1071643/41831284-5982f094-7846-11e8-8472-9822cc9c781d.png)
I like the elegance of number 3 but just black icons easily blend with dark/black backgrounds - leaving just small white rectangle.

My favorite would be number 6. 

Please ignore the sizes. Now I realized that the terminal icon should be just a tiny bit smaller.

**Comment by c-e-p-x-u-o** [comment]
awesome!

Yes, 3 is nice, but may be invisible.

Really I can't prefer one of them, all are cool.

**Comment by flipflop97** [comment]
Nice work! 2, 3 and 5 look the best imo.

**Comment by fornwall** [comment]
I think it looks good!

**Comment by fornwall** [comment]
I'm fine with a PR! We can release it and see what people think.

**Comment by lokesh-krishna** [comment]
Please review #762.

**Comment by c-e-p-x-u-o** [comment]
It will be invisible on black background!

**Comment by lokesh-krishna** [comment]
True, if the background is #000000. If you're talking about the background of the app drawer when using a dark wallpaper on Android 8.1, the black used in this icon is darker than the background and can be distinguished. Also, the problem of blending in is reduced by using two characters rather than the single block.

The problem of blending in is also present when slapping icons onto a white plate such as Google has done with several of their icons as the background is barely visible or sticks out in a bad way on white backgrounds. I don't know how to address it when using black or white.

I could use different colors (I love the [Nord color scheme](https://github.com/arcticicestudio/nord) so maybe the background and foreground colors from that color scheme or any other color scheme that we can arrive at a consensus for) but these colors reflect the default Termux color scheme and that's why I went with them.

Here's what the icon would look like with the background and foreground colors from the Nord color scheme:

![screenshot_2018-07-06 adapticon](https://user-images.githubusercontent.com/20235646/42356278-3f567072-80ef-11e8-84a8-ebfe3bb883be.png)

**Comment by lokesh-krishna** [comment]
> Moreover, what `>` means?

Interesting question. This proved to be an interesting read: [Why is >_ used as a terminal icon anyway?](https://www.reddit.com/r/linux/comments/5sn4k7/why_is_used_as_a_terminal_icon_anyway/).

**Comment by xeffyr** [comment]
@lokesh-krishna, @c-e-p-x-u-o  Probably that `>` is a last symbol of DOS console prompt (full is like `C:\>`). But anyway this is a 'terminal' so I don't see anything wrong with that. Also, default prompt for fish shell ends in `>`.

**Comment by brunelli** [comment]
Should this be fixed by #762?

I've updated to v0.65 but Nova still displays the legacy icon inside a background, not the adaptive one.

**Comment by lokesh-krishna** [comment]
I'm using the OmniROM stock launcher and the adaptive icon shows up properly on it. Could you test any different launcher to see if this is something exclusive to Nova?

**Comment by brunelli** [comment]
Yes, just tested in Pixel Launcher and Action Launcher, both still shows the round icon. 
I'm running Sony's stock Android 8.0 on a Xperia X.

**Comment by c-e-p-x-u-o** [comment]
The adaptive icon shows up properly on Lineage 15.1
But it looks bad on the dark background. (Blurred Lines live wallpaper)
![img_20180806_133049](https://user-images.githubusercontent.com/14617699/43711943-18f78370-997d-11e8-9272-b93f83134d75.jpg)

**Comment by lokesh-krishna** [comment]
@c-e-p-x-u-o There's a PR (#797) to try out an alternative color.

Out of curiosity what's that app with an omelette for an icon.

**Comment by c-e-p-x-u-o** [comment]
scrambled exif, it removes metadata from the photo

**Comment by andreyorst** [comment]
I'd like to add a note about icon.

Old icon was way more stylish, and unique, despite simple design. The whole idea of adaptive icons was bad, because it adds more restrictions to design, and doesn't provide any real benefits except new visual effects, which are not that important, since we're looking for icon on desktop, and usually drop our attention after finding it, because app if find, and already opening. Since 90% of time is spent on search for icon in menu/desk, 5% on icon animations animations (because it's really fast), and 5% on launching animation (because it's as same as fast as icon animation), icon animations are not prior here. Old icon was easy noticeable on both dark bg (desk, with dark wp) and light bg (menu in stock android). New icon is really annoying since I tend to use `#000000` background on my desk.

If adaptive icons could have different background which isn't just cropped, it could be more flexable, and old icon could be easily adapted.

So I agree with https://github.com/termux/termux-app/issues/552#issuecomment-399833763 and number 6 is the best out there. Yet the old variant was better than any other in my opinion

**Comment by tomty89** [comment]
What I don't understand most is why we end up going "Nordic".

**Comment by c-e-p-x-u-o** [comment]
Should be closed, right?
