### ISSUE TITLE
32 bit binary on aarch64

### ISSUE THREAD

**Issue by zpimp** [termux/termux-app#567]
i want to run 32bit binary (xidel, not provided by termux) have 64bit android
https://sourceforge.net/projects/videlibri/files/Xidel/

on first terminal it works (with a small delay)

if i try to run it on a second terminal (session/tab) it says
`CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 64-bit instead of 32-bit
page record for 0xf727a04c was not found (block_size=64)`

why does it work on one and not the other?
what can be done?

**Comment by fornwall** [comment]
Try `unset LD_PRELOAD` before executing the 32-bit binary.

Termux uses `LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so` to inject a shared library which overrides exec() so that normal shebangs (`#!/bin/sh` and similar) works, but that does not work when trying to execute 32-bit binaries, as the library is 64-bit.

**Comment by zpimp** [comment]
thank you
unset LD_PRELOAD
seems to work

**Comment by Akronox** [comment]
Fenomenal...me funciono unset LD_PRELOAD
