### ISSUE TITLE
Unable to install any termux addon (api, widget, styling)

### ISSUE THREAD

**Issue by baconicsynergy** [termux/termux-app#57]
Any time I attempt to install any addon, the error message "Cannot install due to unknown error". Using termux 0.29, Verizon Galaxy S6, android 5.1.1.

**Comment by Neo-Oli** [comment]
Could this be a Play Store Issue? Can you install from F-Droid? https://f-droid.org/repository/browse/?fdfilter=termux

**Comment by fornwall** [comment]
All Termux add-ons needs to be signed with the same key, which means that you cannot e.g. install Termux from F-Droid and termux-styling from Google Play (or vice versa), since F-Droid uses a custom key for signing. Could this explain the problem?

**Comment by baconicsynergy** [comment]
I'll reinstall from F-Droid and see what happens

**Comment by baconicsynergy** [comment]
That completely solved the problem, how foolish of me. Thanks!

**Comment by BeastF5** [comment]
Can't install termux styling  from F-droid how to enable termux styling in termux

**Comment by mangodan2003** [comment]
First, I have always installed termux via F-droid, not google play. I recently tried to install the API addon but it wouldn't work, shows  the error re signing keys. I realised my termux install hadn't been updating and was many versions old and had to completely uninstall and reinstall it due to the same errors. now at 0.108. However I still cannot install either API or Widgets addons, both have no install but and under versions show just an "update" button. I do not have these installed already, and none of the available versions have the installed emblem. If I press the update button I get the error re signed with a different key to the old one.
In the end i managed to get it installed by manually downloading the APK from the fdroid website.
