### ISSUE TITLE
Error when running any pkg command, v0.60

### ISSUE THREAD

**Issue by yankee14** [termux/termux-app#601]
```
$ pkg update 2> debug; cat debug
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://termux.net stable InRelease: Couldn't create temporary file /tmp/apt.conf.bg7IGM for passing config to apt-key
W: Failed to fetch https://termux.net/dists/stable/InRelease  Couldn't create temporary file /tmp/apt.conf.bg7IGM for passing config to apt-key
W: Some index files failed to download. They have been ignored, or old ones used instead.
E: Couldn't create temporary file to work with /data/data/com.termux/files/usr/var/lib/apt/lists/termux.net_dists_stable_InRelease - mkstemp (2: No such file or directory)
E: The package lists or status file could not be parsed or opened.
```
I have this same issue on two different devices.

I installed the Termux v0.60 update released 1/29/18 from F-Droid on my (LS980) LG G2, and this error appeared. I also installed it on an (LS998) LG V30+, and it has the same issue.

**Comment by Grimler91** [comment]
Are you logged in to a ssh shell? TMPDIR seem to be missing. Try `export TMPDIR=$PREFIX/tmp`.

**Comment by Grimler91** [comment]
Your bashrc does `export TMPDIR=/data/local/tmp` so I can't see why apt tried accessing `/tmp/`, 
might be something we want to patch in apt. 

Anyways, good that it works again.

**Comment by Grimler91** [comment]
apt checks for the TMPDIR env dir and makes sure that folder exists and is readable. I'm not sure if `/data/local/tmp` is readable for non-root apps normally, it doesn't seem to be on my android nougat device. 

When apt can't read/write to your TMPDIR folder, it falls back to the default `/tmp`, and fails since this is termux. I'll open a pull request later and make it fall back to `$PREFIX/tmp` instead.
