### ISSUE TITLE
Unable to install Nodejs

### ISSUE THREAD

**Issue by Vm900** [termux/termux-app#616]
Hi
Been trying to install nodejs for days without any success.
I keep getting the following error messages:
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/nodejs_8.10.0_arm.deb(--unpack): corrupted filesystem tarfile -corrupted package archive
dpkg-deb (subprocess): decompressing archive member: Izma write error: Broken pipe
dpkg-deb: error: <decompress> subprocess returned error exit status 2
Errors were encountered while processing:
/data/data/com.termux/files/usr/var/cache/apt/archives/nodejs_8.10.0_arm.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
-----------------            ----__x_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Please Help
Thanks

**Comment by ExtremeNerd** [comment]
Did you try install via Termux repo or official tarball? If official install, too does not work, NVM may work still.. Try installation via NVM.

**Comment by l-jonas** [comment]
@Vm900 Does ```pkg install nodejs``` work? It installs version 8.11.2 (the latest LTS version).

**Comment by goodevilgenius** [comment]
I tried `nvm`, and it doesn't work on Termux because `nvm` doesn't work if `PREFIX` is set. It shows an error saying it doesn't work if `PREFIX` is set.

I tried to get around it by doing the following:

```bash
PREFIX= nvm use --delete-prefix stable
```

This let it use the proper version, and `npm` and `npx` both worked, but `node` failed. I suspect `node` and `npm` have some conflict with the `PREFIX` and the way `nvm` sets it.

There's more info at https://github.com/creationix/nvm/issues/1645#issuecomment-396709449

But, I am able to use the version from the regular repos. Just `pkg install node`, and it works fine. Unfortunately, it's only 9.11.1, instead of the most recent version.

**Comment by ljharb** [comment]
Specifically, `npm` itself uses `$PREFIX` - so the collision means that Termux chould maybe alternatively support `$TERMUX_PREFIX`, and then Termux users could use either one, but node/npm users could use the termux-specific one?

**Comment by ExtremeNerd** [comment]
Is that possible to normally install the ARM binary tarball provided on NodeJS website?

**Comment by Vm900** [comment]
@goodevilgenius Yep it works but it installs an earlier version not the latest
