### ISSUE TITLE
Cant delete file

### ISSUE THREAD

**Issue by leetree2001** [termux/termux-app#633]
![20180323234658141ad7234f07966f](https://user-images.githubusercontent.com/5876253/37860632-73de864e-2ef7-11e8-978b-9454b08c87fb.jpg)

![20180323234457141ad7234f07966f](https://user-images.githubusercontent.com/5876253/37860639-9bd91574-2ef7-11e8-8c64-26669be47e5c.jpg)

no such file.

**Comment by ph4z0n** [comment]
You have to enclose filenames within "full quotation marks" because ampersand ('&') is a shell built-in, causing everything following it to be executed as a separate background task.

See: [Job Control] 
http://tldp.org/LDP/abs/html/x9644.html

And:

http://www.tldp.org/LDP/abs/html/internal.html

In the future post actual text output instead of an image of said text; mayhaps consider helping oneself before stuffing the issue tracker with matters unrelated to 'termux' and which are already thoroughly documented.

**Comment by leetree2001** [comment]
Thank you

**Comment by ph4z0n** [comment]
@leetree2001, I'm mistaken: ampersand (&) causes everything _before_ it – not following – to be forked and run as background jobs.

My apologies.

(Also: using '&&' will execute one command then another in succession. e.g. 'apt update && apt install screen' will first update repo, then install GNU Screen after update command completes)
