### ISSUE TITLE
Repository no longer signed

### ISSUE THREAD

**Issue by yochananmarqos** [termux/termux-app#635]
I get the following running `apt update`:

```
Ign:1 https://termux.net stable InRelease
Get:2 https://termux.net stable Release [1183 B]
Ign:3 https://termux.net stable Release.gpg
Reading package lists... Done
E: The repository 'https://termux.net stable Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

However, I was able to install `curl` by running `pkg install curl` and it used the repository just fine. 

Termux 0.60
Android 8.1
Nexus 6P

**Comment by Grimler91** [comment]
Still a problem? I'm unable to reproduce.

**Comment by yochananmarqos** [comment]
It must have been a temporary server issue, it's working fine now

**Comment by ancientzords** [comment]
I have problem like that

$ apt update
Get:1 https://xeffyr.github.io/termux-x-repository termux InRelease [2039 B]
Hit:2 https://termux.net stable InRelease
Err:1 https://xeffyr.github.io/termux-x-repository termux InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 45F2964132545795
Ign:3 https://hax4us.github.io/termux-tools termux InRelease
Hit:4 https://hax4us.github.io/termux-tools termux Release
Ign:5 https://hax4us.github.io/termux-tools termux Release.gpg
Reading package lists... Done
W: GPG error: https://xeffyr.github.io/termux-x-repository termux InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 45F2964132545795
E: The repository 'https://xeffyr.github.io/termux-x-repository termux InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by Fernal73** [comment]
I received the same error message while trying to install tigerVNC.

**Comment by xeffyr** [comment]
> trying to install tigerVNC.

The correct way to install `tigervnc` is:
```
pkg install x11-repo
pkg install tigervnc
```
https://wiki.termux.com/wiki/Graphical_Environment
