### ISSUE TITLE
Temp never gets cleaned

### ISSUE THREAD

**Issue by easyaspi314** [termux/termux-app#636]
/data/data/com.termux/files/usr/tmp should probably get cleaned whenever Termux does a cold start, or after a reboot.

For example, the sorin-async prompt creates a unique temp file each time you open a shell. Granted, it is zero bytes, but the point is that nothing ever gets deleted.

**Comment by Grimler91** [comment]
One pretty interesting idea is to use the standard cache dir in android. There was a pull request from @xeffyr here: https://github.com/termux/termux-app/pull/478 to do that.

**Comment by xeffyr** [comment]
@Quasic symlink to cache is should be only **temporary** solution as this directory can be accidentaly cleaned when using 'cleaner' apps (e.g. my device have such app embedded into rom). This may lead to broken tmux sessions, possible data loss and such.
Proot-related tools will also show error if /tmp is a symlink to cache dir: `proot error: trying to remove a directory outside of '/data/data/com.termux/files/usr/tmp/', please report this error.`

I think the safest way is to have /tmp in ${PREFIX} and clean it on cold start (when Termux has no running sessions) only.

**Comment by Quasic** [comment]
@xeffyr Thanks, coincidentally, I had a problem running pkg up due to missing tmp files about the same time I saw your warning. Rerunning the command after reverting the symlink worked, so I think I agree that the cold start idea is better.

I think it happened this time because an email app download thousands of emails to internal storage, reducing the free space under 500mb, so Android 5 started cleaning much more aggressively.

**Comment by fornwall** [comment]
In the upcoming v0.66 release the `$PREFIX/tmp` folder will be purged at cold start as https://github.com/termux/termux-app/pull/768 has now been merged!
