### ISSUE TITLE
Cannot apt update

### ISSUE THREAD

**Issue by Yajo** [termux/termux-app#64]
I found out today that I cannot update. Am I doing something wrong?

```
$ apt update
Hit http://apt.termux.com stable InRelease
Get:1 http://apt.termux.com stable/main all Packages [1816 B]
E: The method driver /data/data/com.termux/files/usr/lib/apt/methods/xz could not be found.
```

**Comment by fornwall** [comment]
What is the output of `apt --version`?

**Comment by Yajo** [comment]
apt 1.0.10.2 for arm compiled on Aug 25 2015 17:40:58

**Comment by fornwall** [comment]
@Yajo Did you install Termux a few months ago and haven't run `apt upgrade` in a couple of months?

The problem is that the apt version is old, and is not able to work with the new apt repository format. You should be able to manually install the new apt version (and liblzma which newer apt depends on) with:

    wget http://termux.net/dists/stable/main/binary-arm/liblzma-5.2.2_arm.deb
    dpkg -i liblzma-5.2.2_arm.deb
    wget http://termux.net/dists/stable/main/binary-arm/apt_1.2.4_arm.deb
    dpkg -i apt_1.2.4_arm.deb

and after that run `apt update && apt upgrade` to have all packages up to date. Does that work for you?

**Comment by Yajo** [comment]
Indeed, it was my case and that fixed it. Thanks!
