### ISSUE TITLE
Termux runs as i686 on 64 bit Chromebook Pro?

### ISSUE THREAD

**Issue by pwdonald** [termux/termux-app#644]
I've noticed that Termux runs as 32 bit on my 64 bit Samsung Chromebook Pro. Is this a limitation of Google Play on ChromeOS for Intel processors or something that can be patched on Termux?

**Comment by its-pointless** [comment]
Afaik its due to android implementation done on specific chromebook models.

On 1 Apr. 2018 6:24 am, "Donald Jones" <notifications@github.com> wrote:

I've noticed that Termux runs as 32 bit on my 64 bit Samsung Chromebook
Pro. Is this a limitation of Google Play on ChromeOS for Intel processors
or something that can be patched on Termux?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/termux/termux-app/issues/644>, or mute the thread

**Comment by abiosoft** [comment]
Not a Termux issue, rather an Android on Chromebook issue.

**Comment by sdrausty** [comment]
@pwdonald can you check whether this device is truly 64bit?  A while ago some Android Samsung smartphones had issues regarding 64bit not fully implemented on certain devices.

**Comment by abiosoft** [comment]
Yes, the Chromebook is 64 bit. And it is not the only 64 bit Chromebook with 32 bit Android.

**Comment by pwdonald** [comment]
@sdrausty it is a Samsung Chromebook Pro with Intel m3. Any suggestions on how to be double check the arch?

**Comment by sdrausty** [comment]
> not the only 64 bit Chromebook with 32 bit Android.

Not much that can be done if this is the case.  Options include flashing the ROM; Being content with 32bit...

**Comment by sdrausty** [comment]
@pwdonald here is an example with ` file`:
```
[11:20 ~ ]$ file $PREFIX/bin/busybox
/data/data/com.termux/files/usr/bin/busybox: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, stripped
[11:21 ~ ]$ file /system/bin/busybox
/system/bin/busybox: ELF 32-bit LSB executable, ARM, EABI4 version 1 (SYSV), statically linked, stripped
```
See:
```
[11:22 ~ ]$ man file
```
for more information.

**Comment by sdrausty** [comment]
>  Is this a limitation of Google Play on ChromeOS for Intel processors or something that can be patched on Termux?

Device manufacturers choose to use 64 bit hardware mixed with 32bit.  Why?  Possibly manufacturing cost, OS speed and stability issues.
