### ISSUE TITLE
"Storage" permission not available in app settings

### ISSUE THREAD

**Issue by kovan** [termux/termux-app#653]
Hi. I am trying to have write access to an external USB drive from Termux with no success.
From what I have learned, the process should be: run termux-setup-storage, and allow the permission when the pop-up shows up. I have done that multiple times, and the "storage" directory is created, but it doesn't contain the symlink to "external". If I run "df", I can see how the USB disk is already mounted in /storage (read only), but, as I say, the symlink is not created.

After checking, I noticed that, in the Termux settings page, under "Permissions", there is no Storage permission available for enabling or disabling, only a "Memory" permission, which is already enabled. Could this be the reason of "$HOME/storage/external" not being created?. If so, is there any way to make the Storage permission appear?, or is this a bug?

Thanks and keep up the good work.

**Comment by kovan** [comment]
7.0

**Comment by l-jonas** [comment]
@kovan I think "Memory" means "Storage" in this case (because there is no permission to access the RAM). Which Android are you using (Samsung Android, Lineage OS, ...)? Can you access the USB disk with [Amaze](https://f-droid.org/en/packages/com.amaze.filemanager/) (a preinstalled file manager can have higher permissions than external Apps)?

**Comment by Quasic** [comment]
@kovan Did you try deleting the ~/storage folder before re-running '''termux-setup-storage'''? (#572)

**Comment by Quasic** [comment]
You also might want to check logcat. That's where all error messages will be.

**Comment by xeffyr** [comment]
Android doesn't consider USB sticks as stable part of the device and therefore its API doesn't return Termux private file path for it. Relevant section on developers documentation: https://developer.android.com/reference/android/content/Context.html#getExternalFilesDirs(java.lang.String).

Since arbitrary **direct** access to any kind of external storage is not allowed by Android, using `getExternalFilesDirs()` is necessary to obtain proper path to private directory.
