### ISSUE TITLE
gclient/cipd error.

### ISSUE THREAD

**Issue by JacobTDC** [termux/termux-app#698]
I'm not sure if this is a Termux or Google depot_tools issue, but I'm going to try here first.

Whenever I run `gclient`, `fetch`, etc I get this error:
```[P28695 19:21:49.574 remote.go:125 W] cipd: connectivity error (Get https://chrome-infra-packages.appspot.com/_ah/api/repo/v1/instance/resolve?package_name=infra%2Ftools%2Fcipd%2Flinux-arm64&version=git_revision%3A4d19637ec2c3d1efd8c6a1b05285118b786919e2: dial tcp: lookup chrome-infra-packages.appspot.com on [::1]:53: read udp [::1]:45262->[::1]:53: read: connection refused)```
Is this a Termux issue or configuration issue? If so, how would I fix it?

**Comment by wangwenqing3000** [comment]
I have same issue. I try to access the url by chrome and it return "Method Not Allowed".

error info as follow:
[P9824 14:30:02.020 client.go:310 W] RPC failed transiently. Will retry in 1s
 {"error":"failed to send request: Post https://chrome-infra-packages.appspot.co
m/prpc/cipd.Repository/ResolveVersion: dial tcp 75.126.2.43:443: connectex: A co
nnection attempt failed because the connected party did not properly respond aft
er a period of time, or established connection failed because connected host has
 failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"Reso
lveVersion", "service":"cipd.Repository", "sleepTime":"1s"}
[P9824 14:30:24.044 client.go:310 W] RPC failed transiently. Will retry in 2s
 {"error":"failed to send request: Post https://chrome-infra-packages.appspot.co
m/prpc/cipd.Repository/ResolveVersion: dial tcp 75.126.2.43:443: connectex: A co
nnection attempt failed because the connected party did not properly respond aft
er a period of time, or established connection failed because connected host has
 failed to respond.", "host":"chrome-infra-packages.appspot.com", "method":"Reso
lveVersion", "service":"cipd.Repository", "sleepTime":"2s"}

**Comment by nmnm112233** [comment]
@wangwenqing3000 I have same problem,have you already resovled the problem? I try many ways,but the result is not ok. for example I installed shadowsocks and set the httpproxy, but the errors still existed.

**Comment by wangwenqing3000** [comment]
@nmnm112233 set https_proxy=http://localhost:1080 (not https) in cmd and it will be work!

**Comment by nmnm112233** [comment]
@wangwenqing3000 Thanks a lot. Later when I have free time,I'll try.

**Comment by lxxxxxxxx** [comment]
I get the same error information when i try to run update_depot_tools.bat in ./depot_tools dir，did you resolve this problame?

**Comment by wangwenqing3000** [comment]
Yes, you need to run 'set https_proxy=http://localhost:1080' in cmd before
you run depot_tools.bat.

lxxxxxxxx <notifications@github.com> 于2018年9月15日周六 下午12:10写道：

**Comment by woshihoujinxin** [comment]
mark

**Comment by GuoZhiQiang** [comment]
@wangwenqing3000  Thanks . Set https_proxy=http://localhost:1080 (not https)  is the key !

**Comment by jianzhiyao** [comment]
> @nmnm112233 set https_proxy=[http://localhost:1080 (not](http://localhost:1080%C2%A0(not) https) in cmd and it will be work!

`` set https_proxy=http://localhost:1080 `` run in cmd successfully
`` set https_proxy=http://localhost:1080 `` run in powershell is not work.
