### ISSUE TITLE
[Feature Request] arrow keys, CTRL, ALT, ESC, exit terminal, font colour, etc.

### ISSUE THREAD

**Issue by johnny-mac** [termux/termux-app#728]
Hi, I have been using Termux for quite a while on my Android & must say that its my favourite terminal emulator for Android.... There's an SSH app I use called JuiceSSH which gave me this idea, plus when a command doesn't execute properly & it hangs I cannot stop the hanging, nor can I even make termux exit, which forces me to reboot my phone because termux creates a notification that I can't make close...
I have to type exit in order to get termux to exit, that's not good, perhaps you guys could make it so we can close the app from outside of the app?? A feature to change the text colour would also be cool, it would be easier to read the text if it were bright-ish green on a black background for example.
arrow keys would also be a huge help, that way we can cycle through previous commands, its kind of annoying having to re-type the same command on a touch-screen.

This is what JuiceSSH's looks somewhat like:
http://www.androidguys.com/wp-content/uploads/2014/03/juicessh.png

You can hide that extra menu above the keyboard quite easily too.

**Comment by Grimler91** [comment]
The keys were added yesterday in https://github.com/termux/termux-app/pull/605. Update your app to get them. 
You can long press, press more and then kill process to kill a terminal if ctrl + c/ctrl + d/ctrl + z; kill .. doesn't work.

The font colour request probably belongs at github.com/termux/termux-styling.

**Comment by johnny-mac** [comment]
oh awesome, I updated but never saw them, I'll have to check once again. thanks.

**Comment by setuidroot** [comment]
Yeah you can change colors/fonts with termux-styling.  Also... if/when termux hangs, just exit out and force close termux in tasker.  If the termux notification persists, you can slide down on it and click exist.

Termux also has ssh capabilities built in.  "apt install openssh" and then you can just use termux like Juice (but without the GUI) "ssh root@10.0.0.10" as an example.  You can add private SSH keys into /data/data/com.termux/files/home/.ssh

Juice is cool, but not needed IMO; almost everything can be done in termux.

**Comment by johnny-mac** [comment]
How do I use CTRL in Termux???? .....

**Comment by johnny-mac** [comment]
like, I don't see how I am supposed to be able to use CTRL.... you guys need to make it easier to find these buttons, like how they have it in JuiceSSH....

**Comment by setuidroot** [comment]
Volume down key is control (for me)... so say control+c; hold volume down and hit c key.  

I highly recommend hackers keyboard... it has ctl, alt, fn, etc keys like a real keyboard when you use it in horizontal/landscape mode.  Info about it here: https://github.com/klausw/hackerskeyboard

Hackers keyboard is old and not on Google Play anymore (idk why) but it's on github; latest version APK you can download here: https://github.com/klausw/hackerskeyboard/releases/download/1.39.3/hackerskeyboard-v1.39.3.apk

It works on pretty much every android device (at least every one I've used; Android 2-8.)

There's another keyboard that's good for this, it's newer and kept up-to-date, but I don't use it personally.  It's called AnySoftKeyboard...

Info: https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/README.md

Download: https://f-droid.org/repo/com.menny.android.anysoftkeyboard_4630.apk

I highly recommend one of these keyboards for any terminal work (something with arrow keys, ctl, alt and various options to assign key functions.)  Hackers keyboard works great for me, but AnySoft is newer and kept up-to-date; maybe you'd be better off starting out/learning with AnySoftKeyboard since it's actively maintained.

**Comment by xeffyr** [comment]
* To set color schemes & fonts for terminal, use Termux:Styling addon.
* To use special keys like "ctrl" or arrows, there is an *extra-keys row* which is configurable after version 0.66. Some touch keyboards also provide special keys.

Closing.

**Comment by vvkisil** [comment]
Termux is a great app for Linux-users. I commonly use Ctrl+@ as a keybinding for 'mark-set' in Emacs/mg. However, from my BT keyboard it produces the printable character @ only. Would it be possible to change somehow?
(Just in case: in connectbot to my Linux box pressing Ctrl+@ from the same keyboard produces 'mark-set' as expected.)
