### ISSUE TITLE
Cursor style

### ISSUE THREAD

**Issue by nomxs** [termux/termux-app#757]
How do I change the cursor style?

**Comment by empjustine** [comment]
I think the only alternative cursor mode you get is the text input view. From the manual:

Text Input View

Terminal emulators usually do not support the advanced features of touch keyboards like autocorrect, prediction and swipe typing. To solve this, Termux has a text input view. Text entered in it will get pasted to the terminal. Because it's a native Android text input view, all touch keyboard features will work. To access the text input view you have to swipe the extra keys view to the left.
(...)
To enable the extra keys view you have to long tap on the keyboard button in the left drawer menu. You can also press Volume Up+Q.

**Comment by hyperpallium** [comment]
Can also change colour:

    echo -ne "\033]12;#ff0000\007"    # red

**Comment by Cvar1984** [comment]
Install `Termux:style` plugin and go to `~/.termux/colors.properties`
And set the color you want like example below
```
# green cursors
cursor:  #00bb00
```

[My setup](https://github.com/Cvar1984/dotfiles/blob/master/.termux/colors.properties)
