### ISSUE TITLE
Huawei P10 can't get info of CPU, Uptime, etc. 

### ISSUE THREAD

**Issue by buguniaogu** [termux/termux-app#795]
![](https://i.imgur.com/6fyzJZ8.jpg)

**Comment by xeffyr** [comment]
You are using screenfetch ?

If so, then:
1. To get uptime it use /proc/uptime. Access to this file is restricted on Android 8:
```
$ cat /proc/uptime
cat: /proc/uptime: Permission denied
```

2. To get CPU type, it use /proc/cpuinfo which **may not provide** CPU model name.
For example on my device it shows:
```
processor	: 0
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4
...
```

3. For GPU it tries to use tools like nvidia-smi, lspci, glxinfo (they are not available in Termux) and file /proc/fb to which access is restriced too:
```
$ cat /proc/fb
cat: /proc/fb: Permission denied
```

I guess that it will be possible to fix only displaying of uptime (just use 'uptime' tool instead of /proc/uptime).

**Comment by xeffyr** [comment]
@Grimler91 This can be closed.
