### ISSUE TITLE
trouble with fuse

### ISSUE THREAD

**Issue by izmirlig** [termux/termux-app#807]
In termux, I prooted using a script called enter_deb

It proots with a bind mount to dev. I flipped the toggle in app settings and now I can mount the external sdcard 

There's a file linux.img containing a arm64 debian I used on my old phone which was rooted. I'm now trying to get by without root on my Samsung Note 8.

So I'm trying to mount the image file using g ext4fuse, which I built from source.  As root (in proot) ext4fuse bombs with the error "can not open /dev/fuse, permission denied". I can't even get a directory listing.

**Comment by xeffyr** [comment]
> In termux, I prooted

> to get by without root

> So I'm trying to mount the image file using g ext4fuse

Proot won't let you to have access to /dev/fuse without **REAL** root permissions. Just assume that proot is an 'emulator' and everything that it does (root, chroot, mount, etc...) is fake.

**Comment by izmirlig** [comment]
Ok...that was the feeling I was starting to get. That k you for your reply...I'm relieved to know I haven't messed anything up.

One more question.  In my search for answers I uninstalled fuse and reinstalled it. Everything completed successfully. How is this possible? The binding to dev is without permission so /dev/fuse was unchanged?

Also (ok another question). I thought fuse is supposed to work at the user level. Right?

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by xeffyr** [comment]
> In my search for answers I uninstalled fuse and reinstalled it. Everything completed successfully. How is this possible?

You uninstalled & reinstalled package, right ? If so, you just reinstalled fuse userspace tools (like fusermount or library 'libfuse.so'). This doesn't affect /dev/fuse (which is actually provided by kernel).

> The binding to dev is without permission so /dev/fuse was unchanged?

**This is not real binding!** Proot just hooked some syscalls and rewrote some data so program thinks that /dev is mounted to different rootfs. The same goes for root uid/gid. Want to 'play' with root permissions - root your device or use QEMU instead since proot was designed for different purposes.

> I thought fuse is supposed to work at the user level. Right?

Thats on linux distributions only. Android sets strict permissions for /dev/fuse:
```
xeffyr@archlinux:~:$ adb shell ls -l /dev/fuse
crw------- 1 root root 10, 229 2018-08-06 13:34 /dev/fuse
```

\- as you can see, /dev/fuse can be accessed only by root.

While on Linux distro /dev/fuse available for all users:
```
xeffyr@archlinux:~:$ ls -l /dev/fuse
crw-rw-rw- 1 root root 10, 229 авг 10 15:33 /dev/fuse
```

**Comment by izmirlig** [comment]
Thanks for clarifying!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
