### ISSUE TITLE
Copying text mishandles newlines

### ISSUE THREAD

**Issue by robsmith11** [termux/termux-app#809]
When I highlight and copy multiple lines from Termux and paste somwhere else like a web browser, it appears that Termux incorrectly copies the empty space between the last character of a line and right edge of the window as many spaces.

In addition to all the extra spaces, the newline character is aften missing (~ 70% of lines), so multiple lines are merged into one.

**Comment by xeffyr** [comment]
@robsmith11 It seems that this is not a Termux-only problem.

1. Copying multi-line text from browser:
<p align="center"><img src="https://user-images.githubusercontent.com/25881154/44458882-40b39a80-a610-11e8-9b7e-c13b6f4a1785.jpg" width="60%"></p>

2. Result of pasting into 'GNU Nano' editor:
<p align="center"><img src="https://user-images.githubusercontent.com/25881154/44458914-62ad1d00-a610-11e8-9092-868528b65876.jpg" width="60%"></p>

3. Result of pasting into 'QuickEdit Pro' third-party editor:
<p align="center"><img src="https://user-images.githubusercontent.com/25881154/44458958-8f613480-a610-11e8-9c94-f32eb220bca2.jpg" width="60%"></p>

\-\- As you can see, the result (2 & 3) is independent of which Android program is used. However, in Termux this may be related to this commit: https://github.com/easyaspi314/termux-app/commit/db7cfc869417bdd4dda41f86ea847e2de8d0d651, but I'm unsure and should check...

**Comment by robsmith11** [comment]
I haven't tried Nano, but in emacs the syntax color formatting can get glitchy on long lines once in a while, so yeah those issues may also be caused by the same thing.

Unfortunately, I'm not sure how to further debug.

**Comment by sdrausty** [comment]
> Unfortunately, I'm not sure how to further debug.

IFS?

**Comment by sdrausty** [comment]
https://duckduckgo.com/lite/?q=bash+IFS+linux

**Comment by sdrausty** [comment]
https://duckduckgo.com/lite/?q=bash+IFS+linux

**Comment by xeffyr** [comment]
@markosjal Launch nano with `--nowrap` option and problem will be solved.
-------- Исходное сообщение --------От: markosjal <notifications@github.com> Дата: 06.09.2018  6:19  (GMT+02:00) Кому: termux/termux-app <termux-app@noreply.github.com> Копия: Leonid Plyushch <leonid.plyushch@gmail.com>, Mention <mention@noreply.github.com> Тема: Re: [termux/termux-app] Copying text mishandles newlines (#809) 
while touching this topic:
Ihave seen nano corrupt lines of code in termux . If you edit a long line of code in nano on termux you are likely to see the issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/termux/termux-app","title":"termux/termux-app","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/termux/termux-app"}},"updates":{"snippets":[{"icon":"PERSON","message":"@markosjal in #809: while touching this topic:\r\n\r\nIhave seen nano corrupt lines of code in termux . If you edit a long line of code in nano on termux you are likely to see the issue."}],"action":{"name":"View Issue","url":"https://github.com/termux/termux-app/issues/809#issuecomment-418951217"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/termux/termux-app/issues/809#issuecomment-418951217",
"url": "https://github.com/termux/termux-app/issues/809#issuecomment-418951217",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [termux/termux-app] Copying text mishandles newlines (#809)",
"sections": [
{
"text": "",
"activityTitle": "**markosjal**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@markosjal",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"termux/termux-app\",\n\"issueId\": 809,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"termux/termux-app\",\n\"issueId\": 809\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/termux/termux-app/issues/809#issuecomment-418951217"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 368205650\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by xeffyr** [comment]
@markosjal Launch nano with `--nowrap` option and problem will be solved. Just text wrapping...

**Comment by robsmith11** [comment]
This is still an issue.  I've reproduced it by copying/paste from within Termux (no other apps involved).

Unfortunately, there appears to be a random factor.  It only happens about 25% of the time, but seems more frequent when I use mosh and tmux.
