### ISSUE TITLE
Sending Email

### ISSUE THREAD

**Issue by rlp10** [termux/termux-app#83]
Is it possible, or could it be made possible, to send emails entirely through the command line on termux - preferably through the Gmail app?

**Comment by Neo-Oli** [comment]
Yes. You can set up mutt. It's not quite easy to set up mutt with gmail. So you'll probably need to follow some tutorial like [this](https://blog.bartbania.com/raspberry_pi/consolify-your-gmail-with-mutt/).

**Comment by fornwall** [comment]
You can open the Gmail app with pre-filled recipient, text and subject by executing the following command:

    am start --user 0 -a android.intent.action.SEND -t "text/plain" \
        -n com.google.android.gm/.ComposeActivityGmail \
        --esa android.intent.extra.EMAIL "recipient@example.com" \
        --es android.intent.extra.TEXT "Message to send." \
        --es android.intent.extra.SUBJECT "Subject to use"

Note that you cannot send an email without user interaction using the gmail app - it's not possible by design. To automatically send an email you are probably best of looking at mutt as @Neo-Oli says.
