### ISSUE TITLE
Key combinations with extra keys

### ISSUE THREAD

**Issue by SunflowerFuchs** [termux/termux-app#895]
Is it possible to add the functionality to press key combinations (Extra Keys + Modifiers)? 

I often need to type various combinations, e.g. Shift+Tab (for reducing indent in my editor), Ctrl+Home/Ctrl+End (for jumping to file start/end), etc.

Rebinding the keys is theoretically possible, albeit not preferred since i can't change the bindings on the servers at work, and having differing keybindings on private and work environments is prone to errors.

**Comment by pulketo** [comment]
What you need is download/install another keyboard, i would recommend "Hackers keyboard"
https://f-droid.org/en/packages/org.pocketworkstation.pckeyboard/ 

currently it doesn't have a play store url, i don't know why..

**Comment by xeffyr** [comment]
> currently it doesn't have a play store url, i don't know why..

Here is a reason why: https://github.com/klausw/hackerskeyboard/issues/668#issuecomment-431315004...

**Comment by egoisticalgoat** [comment]
Why do i have to install another keyboard though? The keys are already there, I just need to be able to press them combined. I'd prefer not having to install an entire separate keyboard app just to press key combinations in one specific app.
Also, the hackers keyboard wouldn't've been the best solution anyway, because there still is no way to press e.g. Ctrl+Home. I have also tried the CodeBoard Keyboard, same problem, doesn't have a home key.

**Comment by pulketo** [comment]
you don't know what are you missing... give it a try, i do not use android's keyboard at all, i use this keyboard as i'm on my android connected to remote servers or programming scripts almost all the time.

**Comment by egoisticalgoat** [comment]
I don't use the default android keyboard either, and i'm happy with my current keyboard. I've already tried the hackers keyboard, it is missing a few features I need in a keyboard and doesn't solve my problem.

**Comment by quite** [comment]
I sounds like what @egoisticalgoat wants is the possibility to combine the available keys in the extra keys row. For example, there is `Alt` and `/` in the row, so why can't I hit them so produce `Alt-/`? What I currently have to do is hit `Alt` and then find and hit `/` in the main keyboard.

**Comment by egoisticalgoat** [comment]
Yes, exactly. I've also specifically used the keys `Ctrl` and `Home` in the example because very few keyboards have a home key, making a solution like just getting another keyboard virtually useless. 

From a users perspective, `/`, `Home`, Arrow keys, etc. are all input keys (just like normal letters), and `Ctrl` and `Alt` are (usually) modifier keys, so in my opinion there should be nothing preventing me from combining the two.

**Comment by quite** [comment]
I would additionally be happy if long-pressing `-` in the extra keys bar would give a `_`. Is long-pressing at all possible there? And on the topic of this issue, hitting `Alt` in the extra keys should allow for composing both `Alt--` and `Alt-_`.

**Comment by trygveaa** [comment]
This is now fixed for Ctrl and Alt, with the merge of PR #1479. It still doesn't work with Shift though (there is no support for a Shift key in the extra keys row, and the Shift key on the keyboard doesn't work with extra keys).
