### ISSUE TITLE
Prevent accidental key press when swiping the extra keys view to the left to access the text input view

### ISSUE THREAD

**Issue by vovcacik** [termux/termux-app#905]
The title says it all.

User needs to be careful what key to lay his finger on when swiping the extra keys view, because when the swipe begins it registers as key press. One example for all: the "ARROW_UP" button will fill in previous command, this obstructs the new command you are about to type in the text input view.

https://wiki.termux.com/wiki/Touch_Keyboard

**Comment by ticalc-travis** [comment]
I can confirm this issue. This seems to have only become an issue when the extra keys thing was revamped and changed to two rows. Older versions of Termux did not have this problem.

This behavior makes the input view virtually unusable because there is no way (that I can find) to swipe the extra keys *without* sending a spurious keypress to the terminal, thereby messing up the state I need to begin text input in the first place.

**Comment by 9001** [comment]
I tried adding a blank key to the extra keys bar, hoping that would be a draggable point with no side effects -- instead this crashes Termux :p

I would much prefer if sliding in from the right side of the screen toggled this, similar to the burger menu on the left, as I do not otherwise use the extra input bar at all. Adding it just for the purpose of toggling between android-native and terminal-native text input results in an unfortunate waste of space.

**Comment by Quasic** [comment]
I have the same problem since the keyboard was updated to two rows.

**Comment by epitron** [comment]
Ditto!

Is the bar a custom GUI element? If so, a good solution would be to modify its logic so that the keys are activated on release of the button, and if the bar if swiped, the release event is blocked.

**Comment by Quasic** [comment]
#1014 fixed the empty button crash

**Comment by Mhowser** [comment]
Any progress on this?

**Comment by fornwall** [comment]
Thanks for reporting!

Fix has been released in version 0.83 or higher (Android 7+ devices will get version 0.84).

**Comment by vovcacik** [comment]
Just tried it, its great. Thanks!
