### ISSUE TITLE
termux-wake-lock / unlock simply hangs

### ISSUE THREAD

**Issue by mayureshw** [termux/termux-app#914]
Not sure what triggered this, probably a recent upgrade of termux-api package.

termux-wake-lock / unlock commands are simply seen getting hung.

**Comment by xeffyr** [comment]
> probably a recent upgrade of termux-api package.

No, this can't be caused by termux-api as `termux-wake-lock` is part of package 'termux-tools'. But this issue can occur on Android 5 and 6, and can affect all packages that use java-based utilities.

See https://github.com/termux/termux-packages/issues/334

**Comment by mayureshw** [comment]
It's happening with more commands. It's seen happening with termux-open-url. Instead of terminating after launching it stays alive. Top shows a "shutdown thread".

Further, the active processes constantly eat up cpu. The device becomes slow and heats up and battery discharges fast. In settings, power usage of termux is shown as maximum.

I usually update the apps once in a week and intuitively feel that I am facing this for a week, so may be last week's update caused something. But not sure about it.

Following is a snapshot of "top" showing the "shutdown thread"

21914 16793 u0_a61   R    87096  4.4   2 25.0 {Shutdown thread} /system/bin/app_process / com.example.termuxam.Am start -a android.intent.action.VIEW -d http://....
22231     1 u0_a61   R    87096  4.4   3 25.0 {Shutdown thread} /system/bin/app_process / com.example.termuxam.Am broadcast --user 0 -n com.termux.api/.TermuxApiReceiver --es socket_input 7feb6b
21860     1 u0_a61   R    87096  4.4   1 25.0 {Shutdown thread} /system/bin/app_process / com.example.termuxam.Am broadcast --user 0 -n com.termux.api/.TermuxApiReceiver --es socket_input 6a45c1

**Comment by Grimler91** [comment]
@mayureshw Are all packages updated?

What's your output of `termux-info`?

**Comment by xeffyr** [comment]
Output of `logcat -d` is needed too (immediately after executing termux-api command).

Also you may try to execute this:
```
for lib in $(find /system/framework -type f -iname \*.jar); do
    BOOTCLASSPATH=${lib}:${BOOTCLASSPATH};
done
BOOTCLASSPATH=${BOOTCLASSPATH%%:}
export BOOTCLASSPATH
```
\- helped me to deal with non-working termux-api on Android 6.

**Comment by mayureshw** [comment]
Sorry. The problem recurs randomly. It only appeared that package upgrades solved it. But then it recurred. My termux-info is:

```
$ termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 3.10.49-yuos+ #1 SMP PREEMPT Fri Sep 9 20:15:57 IST 2016 aarch64 Android
Termux-packages arch:
aarch64
Android version:
6.0.1
Device manufacturer:
YU
Device model:
YU5010
```

This is logcat -d since invoking termux-wake-lock, waiting and hitting Ctrl-C
```

11-13 14:10:28.867 22620 22620 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10061 <<<<<<
11-13 14:10:28.872 22620 22620 D AndroidRuntime: CheckJNI is OFF
11-13 14:10:28.915 22620 22620 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
11-13 14:10:28.969 22621 22621 E dex2oat : Failed to create oat file: /data/dalvik-cache/arm64/data@data@com.termux@files@usr@libexec@termux-am@am.apk@classes.dex: Permission denied
11-13 14:10:28.969 22621 22621 I dex2oat : dex2oat took 366.667us (threads: 4) 
11-13 14:10:28.971 22620 22620 W art     : Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg /data/data/com.termux/files/usr/libexec/termux-am/am.apk --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=generic --instruction-set-features=default --no-watch-dog --dex-file=/data/data/com.termux/files/usr/libexec/termux-am/am.apk --oat-file=/data/dalvik-cache/arm64/data@data@com.termux@files@usr@libexec@termux-am@am.apk@classes.dex) because non-0 exit status
11-13 14:10:29.005 22620 22620 I Radio-JNI: register_android_hardware_Radio DONE
11-13 14:10:29.040 22620 22620 D AndroidRuntime: Calling main entry com.example.termuxam.Am
11-13 14:10:29.112 22620 22620 D AndroidRuntime: Shutting down VM

```

**Comment by xeffyr** [comment]
@mayureshw In this case see https://github.com/termux/termux-api/issues/217#issuecomment-419978116.
There no solution other than wiping **dalvik** cache from recovery.

***

### Why this happens

Shortly: DalvikVM never should be called from regular application but Termux does it.

Since Termux puts dalvik cache file (a one that ends in `*@classes.dex`) to system directory /data/dalvik-cache, Android doesn't know anything about it. And when Termux changes it's UID or you accidentaly run `termux-wake-lock` from root shell, the dalvik cache file becomes **inaccessible**.

**Comment by mayureshw** [comment]
No my phone isn't rooted. I have never run termux as root. Also, there was nothing unusual happening on phone. This issue started all of a sudden and was not constantly present. Once in 2/3 days it used to go into "issue-state" and would get resolved on reboot.

Anyway I tried wiping dalvik cache as suggested. Not a termux issue, but sharing what happened: After wiping cache using "fastboot erase cache" my phone could not boot again. Had to reflash the OS. During reinstallation twrp gave errors like "can't mount cache" etc. The errors went away after wiping cache once again. I lost a lot of data.

The stock OS wasn't booting on reflashing. So I switched over to lineage 15.1 / android 8.1. Will observe it for 2/3 days and report.

**Comment by xeffyr** [comment]
>Anyway I tried wiping dalvik cache as suggested
>fastboot erase cache

Nothing that there a **big** difference between `Wipe Dalvik Cache` and `Wipe Cache Partition` ? Also, dalvik cache should be wiped from **recovery**.

> During reinstallation twrp gave errors like "can't mount cache" etc. The errors went away after wiping cache once again. I lost a lot of data.

If you want to use fastboot, use `fastboot format cache` next time instead of `erase`. Also, if you will do only **required** things, then you won't lose data.

***

Everything that you need is to select 'Dalvik Cache' in wipe menu:
![dcache](https://user-images.githubusercontent.com/25881154/48482403-44267e80-e819-11e8-808f-5eb9e247350a.jpg)

Wiping dalvik cache doesn't harm anything. In fact, it sometimes may get restructured/optimized, that's why you observing `Once in 2/3 days it used to go into "issue-state" and would get resolved on reboot.`.

But anyway, I never encountered such issue. Regardless of custom/stock ROMs.

**Comment by kridopratomo** [comment]
can I open the bot loader with termux?
