### ISSUE TITLE
bash error

### ISSUE THREAD

**Issue by Alanovsky** [termux/termux-app#922]
I recently updated Termux packages from custom repostories and when i run Termux i'm getting this error
```
/data/data/com.termux/files/usr/bin/login: 23: exec: /data/data/com.termux/files/usr/bin/bash: not found
```
How can i repair this or at least backup Termux data?

**Comment by xeffyr** [comment]
> from custom repostories

Can you tell which exactly 'custom' repositories ?

> /data/data/com.termux/files/usr/bin/bash: not found

Wondering why nothing was disappeared from /sdcard...
The main rule of shell user is to **always know what you are doing** =).

> How can i repair this

Deleted shell binary cannot be repaired. Also we don't know what else is missing.

> backup Termux data?

```
cd /data/data/com.termux/files
tar -cvf /sdcard/home.tar home
```

Another variant is just to copy a directory, but permissions will be lost:
```
cp -a $HOME /sdcard/termux-home
```

If main shell isn't working at all, try fail-safe shell then.

***

Termux is a **single-user** 'system'. This is by design and can't be changed. You need to be extremely careful when downloading and executing scripts from the Internet as things that may occur can be even worse than missing bash.

**Comment by Alanovsky** [comment]
Bash is not missing, i'm 100% sure because before Termux restart when i executed `bash` it worked normally.

> If main shell isn't working at all, try fail-safe shell then.

How can i do that?

**Comment by Alanovsky** [comment]
>Can you tell which exactly 'custom' repositories ?

I've added Debian armel repositories and i checked is packages from this repository works.

**Comment by xeffyr** [comment]
> Debian armel repositories

Termux is not a Linux distribution. It depends on Android's libc and linker, this means that programs from Debian are not working here. If they working, why we have to use own repo ?

Also, Termux doesn't following standards (it is not possible here). For example, our root file system is stored in `/data/data/com.termux/files/usr`.

Read this article on Termux Wiki: https://wiki.termux.com/wiki/Differences_from_Linux

We never supported Debian/Ubuntu repositories as main ones for Termux. And never will be support. Just ABI incompatibility + our primary target is 100% compatibility with Android.

> How can i do that?

Swipe right to open drawer and do long-click on 'keyboard' button. Then tap 'failsafe'.

@Grimler91 Issue can be closed.

**Comment by xeffyr** [comment]
Next time install Debian packages in chroot.
