### ISSUE TITLE
[Questing] Using different base OS?

### ISSUE THREAD

**Issue by Pernat1y** [termux/termux-app#941]
Hello.
Is there is any way to run different OS as a base in Termux (instead of Debian-ish OS)?
Yes, I know, that it is possible to run plenty of operation systems inside proot in Termux, but it seems like a bit of overhead, as for me.
(Sorry, if it is duplicate, but cannot seems to find any related information).

**Comment by Grimler91** [comment]
Hi, what would you like to change by changing to something else than debian-ish? 
Python (for example) from our debian-ish OS will be the same as python from a "insert-os-here"-ish os. If you want to use for example pacman instead of apt then sure it is possible but you need to create build scripts, recompile all packages and setup a pacman repo for them.

In general running a different OS will mean a lot of work, running packages from normal linux distros simply doesn't work since [android isn't linux](https://wiki.termux.com/wiki/Differences_from_Linux) and hence proot is needed to make it work.

Was this sort of what you were asking?

**Comment by xeffyr** [comment]
> Is there is any way to run different OS as a base in Termux (instead of Debian-ish OS)?

It's not OS. Just set of patched & packaged programs. See https://github.com/termux/termux-packages.
OS here is only one - Android.

**Comment by Pernat1y** [comment]
I thought that Termux is using patched Debian image in some chroot environment (like proot).
Sorry, if my question sounds rude or inappropriate.
