### ISSUE TITLE
Request: Add the ability to use commands installed by magisk or any outside sources

### ISSUE THREAD

**Issue by nitanmarcel** [termux/termux-app#972]
Hi! I've noticed that by default there's no way to use installed cmd tools by magisk or any other source inside termux. The only way to do this is by adding the next line I got from a telegram user to bash.bashrc: `export PATH="/sbin:/system/xbin:/system/bin:$PATH"`

I suggest to have this set as default as when users install the app won't have to repeat the process over and over again.

Thanks!

**Comment by Grimler91** [comment]
Hi, 
Well you can access the same tools by typing their full path: `/system/xbin/{TOOL}` so it is very possible to use the magisk tools, no need to set the path except for convenience. 

> I suggest to have this set as default 

Not everyone uses magisk so we are unlikely to make this change. Great that you reported is so that other users can benefit from the PATH trick though! 
Note that it is better to put your bashrc customization in `~/.bashrc` instead of `$PREFIX/etc/bash.bashrc`, bash.bashrc is overwritten when bash is updated while ~/.bashrc is left alone.
And finally also note that putting /system/bin and /system/xbin before /data/data/com.termux/files/usr/bin in $PATH will most likely break some termux scripts/programs as they pick up other versions than they expect

**Comment by cswl** [comment]
If your use-case is to run the tools as termux user then a `~/.bashrc` should suffice.

I'm thinking of building tsu as full level `sudo` replacement, which will allow you to change userid and even SELinux context.

This will allow to run Termux services as other app "shell" which has lot of permissions than an app etc

**Comment by eMPee584** [comment]
so `export PATH="$PATH:/system/bin:/system/xbin:/system/sbin:/sbin/.magisk/img/ssh/usr/bin"` it is.. but had to create the `.bashrc` from within termux, as via SSH the SELinux contexts were not set and I received a `.bashrc: Permission denied` (even though owner and permission were correct).

**Comment by nitanmarcel** [comment]
@eMPee584 Use the bash.bashrc file located at       /data/data/com.termux/files/usr/etc/ instead of creating a bashrc file
